api/routes/atom-routes.js, src/containers/AtomReader/AtomReader.jsx, src/containers/AtomReader/AtomReaderVersions.js, src/containers/AtomReader/reducer.js
Hey,
Here is the pull request with some of the versionsData rendered. The URLs to older versions do not work.
=> versionsData for architecture2

package.json, src/routes.js, webpack/dev.config.js
- Move code splitting to production only
- Changed the source map configuration in development builds
- Added happypack
=> Refactored code splitting and dev builds.

src/components/AtomTypes/Document/DocumentEditor.jsx, src/components/AtomTypes/Document/collab/carets.js, src/components/AtomTypes/Document/collab/mod.js, src/components/AtomTypes/Document/collab/server-communications.js
=> Making the participants list update so carets work

api/routes/atom-routes.js, api/routes/journal-routes.js, api/routes/user-routes.js, src/containers/AtomReader/AtomReader.jsx, src/containers/AtomReader/AtomReaderFollowers.jsx, src/containers/AtomReader/AtomReaderFollowers.test.js, src/containers/AtomReader/reducer.js, src/containers/JournalProfile/JournalProfile.jsx, src/containers/JournalProfile/JournalProfileFollowers.jsx, src/containers/JournalProfile/reducer.js, src/containers/UserProfile/UserProfile.jsx, src/containers/UserProfile/UserProfileFollowers.jsx, src/containers/UserProfile/UserProfileFollowers.test.js
This is the way that profiles are styled:
I will be pushing more to this branch, so I don't imagine that it matters if you want to pull it in now or later.  : )
Also we must have lost some of your followers upon migration, you may want to look into that.
=> List followers on user profiles

api/routes/version-routes.js, src/containers/Atom/Atom.jsx
=> Added space to contributors

src/client.js
Error replaced with warning.  : )
=> Linting Fix: https://github.com/pubpub/pubpub/pull/195 

api/config.sample.js
config.sample.js was updated, not anymore
=> updated config.sample

client/components/CommunityPreview/CommunityPreview.js, client/components/CommunityPreview/communityPreview.scss, client/components/PubBody/pubBody.scss, client/containers/Explore/Explore.js, client/containers/Page/Page.js, client/containers/Pricing/Pricing.js, client/containers/Pricing/pricing.scss, server/clientRoutes/explore.js, server/models.js
- New pricing language
- Horizontal explore cards
- Displays title if there's no community image
- Restricts explore query to (naive) more active communities
- Adds show all explore query
=> Week of 10/29 fixes

client/components/Footer/Footer.js, client/components/Footer/footer.scss, client/components/InputField/InputField.js, client/components/InputField/inputField.scss, client/components/PageWrapper/PageWrapper.js, client/containers/About/about.scss, client/containers/Explore/explore.scss, client/containers/Landing/landing.scss, client/containers/Pricing/Pricing.js, client/containers/Pricing/pricing.scss, client/containers/UserCreate/UserCreate.js, client/containers/UserCreate/userCreate.scss, package-lock.json, server/apiRoutes/communities.js, server/apiRoutes/communityAdmins.js, server/apiRoutes/index.js, server/apiRoutes/subscribe.js, server/apiRoutes/users.js, server/mailchimpHelpers.js
TODO: Test creating a new community and adding someone to it to make sure mailchimp adds tags. Unsure how to do that on local.
=> new: Newsletter and footer

client/components/DiscussionThreadItem/DiscussionThreadItem.js, client/components/Header/Header.js, client/components/ImageUpload/ImageUpload.js, client/components/ImageUpload/imageUpload.scss, client/components/LayoutEditorBanner/layoutEditorBanner.scss, client/containers/Pub/Pub.js
=> Dev 12 10 quick

client/components/DashboardDetails/DashboardDetails.js, client/components/FormattingBarControls/formattingBarControls.scss, client/components/NavDrag/NavDrag.js, client/components/PubHeader/PubHeader.js, client/components/PubOptionsDetails/PubOptionsDetails.js, package-lock.json
- Update pub title when changing from options.
- Fix citation / footnote structured text overlap.
- Use color picker in site details.
- Fixes a little timeout/update bug I found when closing pub options.
=> Dev fixes 1 14 19

client/components/PubHeader/PubHeader.js, client/components/PubInlineMenu/PubInlineMenu.js, client/components/PubOptions/PubOptions.js, client/containers/Pub/Pub.js, package-lock.json, server/clientRoutes/pub.js
See example on localhost/dev here: http://localhost:9876/pub/lb9afcp5
=> Disallow public comment on hardcoded pub list

package-lock.json, server/clientRoutes/pub.js
Disables a list of specific pubs for public discussion.
=> update: Add list of pubs to disallow public discussion.

client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/PubRow.js, client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/collectionEditor.scss
This is just a thing I remembered a few folks have requested. Seems to play just fine with DND. Feel free to tell me to get lost if now's not a good time for it, but I was there, remembered it, had a second, so why the heck not.
=> update: Add link to Pub from collection DND pane

client/components/GdprBanner/GdprBanner.js, client/containers/Privacy/Privacy.js, client/containers/Privacy/PrivacyPolicy.js, client/containers/Privacy/PrivacySettings.js, client/containers/User/UserEdit.js, client/containers/User/userEdit.scss, package-lock.json
Addresses #393 #394. I'm having to punt on #387 until next cycle, so this temporarily removes the GDPR tab, but I think that's ok.
=> Privacy language

client/components/Footer/footer.scss, package-lock.json
=> Mobile footer subscribe centering fix

client/containers/Dashboard/DashboardContent/Settings/Settings.js, client/containers/Dashboard/DashboardContent/Settings/settings.scss, client/containers/Privacy/PrivacySettings.js, package-lock.json
- Adds export and delete section to community settings page
- Tweaks user export and delete mailto formatting and language
Addresses #395 and #396.
=> New/update: Community and User Export & Delete

client/containers/Pricing/Pricing.js, client/containers/Pricing/pricing.scss, server/server.js
Updates pricing page to reflect new ideas from last week given the attention from HDSR. Feedback on text welcome.
=> update: Pricing page

client/components/Footer/Footer.js, client/components/FormattingBar/FormattingBar.js, client/components/Header/Header.js, client/components/NavBar/NavBar.js, client/containers/Dashboard/DashboardSide.js, client/containers/Landing/Landing.js, client/containers/Landing/landing.scss, client/containers/Pub/PubDocument/PubBody.js
Mostly involves labels and roles — addresses #540 #541 #546 
_Test plan:_
- Check that the "Join PubPub" does not appear on the homepage for logged-in users
- Check that the focus rings on the dark background of the homepage are an appropriate color
- Check that you can navigate the Page header with a screenreader
- Check that the Pub body is announced as "main content" by a screenreader.
=> update: A handful of a11y-related quick fixes

workers/tasks/export/html.js, workers/tasks/export/metadata.js
All this does is makes the title color of the PDF the community dark color. We'll do more branding later, but this is a small thing that will make folks happy for now.
=> Paged branding

client/components/Menu/Menu.js
=> fix: Bump menu zindex to show over pub header

server/routes/pubRedirects.js
This PR fixes an issue with pub redirects that are inbound with an access hash. 
Access hashes used to live on Branches, and now live on Pubs. If the inbound accessHash matches the `viewHash`, `discussHash`, or `editHash`, the Pub's respective accessHash is placed in the redirect route. 
`discussHash` has been deprecated as `viewHash` on Pub confers discuss privileges.
**Test**
Test the functionality (on the auto-generated review app if you wish!) by navigating to `/pub/plf0syc4/branch/2?access=7mawlz01`. The `7maw...` hash was the `editHash` on the draft branch before migration. You should land on the Pub draft with edit permissions.
=> fix: access-hash redirect bug

client/containers/Signup/Signup.js
fix for #775
_Test_
- Run www community on local
- Visit `/signup`
- Enter an email that doesn't already exist in the system (ie, `you+testuser@knowledgefutures.org`)
- Verify that request is submitted and you receive an invite email
=> fix: signup page error hook

client/containers/Pricing/Pricing.js
=> update: Language suggestions

server/editor/queries.js, utils/pub/metadata.js
This PR fixes #913. See that issue for further conversation.
=> fix: custom citation label crashing for empty structuredValue

.gitignore, .replrc.js, package-lock.json, package.json, tools/devshell.js, tools/index.js, workers/tasks/index.js
I wanted a Node REPL that executes in a PubPub environment, so I made one:
You can access it with `npm run tools devshell`. Give it a shot!
=> dev: Implement a devshell

client/containers/Pub/PubSuspendWhileTyping.js
It has become something of a running joke at this point, but I have found another way to make `PubSuspendWhileTyping` faster.
The gist of this component is that it renders a cached version of its subtree if the user is currently typing into the editor, to keep the editor snappy. If a `PubSuspendWhileTyping` doesn't re-render, it sets a timer and checks back after a configurable number of milliseconds. While this is happening, a function called `markLastInput` is called on every editor keypress, to indicate that the user is still typing. But it turns out that even this single function can eat up quite a bit of time, since it invokes a state update and triggers a bunch of React lifecycle stuff:
The solution is to store the input time in a ref instead of a state hook (and to memoize some …
=> dev: Make PubSuspendWhileTyping faster

client/components/Members/InheritedMembersBlock.tsx, client/containers/App/Breadcrumbs/Breadcrumbs.tsx, client/containers/App/Breadcrumbs/CreateCollectionDialog.tsx, client/containers/DashboardOverview/OverviewRow.tsx, client/containers/DashboardPage/DashboardPage.tsx, client/containers/DashboardPages/CreatePageDialog.tsx, client/containers/DashboardReviews/DashboardReviews.tsx, client/containers/DashboardSettings/CollectionSettings/CollectionSettings.tsx, client/containers/DashboardSettings/CommunitySettings.tsx, client/containers/DashboardSettings/PubSettings/Collections.tsx, client/containers/DashboardSettings/PubSettings/DeletePub.tsx, client/containers/DashboardSettings/PubSettings/PubSettings.tsx, client/containers/Pub/PubHeader/UtilityButtons.tsx
Just a quick PR to remove some ts-expect-error comments.
=> fix: remove ts-expect-error comments related to getDashUrl

app.json, jest.config.js, package-lock.json, server/collection/queries.js, server/pub/model.js, server/rss/__tests__/api.test.js, server/rss/__tests__/data.js, server/rss/__tests__/getFeedItemForPub.test.js, server/rss/__tests__/getQueriedPubIds.test.js, server/rss/api.js, server/rss/queries.js, stubstub/global/setup.js, stubstub/modelize/builders.js, utils/pub/contributors.js, utils/pub/downloads.js
This PR implements the [RSS Filtering spec](https://notes.knowledgefutures.org/pub/qtf79s0u/draft), adding:
- `dc:creator` elements for every author associated with a Pub
- `enclosure` elements for downloads
- `category` elements for Collections
It also adds some useful query parameters:
- `collections` accepts a list of Collection slugs like `s1,s2,-s3` where the `-` indicates exclusion.
- `connections=false` will exclude Pubs that are children via Connections
- `published(Before|On|After)` will filter Pubs by publication date (based on Releases or `customPublishedAt`)
_Test plan:_
```
npm run test-dev server/rss
```
Also, visit a community and check out its RSS feed at `rss.xml`. Try out the query parameters listed above.
Resolves #1028
=> RSS improvements

client/components/AccentStyle/AccentStyle.tsx, client/components/ClickToCopyButton/ClickToCopyButton.tsx, client/components/Editor/styles/main.scss, client/components/Header/header.scss, client/components/NavBar/NavBar.tsx, client/components/NavBar/navBar.scss, client/components/PubHistoryViewer/PubHistoryViewer.tsx, client/components/PubReleaseDialog/PubReleaseDialog.tsx, client/components/PubReleaseDialog/pubReleaseDialog.scss, client/components/PubShareDialog/PubShareDialog.tsx, client/components/Thread/ThreadEvent.tsx, client/components/Timeline/timelineStories.tsx, client/containers/DashboardOverview/PubOverview/PubTimeline.tsx, client/containers/DashboardPage/DashboardPage.tsx, client/containers/DashboardReview/DashboardReview.tsx, client/containers/Pub/PubDocument/PubHistoricalNotice.tsx, client/containers/Pub/PubDocument/PubInlineMenu.tsx, client/containers/Pub/PubDocument/PubMouseEvents/HeaderPopover.tsx, client/containers/Pub/PubDocument/pubBody.scss, client/containers/Pub/PubDocument/pubHistoricalNotice.scss, client/containers/Pub/PubHeader/CitationsPreview.tsx, client/containers/Pub/PubHeader/DraftReleaseButtons.tsx, client/containers/Pub/PubHeader/PubHeaderContent.tsx, client/containers/Pub/PubHeader/details/PubDetails.tsx, client/containers/Pub/PubHeader/draftReleaseButtons.scss, client/containers/Pub/PubHeader/largeHeaderButton.scss
This PR contains all the fixes @djagdish introduced in #1023, rebased on latest master, with each affected change "rewritten" in TypeScript.
Test Plan:
- Verify this code works exactly the same as #1023.
=> Release workflow updates loosely converted to TypeScript

client/containers/Page/Page.tsx
Very quick patch to restore narrow widths. Will need to be fixed more upstream when @idreyn returns.
=> fix: Restore narrow widths

client/components/Editor/styles/figure.scss
Closes #1134 (for real this time).
=> fix: always enable pointer events in pub figures

client/containers/DashboardSettings/PubSettings/Doi.tsx, client/containers/Pub/PubHeader/pubHeaderStories.tsx, server/collection/queries.js, server/collectionPub/model.js, server/collectionPub/queries.js, server/doi/queries.js, server/rss/__tests__/getFeedItemForPub.test.js, server/rss/queries.js, server/utils/citations/generateCitationHtml.js, stubstub/modelize/builders.js, tools/migrations/2020_11_19_removeIsPrimary.js, utils/collections/primary.ts, utils/crossref/__tests__/data/pub.js, utils/pubPageTitle.js, utils/storybook/data/dataOverview.js, utils/storybook/data/dataPub.js, utils/types.ts, workers/tasks/export/metadata.js
It's been quite a journey but we're finally here!
_Test plan:_
Run `npm run test` to check everything. There's some decent coverage of the API but we should probably also do a manual QA pass before deploying this one.
=> update: Remove remaining references to CollectionPub.isPrimary

client/components/FormattingBar/BlockTypeSelector.tsx, client/components/FormattingBar/CommandMenu.tsx, client/components/FormattingBar/blockTypeSelector.scss, client/components/NavBar/NavBar.tsx, client/containers/Pub/PubDocument/pubBody.scss
**Screenshot showing updates to header styles & block selector dropdown**
**Style-set rendered in Figma with font info**
**Overflow gradient in navbar-dark**
**Overflow gradient in navbar-light**
=> UI: Navbar, Header styles, Block style selector

client/containers/Pricing/Pricing.tsx, client/containers/Pricing/pricing.scss
Updates pricing page for late 2020 based on Community feedback and internal discussions.
=> Update pricing page

utils/crossref/communities.js
Also adds the new apa journal.
=> add rochester doi prefix

utils/licenses.js
Makes a long overdue change to give all communities all the CC licenses.
_Test plan_
- Visit a community without the premium flag
- Make sure they can now select from all 5 cc license options
=> update: give everyone all the cc licenses

server/pub/permissions.ts, utils/crossref/communities.js
Resolves #1361, and adds a new MITP crossref community.
=> Citation options and deposit quick fix

client/containers/Pub/usePubNotes.ts
Fixes citations with structured values not sorting alphabetically in pub bottom citation list.
=> fix: alphabetize structured citations

client/components/Header/Header.tsx, client/containers/Explore/Explore.tsx
Adds Explore to the WWW global nav, and updates Explore page text (with some edits), which, when combined with DB changes I made today, resolves #1478.
_Test plan_
- Make sure explore page link in global nav works
- Make sure text on explore page is updated, and link to community creation works
- Make sure www global nav looks good on mobile
=> update: Change explore text and add explore link to www menu

client/components/NavBar/navBar.scss
=> fix: Removed navbar fade for larger displays (width > 1200px)

server/utils/citations/citeStyles/american-medical-association.csl, utils/citations.ts
add AMA citations to the options citation style
=> enhancement: add AMA to citation styles

server/pub/__tests__/queryMany.test.ts, server/pub/queryMany.ts, server/submissionWorkflow/__tests__/api.test.ts, types/pubQuery.ts
issue number #1620
Query pubs based the presence of a submission status
=> enhancement: query many submissions

utils/crossref/communities.js
=> update: add ISU, NCSU, JBT crossref prefixes

client/components/Layout/Layout.tsx, client/components/Layout/LayoutSubmissionBanner.tsx, client/components/Layout/LayoutSubmissionBannerSkeleton.tsx, client/components/index.ts, client/containers/Collection/Collection.tsx, client/containers/DashboardSubmissions/NewSubmissionWorkflowEditor.tsx, server/pub/__tests__/queryMany.test.ts, server/routes/collection.tsx, server/routes/pubDocument.tsx, server/submission/api.ts, server/submissionWorkflow/queries.ts, server/utils/queryHelpers/pubGet.ts, utils/layout/types.ts
Kind of resolves #1616 
This is mostly code that glues together stuff we already have.
- Causes the workflow editor on the Submissions tab to actually create a workflow when "Save and Continue" is clicked.
- When a workflow is present and enabled a very basic looking submissions banner will appear in its layout. It will have a Submit button that can be clicked to create a new Pub
Lots of work left to do here, this is just enough code to help us test as we build other parts of Submissions.
_Test plan:_
Make sure the above things work :)
=> update: Really basic SubmissionWorkflow banner

client/utils/useManyPubs/ordering.ts, server/pub/__tests__/queryMany.test.ts, server/pub/model.ts, server/pub/queryMany.ts, server/submission/__tests__/api.test.ts, server/submission/model.ts, server/submission/queries.ts, stubstub/modelize/link.js, types/pub.ts, types/pubQuery.ts, types/submission.ts
Resolves #1679 
_Test plan:_
```
npm run test-dev server/submission/ server/pub/
```
=> update: Add Submission.submittedAt field (and update queries to support it)

client/containers/About/About.tsx, client/containers/About/about.scss, client/containers/CommunityCreate/CommunityCreate.tsx, client/containers/Landing/Landing.tsx, client/containers/Pricing/Pricing.tsx, client/containers/Pricing/pricing.scss, client/containers/UserCreate/UserCreate.tsx
Updated pricing page, about, community creation for membership.
Also adds DOI notice to community creation page and (long overdue) terms acceptance to user signup and community creation pages.
_Test plan_
- Make sure you cannot create a new community without the I accept box checked.
- Make sure you can with it checked (and other required fields filled out).
- Make sure you cannot create a new user without the I accept box checked.
- Make sure you can with it checked (and other required fields filled out).
=> update: Pricing, About, User Creation, Community Creation

client/containers/Pricing/Pricing.tsx
=> fix: pricing typo

utils/licenses.ts
=> fix: change cc-0 license version from 4.0 to 1.0

client/containers/Pub/SpubHeader/SpubHeaderToolBar/SubmitDialog.tsx
Addresses #1907
_Test plan_
create a spub
submit it
immediately after the submission goes through, where there used to be a 'submit' button it should now display `status: pending`
=> Update submissionsState after submitting

server/utils/email/communityServices.ts, server/utils/email/reset.ts, server/utils/email/signup.ts, tools/emailUsers.js
A fast-follow to #1927 to apply the same fix to other Mailgun calls.
=> fix: use spam fix in other mailgun calls

client/components/DashboardFrame/DashboardFrame.tsx, client/containers/DashboardOverview/CollectionOverview/DashboardCollectionOverview.tsx, client/containers/DashboardOverview/CollectionOverview/dashboardCollectionOverview.scss, server/routes/dashboardCollectionOverview.tsx
This adds a banner to collections that have submissions open 
Test plan:
Navigate to Collections that do not have any submissions open. 
Make sure the banner is not present
Navigate to collections with submissions open
Make sure the banner is present
(order not relevant)
=> Submissions are Open Banner

client/components/Banner/Banner.tsx, client/components/Banner/banner.scss, client/components/index.ts, client/containers/DashboardOverview/CollectionOverview/DashboardCollectionOverview.tsx, client/containers/DashboardOverview/CollectionOverview/dashboardCollectionOverview.scss
Digivolve the open submissions banner to be more generic and take ina right positioned ReactNode
Test:
Logout and be sure you cant see a banner
Try changing your personal profiles permissions, as admin, and be sure you can't see that banner when logged in, as not the admin
Then log in as admin again, and take a look at that banner...mmmm good ole visual feedback
=> Banner and Button

server/scopeSummary/queries.ts
Follow up on `scopeSummary` augmentation to include submissions, this time resolving erroneously counting only spubs towards a scope's pubs.
=> Fix scopesummary calculation, use simplified sequelize syntax

package-lock.json, package.json, server/routes/pubDocument.tsx
This addresses #1953 
webscraping is intensive on the pubDocument API routes(because scraping pubs). We need to enable rate limiting to throttle requests and add resistance to potential DOS attacks. 
Rate limiting is used to limit requests from IP addresses or users or both. We can use two libraries
- express-rate-limit 
- To alleviate request load through request rejection
- Since the node version we use is 12.13.1 we can't use express-rate-limit 
- we will instead use express-slow-down 
- express-slow-down
- Will slow down the request and add them to a queue to be completed at some time
- adds a new request field called `req.slowdown`
Set API limiting to something to something this for the routes in `server/routes/pubDocument.tsx` :
```
const speedLimiter = slowDown({
windowMs: 60000, …
```
=> enhancement: Slowdown Route Request 

client/components/Editor/utils/view.ts, client/containers/Pub/PubDocument/PubBody.tsx
=> fix: restore citation/tooltip/discussion functionality to Pub release

client/components/Editor/views/NotePopover.ts
solves issue #1980 
DOI hyperlinks in editor popovers are now linkified
test:
visit a pub to create a citation and footnote.
hover over them. 
structured citations should have clickable doi
unstructured should have clickable links
=> Adds DOI hyperlinks for citation popover

client/components/PubPreview/PubPreview.tsx, client/containers/Pub/PubHeader/EditableHeaderText.tsx
Restores multiline to header to fix long headers not wrapping and breaking everything.
=> HOTFIX: Header

server/utils/queryHelpers/communitySanitize.ts, server/utils/queryHelpers/scopeGet.ts
solves issue #2023 
I added the can view/manage/edit permissions explicitly
test:
edit your personal user to have view roles from the team pub pub admin
login as that user
be sure you can see all collections at the community level
=> Fix View Permissions

client/components/TitleEditor/TitleEditor.stories.tsx, client/components/TitleEditor/TitleEditor.tsx, client/components/index.ts
A nascent "rich-text-lite" title editor:
https://user-images.githubusercontent.com/6402908/169867704-add503ae-e387-41c7-97ee-0e569903fdfa.mov
=> feat: add simple title editor with bold/italics functionality

client/components/TitleEditor/TitleEditor.tsx, client/containers/Pub/PubHeader/TitleGroup.tsx, server/pub/queries.ts
Adresses #2052 & #2053 
Will now render `&` character in document title and update in realtime
=> Handle Some of Header Text Issues

server/utils/citations/generateCitationHtml.ts
Fixes citation-js error by adding lang back into last callsite I forgot.
=> fix: specify language of cite

client/components/Editor/plugins/inputRules.ts
Resolves #2141
We caught a few issues with the input rule that automatically converts `$ this $` to inline math:
1. It fires on sentences involving money ("$7.00 to $9.00")
2. It fires inside of inline code marks, which makes it hard to discuss how to use the feature
This PR fixes these issues. I have also added an equivalent rule for turning single backticks into inline code (finally!)
_Test plan:_
Okay, my brain is too fried to write all this out. But here is some stuff you can try to replicate. Let me know you see anything funky. Note that the fourth line down will trigger a new problem because we no longer match `$ this when it has a TeX dollar sign ($) in it $`. I think this is a tractable problem with clever use of regex, but I'm going to punt on it for now.
=> fix: Better inputRules for inline math (and one for code)

client/components/SimpleEditor/SimpleEditor.tsx
Quick fix for math in captions.
**Test Plan**
- Add math to a caption. It should render correctly in the editor.
=> fix: math in captions

client/containers/User/User.tsx
See [here](https://github.com/pubpub/pubpub/pull/2223)
=> bug: Fix author pub count

client/containers/Pub/PubHeader/Review/ReviewerDialog.tsx, client/containers/Pub/PubHeader/ReviewHeaderSticky.tsx
this fixes an issue where logged-out users would not be redirected anywhere
=> enahncement: Redirect Logged-Out Users

package-lock.json, workers/tasks/export/pandoc.ts
this addresses issue #2197 
handles warning for pandoc conversion that would otherwise prevent a user from downloading said document
=> bug: Handle Warnings from Pandoc

server/routes/collection.tsx
See https://github.com/pubpub/pubpub/discussions/2124#discussioncomment-3704285
=> fix: pass collection to collection page metadataComponent

client/containers/Pub/usePubBodyState.ts
adresses #2359 
set plugin to true, allow anchors to render on draft
=> Render Anchors 

tools/encrypt.js, tools/exportCollection.js, tools/index.js
- Adds recursion to makes the exportCollection function actually work!
- Adds the encrypt function to tools so it can be run with npm run tools, makes the variable entry more explicit
=> dev: cleanup some tools

client/components/Layout/LayoutBanner.tsx
addresses #2250 
now a redirect link is made
=> bug: Login to create pub 

server/rss/__tests__/api.test.ts, server/rss/api.ts
Fixes #2432 
- Handles the missing community id in the initial data when on base pubpub
=> Return 404 for base pubpub /rss.xml

utils/customScripts.ts
Adds custom JS for eLife's container community.
=> Add custom JS for eLife

client/components/Editor/plugins/inputRules.ts
Fixes #2476 
Type links and email addresses followed by a space character and watch them automatically link-ify!
=> fix: link input rule

server/Html.tsx
Resolves dynos crashing with this error:
=> fix: hotfix for 'cannot use in operator to search for slug in null

client/components/Deposit/Deposit.tsx, client/components/Deposit/UpdateDoi.tsx, deposit/datacite/deposit.ts, deposit/datacite/index.tsx, deposit/transform/collection.ts, deposit/transform/pub.ts, types/pub.ts
Some quick fixes before Datacite playtesting.
=> Datacite fixes

client/components/Deposit/DataciteDeposit.tsx, client/components/Deposit/DataciteDepositPreview.tsx, client/components/Deposit/Deposit.tsx, client/components/Deposit/ReviewDepositCallout.tsx, client/components/Deposit/dataciteDeposit.scss, deposit/datacite/deposit.ts, deposit/datacite/index.tsx, deposit/transform/collection.ts, deposit/transform/pub.ts, deposit/utils.ts, server/pub/api.ts, utils/canonicalUrls.js, utils/crossref/createDeposit.js
Resolves #2587 
Go through our [playtest document](https://notes.knowledgefutures.org/pub/yo89la54/draft), and confirm your feedback has been addressed in this PR's review app.
=> fix: remaining datacite fixes

client/components/Deposit/Deposit.tsx, deposit/transform/pub.ts, server/collection/api.ts, server/pub/api.ts, server/utils/queryHelpers/pubOptions.ts
N/A
Using the `eric` community...
1. Verify that you can set a DOI for a Pub prior to initial release.
2. Verify that custom DOI suffixes actually show up in Fabrica.
3. Verify that the _Publisher_ community setting is used as the value for `publisher` in a deposit.
=> More DataCite fixes

client/components/FormattingBar/controlComponents/ControlsLink.tsx, client/containers/DashboardEdges/useDashboardEdges.ts, client/containers/Pub/PubContextProvider.tsx
Dashboard Crashes on DB err
Visit any page a link can be created. Attempt to make a link. 
Be sure you can still open in a new tab 
Visit a pub and be sure the that connections can still be made there
=> Enhanced links fix

client/components/FormattingBar/controlComponents/ControlsLink.tsx, client/containers/DashboardEdges/NewEdgeEditor.tsx, server/pubEdgeProposal/queries.ts, utils/pubEdge/helpers.ts
Resolves #2646
Create a connection with an external (non-PubPub) URL.
=> fix: connection creation to external URL

client/components/FormattingBar/buttons.ts, client/containers/Pub/PubDocument/PubHeaderFormatting.tsx
#2572 
View a pub community with suggested edits on. Make sure you can use the buttons and 
@djagdish feel free to comment if we should arrange it differently
=> move SE buttons to right

deposit/datacite/deposit.ts, deposit/datacite/index.tsx
Resolves #2627 
1. Manually create a DOI in DataCite Fabrica.
1. Create a Pub in the `eric` DuqDuq community.
1. Give it the same DOI used in step 1.
1. Submit the deposit to DataCite. You should see "DOI Deposited" and no error messages.
=> fix: use datacite api to determine if doi exists before depositing

server/user/__tests__/api.test.ts, server/user/api.ts, server/user/permissions.ts, server/user/queries.ts
Part #2591 
run the test in user/__test__
be sure all pass
this will be an api call made on the client when getting user info for a suggested edit
https://notes.knowledgefutures.org/pub/cthxjiio#who-made-the-suggestion-and-when
=> API method for getting user

client/layouts/CollapsibleHeader/CollapsibleHeader.tsx
Primary and Secondary navigation will be detected by screen readers automatically.
=> dev: remove role for navigation

client/layouts/TwoColumnFooter/TwoColumnFooter.tsx, client/layouts/TwoColumnFooter/twoColumnFooter.scss
=> dev: remove classes that are not needed

.jest/setup-env.js, server/customScript/__tests__/api.test.ts
=> test: fix scripts tests

client/layouts/TwoColumnFooter/TwoColumnFooter.tsx
=> add footer tag so code is semantic

client/components/Editor/styles/suggestedEdits.scss
#2685 
1. Open a draft and create an HR.
2. Enter suggestion mode. Delete the HR. You should see a 32px-tall red line to its left.
3. Create an HR. You should see a green line to its left.
=> feat: hr suggestion styling

server/login/api.ts, server/models.ts
Per some guidance, adding these should make connection timeouts less likely.
=> hotfix: add min, idle and acquire times to connection pool

server/utils/citations/structuredCitations.ts
Resolves #2729
1. Open a Pub with many (100+) structured citations.
2. The citations should load properly (i.e. not display as "Error")
=> fix: batch Cite.async calls to avoid timeouts in Pubs with many structured citations

client/components/Editor/plugins/suggestedEdits/resolve.ts, client/components/FormattingBar/FormattingBarSuggestedEdits.tsx, client/components/FormattingBar/buttons.ts, client/components/FormattingBar/formattingBarSuggestedEdits.scss, client/containers/Pub/PubDocument/PubInlineSuggestedEdits.tsx, server/user/__tests__/api.test.ts, server/user/api.ts, server/user/queries.ts, types/user.ts
#2591 
go to a pub
add suggested edits
be sure your avatar comes up
find another pub with suggested edits from not you [here](http://localhost:9876/pub/35ifjc2m/draft)
=> Inline suggestion info

client/components/Editor/plugins/suggestedEdits/resolve.ts, client/components/FormattingBar/FormattingBarSuggestedEdits.tsx, client/components/FormattingBar/buttons.ts, client/components/FormattingBar/formattingBarSuggestedEdits.scss, client/components/FormattingBar/index.ts, client/components/PubReleaseDialog/PubReleaseDialog.tsx, client/containers/Pub/PubDocument/PubDocument.tsx, client/containers/Pub/PubDocument/PubInlineMenu.tsx, client/containers/Pub/PubDocument/PubInlineSuggestedEdits.tsx, client/containers/Pub/PubDocument/pubInlineSuggestionMenu.scss, server/user/__tests__/api.test.ts, server/user/api.ts, server/user/queries.ts, types/user.ts
#2590  
Once again, i'm asking you to dona.. I mean make a pub
Copy some text in. 
Make edits to the text
Try accepting or rejecting the suggestions from the new inline menu
Try selecting a range in the doc with no suggestion edits
=> Inline suggestion buttons

server/routes/redirects.ts
Creates two new redirects as requested.
=> dev: add redirects for two arcadia pages

client/layouts/CollapsibleHeader/CollapsibleHeader.tsx
=> Move search and alert icon to right side of link text

client/layouts/TwoColumnFooter/TwoColumnFooter.tsx, client/layouts/TwoColumnFooter/twoColumnFooter.scss, client/layouts/TwoColumnFooter/twoColumnFooterData.ts
=> Investor logo fixes

client/layouts/TwoColumnFooter/twoColumnFooter.scss
=> refactor investor logos so 520 breakpoint works properly

client/layouts/TwoColumnFooter/twoColumnFooterData.ts
Quick fix to an incorrect link in the footer on eLife
=> Fix relative URL for "who we work with" to make it absolute

client/components/Editor/schemas/iframe.ts
=> fix: hide iframe labels

server/collectionPub/api.ts, server/collectionPub/queries.ts, server/routes/dashboardCollectionOverview.tsx, server/user/api.ts, server/userNotification/api.ts, server/utils/queryHelpers/scopeGet.ts
Fixes the following:
1. https://kfg.sentry.io/issues/4271437596/?project=1505439&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
2. https://kfg.sentry.io/issues/4399002620/?project=1505439
3. https://kfg.sentry.io/issues/4277556266/?project=1505439&query=is%3Aunresolved&referrer=issue-stream&stream_index=1
1. Send a get request to `/api/userNotifications`. If you get a 404 back alls good
2. Go to random `/dash/collection/asihotnea` route and see if you still get the Application Error
3. 1. Send a get request to `/api/collectionPubs`. If you get a 404 back alls good
#2808
=> fix: a number server crashes 

.jest/setup-env.js, server/routes/pubDocument.tsx, server/routes/user.tsx, server/server.ts, server/userScopeVisit/queries.ts, server/utils/queryHelpers/communityOverview.ts, server/utils/search.ts, server/utils/workers.ts, server/workerTask/api.ts, server/workerTask/queries.ts, utils/api/contracts/workerTask.ts, utils/caching/__tests__/purge.test.ts, utils/caching/caching_strategy.md, utils/caching/getCorrectHostname.ts, utils/caching/purgeMiddleware.ts, utils/caching/purgeSurrogateTag.ts, utils/caching/schedulePurge.ts, workers/queue.ts, workers/tasks/export/export.ts, workers/tasks/export/metadata.ts, workers/tasks/export/types.ts
=> feat: add purgeMiddleware for purging cache on CRUD operations 

server/routes/pubDocument.tsx, utils/caching/__tests__/purge.test.ts, utils/pubEdge/helpers.ts
=> fix: fix setting Surrogate-Key headers for pub edges on releases, and undefined.pubpub.org

client/utils/hydrateWrapper.tsx, client/utils/initialData.ts, server/Html.tsx
This reverts commit 434acebd877bed100e44c810515e3732b01b49e2.
=> HOTFIX: Serialization

server/logout/api.ts, utils/caching/__tests__/purge.test.ts, utils/caching/purgeMiddleware.ts, utils/caching/purgeSurrogateTag.ts, utils/caching/schedulePurge.ts
- feat: purge session cache on logout
- fix: add test
=> Purge Surrogate Tags on logout based on session

client/containers/App/App.tsx, client/layouts/CollapsibleHeaderBPC/CollapsibleHeader.stories.tsx, client/layouts/CollapsibleHeaderBPC/CollapsibleHeader.tsx, client/layouts/CollapsibleHeaderBPC/collapsibleHeader.scss, client/layouts/CollapsibleHeaderBPC/collapsibleHeaderData.ts, client/layouts/CollapsibleHeaderBPC/index.ts, client/layouts/index.ts
As described. To test, visit `biophysicscolab` community on a dev environment.
=> Adds biophysics colab layout

README.md
=> docs: fix the incorrect apidocs link

tools/migrations/2024_06_12_replaceLinkedinHandles.js
Fixes ESLint failing on CI, should have been a part of #3111 !
Reminder: migration should be run when this is pushed to prod.
=> fix: fix small eslint issue

client/layouts/TwoColumnFooter/twoColumnFooterData.ts
Not to be merged until at least 24th June 2024
=> eLife change of address

client/components/UserAutocomplete/UserAutocomplete.tsx
- Debounces the user search query so that our server isn't spammed when people perform lots of long searches.
- Does not send user query when the query value is blank
- Visit a Pub
- With the network console open, attempt to add a user by searching
- See that the `/api/user/search?q=text` query is sent only once every 300ms at maximum (this felt like the right number between ~200 and ~500).
- Delete the text, wait 300ms, and make sure no empty query (`api/user/search?q=`) is sent.
- Search by a pasted email that has a user account and make sure the user is returned after ~300ms
- Make sure you can still add a returned user to the pub
- Make sure you can add a non-existing "shadow" user to the pub
- Repeat in pub settings
- Repeat for collections in the dashboard
=> Dev: Debounce user query and prevent empty queries

client/utils/legal/tosUpdate.ts
Removes the TOS banner. It's been long enough.
n/a
Visit any page in an incognito window. Make sure no TOS banner displays.
=> dev: Remove TOS banner

server/routes/redirects.ts
Redirects some URLs for JEED and COPIM
=> dev: Redirect some URLs

Aptfile, app.json
Triggering a review app deployment as recommended in the [Heroku docs](https://devcenter.heroku.com/articles/heroku-24-stack#upgrading-to-heroku-24)
=> chore: upgrade heroku stack

server/community/api.ts
=> drop daily archive count to 2

client/containers/DashboardSettings/CommunitySettings/CommunityAdminSettings.tsx
N/A
Take a quick look at the changes to the instructions!
=> fix: couple of grammatical errors

workers/tasks/archive.tsx, workers/tasks/archive/siteDownloaderTransform.ts, workers/tasks/export/metadata.ts, workers/tasks/export/notes.ts
- **feat: also download html**
- **feat: include draft html/abstract, rather than latest release one, and make constructing html more efficient. dont include release prosemirror trees**
- **fix: reduce batchsize to 200**
=> fix: some adjustments to json export
