src/components/AtomTypes/Video/VideoEditor.jsx, src/components/AtomTypes/Video/VideoEditor.test.js, src/components/AtomTypes/Video/VideoViewer.jsx, src/components/AtomTypes/Video/VideoViewer.test.js, src/components/AtomTypes/index.js, src/containers/AtomEditor/AtomEditorPane.jsx, src/containers/AtomReader/AtomViewerPane.jsx, src/containers/Landing/Landing.jsx
yay look videos
This is currently only using the default HTML5 video player, which only handles MP4, OGG, and webm filetypes. We probably eventually want a more rich, inclusive video player, but those are a pain because they're big and styling them is a pain. I'll update this branch with a better one once I get code splitting working on atom viewer types, which doesn't happen yet.
=> added video editor

package.json, src/components/AtomTypes/IFrame/IFrameEditor.jsx, src/components/AtomTypes/IFrame/IFrameViewer.jsx, src/components/AtomTypes/LaTeX/LaTeXEditor.jsx, src/components/AtomTypes/LaTeX/LaTeXEditor.test.js, src/components/AtomTypes/LaTeX/LaTeXViewer.jsx, src/components/AtomTypes/LaTeX/LaTeXViewer.test.js, src/components/AtomTypes/index.js, src/containers/Landing/Landing.jsx, src/server.js
- LaTeX atom using KHan Academy's KaTeX package. It's fast and light and outputs pure HTML. Downside is that there's an extra stylesheet link in server.js now.
- Added width and height props to IFrame, and cleaned up the code a bit
- Updated package.json with happypack (for dev rebuilds) and katex (for the LaTeX atom)
=> Added LaTeX atom and updated IFrame atom

README.md
The pubpub-api link uses github.org rather than github.com.
=> fix URL to pubpub-api repo

client/components/PubDraftHeader/PubDraftHeader.js, client/components/PubHeader/PubHeader.js, searchSync/init.js, stories/components/footerStories.js, stories/components/headerStories.js, stories/components/pubDraftHeaderStories.js, stories/data.js
This PR fixes various React Storybook entries that were previously failing due mostly to missing props. I've added the props where appropriate and I'm looking into a way to automatically test that all fixtures mount and render, either as a pre-push hook or a CI step, to make sure this doesn't happen again.
_Test plan:_
Run `npm run storybook` and visit `localhost:9001`. Check that every story renders as expected.
=> fix: update all broken Storybook entries

workers/exportTask.js
We don't meaningfully support embedding discussions in exports, so this PR disables that for the time being.
_Test plan:_
`npm run workers-dev` and export a pub with a discussions embed as a PDF. Verify that the discussion is stripped out.
=> update: Strip discussions from export

server/apiRoutes/discussions.js
We now validate the `userId` passed in though an `/api/discussions` request before posting a comment.
_Test plan:_
- Verify that adding discussions still works.
- As a logged-out visitor to a pub, try spoofing a `userId` of another user and verify that you get a 500 error.
=> fix: Improve handling of userId in discussions code

client/components/PubBody/PubBody.js, client/components/PubDraftHeader/PubDraftHeader.js, client/components/PubEditorUserInputCapture/PubEditorUserInputCapture.js, client/containers/Pub/Pub.js, package-lock.json, package.json
The use of an `Editor` component as an uncontrolled text editor presents problems for a React-based UI, since only its initial contents are controlled by a prop. When the same editor needs to be shown consecutively for two different pieces of information — in this case, the captions of two images in a Pub — React does not naively destroy the first instance and create a new one to pass initial contents into as we'd hope. I've done this by adding a `key` prop for the image based on its document position. During collaborative editing, this could cause issues when other users are changing the document position of an image as someone is trying to update its caption, but short of a new system of stable identifiers for pub entities, I think this is the best I can do for now.
_Test plan:_
Create …
=> fix: FormattingBar image caption field updates when image selection is changed

client/components/LayoutEditorPubs/LayoutEditorPubs.js
This PR fixes an issue where the remove/"x" button on tags was not being correctly positioned due to what looks like an extraneous `.bp3-` Blueprint CSS class that was being applied to one of its parents. AFAIK the parent element with that class is safe to remove entirely, and I think the general takeaway is that we should leave the use of Blueprint CSS classes to the Blueprint React API wherever possible.
_Before:_
_After:_
_Test plan:_
Find a place where we use a `TagMultiSelect` component — the "Filter by tags" entry in the layout editor at `/dashboard/pages/` is as good as any — and verify that added tags have their close button positioned correctly.
=> fix: Correctly position remove button on tags

client/components/AttributionEditor/AttributionRow.js, client/components/AttributionEditor/attributionEditor.scss, package-lock.json, package.json, server/apiRoutes/handlers/attributions.js, server/migrations.js, server/models/collectionAttribution.js, server/models/pubAttribution.js, shared/crossref/__tests__/__snapshots__/createDeposit.test.js.snap, shared/crossref/__tests__/createDeposit.test.js, shared/crossref/__tests__/data/attributions.js, shared/crossref/__tests__/data/pub.js, shared/crossref/schema/contributors.js, stories/containers/Pub/PubManage/attributionStories.js
This pull request adds the `affiliation` field to the `PubAttribution` and `CollectionAttribution` models, allowing us to set an affiliation for contributors to pubs and collections, and submit that information to Crossref. To users, we expose a field like this:
Right now it's just a freeform string — so you could affiliate yourself with the Chattanooga School of Clowning Arts if you want. Eventually we'll want to start collecting affiliations at the `User` level, linking to ORCID, etc. — but it's a start.
_Test plan:_
After running `npm migrate && npm start` I observed the following:
- Both the collection and pub-level attribution editors let you see and update affiliation for each author
- Submitting DOI information for both a collection and a pub causes the affiliation to appear for …
=> feature: Attribution "affiliation" field

client/containers/Pub/Pub.js, client/containers/Pub/PubDocument/PubBody.js, client/containers/Pub/PubDocument/PubHeaderCollaborators.js, client/containers/Pub/PubDocument/PubHeaderFormatting.js, client/containers/Pub/PubSyncManager.js, client/utils/firebaseClient.js
As in v5 we would like to show the avatars of other collaborators currently editing the same pub branch. Most of the code is in place to do this is already left over from v5 — I've just had to make some tweaks to make it understand branches, and do a bit of cleanup along the way. Here it is in action:
_Test plan:_
Log in as two different PubPub users and open the same pub. Then verify that:
- Users do not see themselves among the collaborators
- Collaborator avatars appear in the draft editing bar as expected
- Cursor colors in the editor match the color rings around the avatars
- Custom profile images are shown for users that have them
- Closing a user's editor causes their bubble to disappear
=> update: Restore collab avatars in v6

.eslintrc, client/containers/Pub/PubMeta/Download.js, client/containers/Pub/PubMeta/PubMeta.js, client/containers/Pub/PubMeta/download.scss, client/utils/pingTask.js, server/apiRoutes/export.js, stories/containers/Pub/PubMeta/downloadStories.js, workers/tasks/export.js, workers/tasks/import.js, workers/tasks/search.js, workers/worker.js
This PR does contains an end-to-end update that makes pub download/export work in v6. It also contains styling updates to the Download pane in PubMeta. Here it is:
There are some more changes that I want to make in this area so that exported downloads always cache correctly — see #378.
_Test plan:_
- `npm run storybook` and look at [the Storybook fixtures](http://localhost:9001/?path=/story/containers-pub-pubmeta-download--default).
- Visit a pub that you manage and make sure you can update its custom download
- Make sure that exporting a pub works and that the resulting documents contain the expected content.
=> update: Port pub export to v6

server/routes/pub.js, server/utils/index.js
Addresses #385.
If the pub is not in a primary collection or the pub's primary collection is of kind 'issue', the page title becomes: `{pubTitle} • {communityTitle}`
Otherwise, the pub is in a primary collection that is a book or conference, in which case the page title becomes: `{pubTitle} • {primaryCollection.title}`
Additionally, it appears that page metadata (title, og, twitter card, etc.) had regressed in V6. This attempts to restore this metadata, and makes modifications such that citation titles do not include community or collection titles.
One open question to resolve: what to do with unlisted in generateMetaComponents in the new pub model (server/routes/pub.js#99).
=> Pub page metadata and titles

client/components/Footer/Footer.js, client/components/Footer/footer.scss, client/containers/UserCreate/UserCreate.js, client/containers/UserCreate/userCreate.scss
This PR implements:
Adds an opt-in checkbox for GDPR compliance and a popover with third-party data notice.
- Scroll to footer.
- Hover over new compliance language, make sure the third-party notice popover appears
- Click on privacy link in popover
- Submit email without checking confirmation box
- Check confirmation box, then submit email
=> update: GDPR opt-in and third-party notices

client/containers/Pub/PubDocument/PubBody.js, client/containers/Pub/PubDocument/pubBody.scss, client/utils/hydrateWrapper.js, package-lock.json, package.json, server/server.js
This PR responds to #456. The bulk of functionality updates are in [pubpub-editor](https://github.com/pubpub/pubpub-editor/commit/68468e91876bb5b408bc172305c97f5edc6fc67a). Both local Prosemirror errors and asynchronous Firebase errors are caught, and passed to a new `onError()` param on the `<Editor />` component. 
This onError function is used in `<PubBody />` to trigger an alert that blocks further typing and forces a page reload.
When `onError()` is triggered, we also fire a Sentry event and add a `{ error_source: 'editor'}` tag which will allow filtering from the Sentry end.
Feedback/commits on the language of the error is especially welcome.
=> update: Add warning message when the Editor throws errors

server/branch/__tests__/api.test.js, server/branch/__tests__/permissions.test.js, server/branch/api.js, server/branch/queries.js, server/branchPermission/__tests__/api.test.js, server/branchPermission/api.js, server/branchPermission/permissions.js, server/branchPermission/queries.js
This PR adds tests for `branch` and `branchPermission` code, and shores up some of the code that we're testing as well. It also updates the branch-related API routes to use semantically-meaningful HTTP error codes.
_Test plan:_
`npm run test server/branch`
=> dev/fix: Tests and some small fixes for branch-related code

server/collection/__tests__/api.test.js, server/collection/api.js, server/collectionAttribution/__tests__/api.test.js, server/collectionAttribution/api.js, server/collectionPub/__tests__/api.test.js, server/collectionPub/api.js, server/collectionPub/queries.js
This PR adds tests to collections-related code on the server, and also adds some small fixes to CollectionPub logic. It also refactors the collections-related API routes so that they return semantically meaningful error codes.
_Test plan:_
`npm run test server/collection`
=> dev/fix: Tests and a tiny fix for collections-related code

server/community/__tests__/api.test.js, server/community/api.js, server/communityAdmin/__tests__/api.test.js, server/communityAdmin/api.js
This PR adds tests to community-related code on the server. It also refactors the community-related API routes so that they return semantically meaningful error codes.
_Test plan:_
`npm run test server/community`
=> dev: Tests for community-related code

client/containers/Pub/PubDocument/PubDiscussions/DiscussionThread/DiscussionInput.js, client/containers/Pub/PubDocument/PubDiscussions/DiscussionThread/DiscussionItem.js, server/discussion/__tests__/api.test.js, server/discussion/__tests__/permissions.test.js, server/discussion/api.js, server/discussion/permissions.js, server/discussion/queries.js
This PR adds tests for discussions-related code. It also makes some fairly significant changes to the way discussion permissions are handled, so they now respect branch permissions. This is adequately covered by the new tests, but I'll do some manual testing before merging this as well.
_Test plan:_
- `npm run test server/discussion`
- Also manually poke around a pub and make sure you can still add discussions as a user with `discuss` branch permissions
=> dev/update: Tests and updates to discussions-related code

client/containers/Pub/PubDocument/PubInlineMenu.js
On mobile, both Chrome and Safari have a context menu that appears around selected text...right where we put our `PubInlineMenu`. In these contexts (specifically, on devices with `iPad`, `iPhone`, or `Android` in the user-agent string) we'll move the menu to the bottom of the selection where it remains accessible.
_Test plan:_
- Patch the devserver so it accepts connections on the local network from other devices. I changed `if (req.hostname.indexOf('localhost') > -1)` in `server.js` to `if (true)`.
- Fire up a pub on your mobile device and verify the `PubInlineMenu` does not overlap your mobile browser's inline context menu when text is selected in a Pub.
- Open the same Pub in a desktop browser and verify that the menu positioning is the same as before.
_Screenshots:_
Desktop (same as …
=> fix: Position PubInlineMenu away from mobile browsers' built-in inline controls

client/containers/Pub/PubDocument/PubDiscussions/DiscussionThread/DiscussionInput.js, client/containers/Pub/PubDocument/PubDiscussions/DiscussionThread/DiscussionItem.js, client/containers/Pub/PubDocument/PubDiscussions/DiscussionThread/discussionItem.scss, client/containers/Pub/PubDocument/PubDiscussions/DiscussionThread/discussionThread.scss, client/containers/Pub/PubDocument/PubDiscussions/PubDiscussions.js, client/containers/Pub/PubDocument/PubDiscussions/pubDiscussions.scss
While there's no technical reason we can't have discussions at the bottom of the Pub unassociated with any highlight, we haven't had this capability at least since v6 launched. This PR adds a comment box at the bottom of the pub to enable this.
_Test plan:_
- Load a pub and make sure you can add (multiple) comments using the bottom discussion box
- Make sure the box does not appear when you don't have discuss permissions.
=> feature: Enable unanchored discussions in V6

server/routes/__tests__/collection.test.js, server/routes/collection.js, stubstub/modelHelpers.js
This PR updates the behavior of the `/collection/:id` route (notable for being referenced in DOI deposits) so that it resolves to the Page associated with a Collection, where one exists.
_Test plan:_
- Create a collection and copy its URL (from the Metadata tab of the collection editor) into the search bar. Verify that it redirects to a `/search` URL.
- Now link your collection to a Page (from the Details tab of same). Verify that the same collection URL now redirects to the Page.
- `npm test server/routes`
=> update: Make /collection/:id requests redirect to collection page, where applicable

client/components/PubNoteContent/PubNoteContent.js, client/components/PubNoteContent/pubNoteContent.scss, client/containers/Pub/PubDocument/PubBottom/Discussions/FilterMenu.js, client/containers/Pub/PubDocument/PubBottom/Footnotes.js, client/containers/Pub/PubDocument/PubBottom/PubBottom.js, client/containers/Pub/PubDocument/PubBottom/PubBottomSection.js, client/containers/Pub/PubDocument/PubMouseEvents/PubMouseEvents.js, stories/containers/Pub/PubBottom/footnotesStories.js, stories/containers/Pub/PubBottom/pubBottomStories.js
This PR connects the new `pubData.citations` and `pubData.footnotes` fields from our NodeView refactor to the new PubBottom UI, so that citations and footnotes in the document will be reflected live in the footer.
_Test plan:_
-  Visit a Pub with some footnotes and citations ([like this one](http://localhost:9876/pub/xiyvipgb))
- Test that the footnotes and citations in the document are visible in the footer
- Test that editing the document updates these footnotes and citations
- Test that clicking the "return" link on a footnote/citation takes you back to its position in the Pub.
=> feature: Wire new citations/footnotes fields into new pub footer (3/x)

client/containers/Pub/Pub.js, client/containers/Pub/PubSyncManager.js, server/routes/pub.js, shared/utils/pubPageTitle.js
Does what it say on the tin — makes the page title change when we edit the Pub title in real time.
_Test plan:_
Open a pub, edit the title by clicking on it in the header, make sure the page title changes.
=> fix: Update page title when Pub title changes

client/components/SimpleNotesList/SimpleNotesList.js, client/components/index.js, workers/tasks/export.js
Since we no longer render citation or footnote lists in our Prosemirror docs, we'll now append these to the bottom of the export that we send to Pandoc.
_Test plan:_
- Create a pub with some footnotes and citations. Test that you can export it to several formats, and that the exports contain footnotes and citations.
- Test that exporting pubs without footnotes/citations still works.
_Example output:_
=> feature: Add footnotes/citations to export

client/containers/Pub/PubDocument/PubDiscussions/DiscussionThread/DiscussionInput.js, server/routes/__tests__/pub.test.js, server/utils/formatPub.js, server/utils/pubQueries.js
This PR fixes a bug that was introduced when implementing the branch-redirect logic. This addresses #538.
The issue was that non-document views (e.g. /manage or /review) were triggering a redirect if a public branch was not visible (or was empty), as the "default branch" would resolve to null given that there was no public branch, and no specific sub-branch specified in the URL.
=> fix: Non-document pub views cause redirect when no public branch exists

package-lock.json, package.json, workers/tasks/export.js
Oops, forgot to put this up yesterday. This PR adds passes the `author` and `date` metadata values into Pandoc, showing them in our Pub exports. Where applicable we also include "Updated at" and "DOI" fields at the top of the export.
_Test plan:_
- Check that an exported pub contains a date and a correctly-sorted list of contributors under the title.
- Try exporting a pub with (and without) a DOI and check that it appears (or doesn't) as expected in the result
- Test that the "Updated at" field appears iff the pub has been updated, and the updated date is not the same as the published date
_Screenshot:_
=> feature: Add metadata to Pub exports

client/components/Header/Header.js, client/components/Menu/Menu.js, client/components/Menu/MenuButton.js, client/components/Menu/MenuItem.js, client/components/Menu/index.js, client/components/Menu/menu.scss, client/components/Menu/menuContext.js, client/components/NavBar/NavBar.js, client/containers/Pub/PubSuspendWhileTyping.js, package-lock.json, package.json, stories/components/menuStories.js
While Blueprint serves us well as a UI framework, it's unfortunately not very good for keyboard and screenreader users, especially in places where complex interactions and portals are involved. In particular, dropdown menus are practically unusable with a keyboard. [This appears to be a known issue](https://github.com/palantir/blueprint/issues/3079) with a `help wanted` tag, but given the amount of work that goes into correctly implementing accessible UI elements _and_ merging that code into a complicated foreign codebase, I decided against trying to submit a PR to Blueprint to fix this.
Instead, I've used a very promising new UI framework called [Reakit](https://reakit.io/) to build a new menu component, which can be navigated using the keyboard and provides useful screenreader …
=> feature: New accessible menu component

client/components/PageWrapper/PageWrapper.js, client/components/SkipLink/SkipLink.js, client/components/SkipLink/skipLink.scss, client/components/TabToShow/TabToShow.js, client/components/TabToShow/tab-to-show.scss, client/components/index.js, client/containers/Dashboard/Dashboard.js
A skip link is an `<a>` element that allows keyboard users to jump past generic navigation elements such as headers and navbars to get to the page's main content. The link is invisible unless it is tabbed to, at which point we make it visible and it is announced to screenreaders. This PR adds a global skip link that bypasses the global and page navigation, and as a proof of concept I've added one that skips past the dashboard sidebar into the dashboard content as well. We could use these everywhere, potentially even in the soon-to-be redesigned Pub header.
_Screenshot:_
_Test plan:_
Visit any Page and tab to focus the page content. The "skip to main content" link should be visible and when activated should skip the user past the header and into the Page content. Likewise, it should skip …
=> feature: Skip links

client/components/DragDropListing/DragDropListing.js, client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/CollectionEditor.js, client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/CollectionEditorView.js, client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/PubListingControls.js, client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/PubRow.js, client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/PubSelectionControls.js, client/containers/Dashboard/DashboardContent/Collection/CollectionEditor/collectionEditor.scss, client/containers/Dashboard/DashboardContent/Collections/CollectionTile.js, client/containers/Dashboard/DashboardContent/Collections/NewCollectionCard.js, client/containers/Dashboard/DashboardContent/Collections/collections.scss
This PR contains a few improvements to the collection editor:
- The buttons at the top of `/dashboard/collections` are now actually buttons that can be accessed with the keyboard
- The collection editor itself has better screenreader announcements and new buttons that make it a little easier to add a Pub to a collection without dragging it.
- While the drag-and-drop interface for the collection editor does have keyboard/screenreader support thanks to `react-beautiful-dnd`, I've made that more transparent by adding a "keyboard shortcuts" pane that it shown to keyboard and screenreader users who are accessing the page, as well as some new keyboard shortcuts that should make jumping around this complicated piece of UI somewhat easier. The pane appears automatically for keyboard users, using …
=> update: a11y-focused improvements to Collections editor

package.json
Adding this to a PR so we can have a standalone conversation about it.
Node.js version 12 [just entered its long-term support period](https://nodejs.org/en/about/releases/). Coincidentally, I'm working on some stuff over in #590 which requires us to upgrade to a newer version of `10.x` or `12.x` (which are on parallel LTS tracks). I see no reason not to try for `12.x`.
_Test plan:_
- Run `npm test`
- Check some routes to make sure the site generally works with Node 12.
- After this is approved I'll push it to duqduq and we can observe it in situ on Heroku for a bit before pushing it to production.
=> dev: Update to Node 12.13.0

client/containers/Pub/PubHeader/Download.js, package.json, server/models.js, workers/environment.js, workers/initWorker.js, workers/queue.js, workers/tasks/export.js, workers/tasks/import-export/import.js, workers/worker.js
We've been having issues where heavy Pub imports/exports have clogged up the job queue, preventing others from running imports or exports. The problem is twofold:
- There is no way for jobs that could potentially take forever to be killed after a timeout
- There is no way for one Heroku dyno to run `n > 1` jobs at once, though I suspect there are gains to be squeezed from parallelism here, at least for low `n`.
This PR addresses these issues by restructuring the worker dyno code so it spawns one thread per job using the relatively new `worker_threads` Node module. This lets us kill jobs if they take too long, as well as kick off multiple jobs at once. One caveat is that large numbers of parallel jobs can create more database connections than our Postgres instance allows, leading to …
=> update: More resilient worker queue

server/community/queries.js, server/communityAdmin/queries.js, server/subscribe/queries.js, server/user/queries.js, server/utils/mailchimp.js
Switches to our new mailchimp account.
_Test plan_
1. Replace mailchimp api key in config.js with new key
1. Signup for the newsletter in the footer
1. Signup for the newsletter as part of user login – your new mailchimp user should be given the `users` in mailchimp
1. Add your user as a community admin – your user should be tagged as a `community admin` in mailchimp
1. Create a new community (is this possible on dev?) - your user should be tagged as a `community admin` in mailchimp
Deploying will require updating mailchimp env variable in heroku.
=> Mailchimp account update

client/containers/Pricing/Pricing.js, client/containers/Pricing/pricing.scss
Updates the pricing page to reflect our latest model ideas. Also updates the email address to partnerships@ (partners@ also works), which goes to select team members as well as automatically to freshdesk to record a lead.
_Test plan_
- Read it and see what you think?
- Make sure the email links work and that sending emails to partnerships@ work
=> update: pricing page

client/containers/Pub/PubDocument/PubBottom/ReadNextSection.js, client/containers/Pub/PubHeader/Download.js, client/containers/Pub/PubHeader/download.scss, client/containers/Pub/PubSyncManager.js, client/containers/Pub/pubHooks.js, client/containers/Pub/usePageContext.js, package-lock.json, server/branch/model.js, server/branch/permissions.js, server/export/__tests__/api.test.js, server/export/api.js, server/export/model.js, server/export/permissions.js, server/export/queries.js, server/merge/queries.js, server/migrations.js, server/models.js, server/utils/pubQueries.js, shared/export/formats.js, stubstub/global/setup.js, stubstub/index.js, stubstub/modelHelpers.js, stubstub/stub.js, workers/tasks/export/export.js, workers/tasks/export/prosemirror.js, workers/tasks/export/util.js
This PR adds an `Exports` table to our database schema, which keeps a record of all exports that are created, keyed on `(branchId, historyKey, format)`. From now on we will check this table for an existing export URL before spinning up a worker task to create one. I also added code to trigger creating all exports when a branch merge is completed — hopefully this means most visitors will not have to wait at all for an export to complete.
In passing, I updated the Download menu so that this fixes #553.
There is more work to be done here on keying exports against the _version_ of the exporter, in case of major improvements. That's out of scope for this PR and for the time being can be accomplished with manual manipulation of the `Exports` table.
_Test plan:_
- Run `npm test server/export`
- …
=> feature: Cache exports and automatically create them on merge

workers/tasks/export/html.js, workers/tasks/export/styles/printDocument.scss
Makes a few initial tweaks to pagedjs to fix a few small bugs that are prevalent in top HDSR articles.
- Default content for iframes
- Break-avoid for figures, images, and image captions
- Max-height on figures of 800px.
- Smaller font size and break-avoid for math to avoid math breaking onto multiple pages
_Test plan_
- Manually delete export for Glickman (1.1)
- Export PDF
- Verify that:
- Images and figures/captions do not break onto multiple pages
- iFrames appear small, grey, and with default text
- Math appears in smaller font and does not break onto multiple pages
- Manually delete export for Gibbons (1.2)
- Export PDF
- Verify that:
- Large supplement table images 2 and 5 at the bottom are resized properly
- Images and figures/captions do not break onto multiple pages
- Manually …
=> Paged tweaks

workers/tasks/export/styles/editorBase.scss, workers/tasks/export/styles/printDocument.scss
This temporarily switches to using a static pubpub-editor css file to avoid the pagedjs media query bug described here: https://gitlab.pagedmedia.org/tools/pagedjs-cli/issues/11
_Test plan_
1. Generate the PDF for a pub that uses sized images, ie: https://kfg.duqduq.org/pub/v7wsbips/
1. Repeat for float left, right, center and full
1. Repeat for videos
=> fix: Remove media query effective PDF images

server/routes/user.js, server/utils/index.js
At the moment, search engines will index a user's profile on different communities as separate results. This leads to folks having 4 or 5 PubPub community profile pages in search engine results when entering their name. 
This PR proposes that we add a `<link rel="canonical">` tag to user profile meta tags that points to the default www.pubpub.org user profile.
=> update: Set canonical URL for user profiles

server/editor/queries.js, server/routes/pub.js, server/utils/index.js, shared/pub/metadata.js
This generates Google/Highwire meta tags for references on the frontend for pubs that use built-in footnotes or citations. It's a pretty naive generator; on the other hand, the tags themselves are [not well specified](https://citation.js.org/blog/?post=3781582023912504297). Eventually, we should probably write a CSL to produce these, but that seems like a multi-week project not particularly worth our time at the moment.
Features of this particular PR:
- De-duplicates among footnotes and tags
- Supports journal, conference, and book (defaulting to journal)
- Filters out unstructured inputs
_Test plan_
1. Visit pub with lots of citations and verify they are represented in meta tags 
2. Visit pub with duplicate tags (both within footnote/citation and across footnote/citation) and verify they …
=> new: Google Scholar/Highwire metadata

client/components/PubNoteContent/pubNoteContent.scss
=> fix: Breaks URLs and other long strings in note popovers

workers/tasks/export/styles/printDocument.scss
Fixes a small CSS issue in PDF exports where authors with super long affiliations had them cutoff on the cover page instead of wrapped.
Before:
After:
@idreyn: Let me know if there was a reason for setting nowrap here and if we should go instead with some kind of overflow setting higher up the tree.
_Test plan_
1. Create Pub with an author with a very long affiliation of at least 125 chars.
1. Export to PDF
1. Ensure that author name is not cutoff
1. Add a few more authors with long affiliations
1. Export PDF (requires updating the pub body)
1. Ensure that they all display properly and don't overlap
=> fix: Wrap long affiliations in HTML/PDF exports.

client/containers/Terms/Terms.js, client/styles/base.scss
Updates the TOS, and fixes some longstanding CSS weirdness that was causing abnormally large text sizes for list items.
_Test Plan_
- Visit `/tos`
- Read and make sure it matches the attached uploaded docx.
- Check all the links – 1 to CC and 4 email links – and make sure they work as expected.
[PubPub Terms of Service - 31 Oct 19 - CLEAN FINAL (1).docx](https://github.com/pubpub/pubpub/files/4119945/PubPub.Terms.of.Service.-.31.Oct.19.-.CLEAN.FINAL.1.docx)
=> update: Terms of Service

client/components/PubPreview/SubPreview.js
Tested locally using PUBPUB_PRODUCTION=true.
=> update: Commentaries and rejoinders for HDSR 2.1

client/containers/Pub/PubDocument/PubHeaderFormatting.js, client/containers/Pub/PubHeader/PubHeader.js, client/utils/useSticky.js
This addresses #678 and also Deepak's report that scrolling to the bottom of a Pub will sometimes cause large amounts of unpleasant jittering. Hoping to get a few pairs of eyes on this to verify that the problem is fixed, since I had some problem reproducing it to begin with.
_Technical mumbo-jumbo:_
It seems that Stickybits doesn't automatically recompute certain values when the total height of the page content changes, such as when a lot of text is added to a Pub — instead, you need to explicitly call the `update` method on the instance it provides. Here we observe changes using the `ResizeObserver` API where available, and using a timeout otherwise (in Safari and IE/legacy Edge). There are polyfills available for this API, but they appear not to work in this case. I factored the …
=> fix: Make sticky headers work when page size changes

client/containers/Legal/Terms.js, package-lock.json
Pretty straightforward. Adds a dialog with DMCA information to the TOS that was missing in our initial push. Since this does not edit the TOS, I don't believe sending an update to users is required.
Only weird-ish thing is I used a button, restyled to look like a link, because jsxa11y complained about using an anchor to launch the dialog.
_Test plan_
1. Visit Terms (/legal/terms)
2. Click "please click here for more information"
3. Verify that dialog opens when the line is clicked
4. Close dialog by clicking on the `x` in the header
5. Verify that dialog can be closed with escape and by clicking outside the dialog
=> new: Adds DMCA info without editing text of TOS

server/routes/redirects.js
The Bulletin of the American Astronomical Society (BAAS) just replaced their old WordPress site with PubPub, and there are a few URLs out in the wild that we want to preserve by establishing redirects. A couple of the new entries that we need are because PubPub doesn't accept URLs with trailing slashes for its established names. One of them is for a URL slug that apparently got changed at some point.
=> fix: Add a few additional redirects neeed by BAAS

client/components/LicenseSelect/LicenseSelect.js, client/containers/Pub/PubDocument/PubBottom/LicenseSection.js, package-lock.json, package.json, shared/license/licenses.js, static/license/copyright.svg, stories/components/licenseSelectStories.js
This PR allows users in communities with `premiumLicense === true` to select copyright as one of the licenses. Copyright has some logic built in:
- By default, the copyright date is the year the pub was published (or created, for draft pubs), and the copyright holder is the name of the community.
- This is manually overwritten for the COVID community to be 'Massachusetts Institute of Technology'. In the future, we should add a copyright holder field for collections.
- If the pub is in a primary collection that has a publication date (or, in the case of a conference, date) set, that date is the copyright date.
_Test plan_
1. Visit a pub in a community without the license flag set (ie cursor). Verify that you cannot select copyright.
1. Visit a pub in a community with the license flag set …
=> new: Select copyright for Pub license

client/containers/Legal/PrivacyPolicy.js, client/utils/heap.js, client/utils/hydrateWrapper.js, client/utils/legal/gdprConsent.js, package-lock.json, server/Html.js
Adds Heap tracking for both dev and prod, including the ability to opt out from tracking and small updates to the privacy policy.
The way Heap works is it assigns a relatively persistent anonymous `user_id` to every visitor. We can add an additional `identity` field from our side, and it will automatically merge sessions from the anonymous `user_id` when we supply an `identity` – useful for tracking logged in vs. logged out, and across devices. Also nice: we can strip or further anonymize the `identity` from downstream analytics in redshit etc. without losing the ability to match sessions.
So, this PR sets the PubPub user id as the Heap `identity` if a user is logged in and consents to tracking. 
Heap also allows you to set event properties. I've added an event property called `loggedIn` …
=> new: Heap tracking

client/components/Thread/Thread.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/DiscussionInput.js, client/containers/Pub/PubDocument/PubDiscussions/discussionUtils.js, client/containers/Pub/PubSyncManager.js, server/discussion/__tests__/api.test.js, server/discussion/api.js, server/discussion/permissions.js, server/discussion/queries.js, server/utils/firebaseAdmin.js, stubstub/stub.js
This PR sets the Visibility of new Discussion objects based on their branch of origin. If created on a 'public' branch (i.e. a Release), the Visibility is set to 'public'. In all other cases, the Visibility is set to 'members'.
This PR also disables the live syncing of discussion objects over the discussionsContentLive object on firebase. A new live-syncing approach will be implemented shortly.
=> fix: Discussion Visibility and syncing bugs

client/components/PubPreview/pubPreviewUtils.js, client/components/Thread/Thread.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/DiscussionInput.js, client/containers/Pub/PubDocument/PubDiscussions/discussionUtils.js, client/containers/Pub/PubSyncManager.js, client/containers/Search/Search.js, package-lock.json, package.json, searchSync/searchSync.js, server/discussion/__tests__/api.test.js, server/discussion/api.js, server/discussion/permissions.js, server/discussion/queries.js, server/routes/search.js, server/utils/firebaseAdmin.js, stubstub/stub.js, tools/dashboardMigrations/headerCols.js, workers/tasks/search.js, workers/utils/searchUtils.js
This PR makes several changes to update our search permissioning based on the new Members model. The Members model simplifies the handling of private data by simply including an `accessIds` array on each algolia object which is filtered against. 
This does not yet account for Pubs who have their draft set to be publicly visible, as the PublicPermissions model is still in development.
=> update: Make searchSync and searchUtils work with new Member model

server/rss/queries.js
I wasn't 100% sure if branches could be stripped out or not in the query, but it seems to work.
_Test Plan_
- visit `/rss.xml` and make sure it generates XML.
- Copy output and [validate](https://validator.w3.org/feed/check.cgi)
=> fix: Include release model in RSS query

client/components/Thread/ThreadComment.js, client/containers/Pub/PubDocument/PubBody.js, client/containers/Pub/PubDocument/PubBottom/Discussions/DiscussionsSection.js, client/containers/Pub/PubDocument/PubBottom/PubBottom.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/Discussion.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/DiscussionInput.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/DiscussionReanchor.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/LabelSelect.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/ManageTools.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/ThreadComment.js, client/containers/Pub/PubDocument/PubDiscussions/Discussion/discussion.scss, client/containers/Pub/PubDocument/PubDiscussions/Discussion/labelSelect.scss, client/containers/Pub/PubDocument/PubDiscussions/DiscussionGroup/DiscussionGroup.js, client/containers/Pub/PubDocument/PubDiscussions/PubDiscussions.js, client/containers/Pub/PubDocument/PubDiscussions/discussionUtils.js, client/containers/Pub/PubDocument/PubDiscussions/pubDiscussions.scss, client/containers/Pub/PubDocument/PubDocument.js, client/containers/Pub/PubSyncManager.js, server/discussion/__tests__/api.test.js, server/discussion/api.js, server/discussion/permissions.js, server/discussion/queries.js, server/utils/queryHelpers/scopeGet.js, stories/containers/Pub/PubDiscussions/discussionThreadStories.js
After the Dashboard migration, there's some stuff we can clean up around discussions:
- Re-enabling discussion labels with some permissions tweaks
- Applying a modicum of styling to the discussion management buttons
- Some props cleanup — it is not necessary to be passing `firebaseRef` and `collabData` deep into the discussions render tree.
Here is a discussion with the new buttons layout — I think the text labels improve the buttons:
_Test plan:_
- Create a discussion from both the pub bottom and the pub document
- Edit a ThreadComment
- Archive a discussion
- As an admin, un-archive a discussion
- Re-anchor a discussion
- As an admin, create a label
- As an admin, apply a label to a discussion
- As an author, apply a label to a discussion
- Run `npm run test server/discussion/`
=> fixes: pub discussions touch-up

server/utils/queryHelpers/scopeGet.js
This PR adds a simple manual community-level override for `canCreateDiscussions` which will disable the public ability to create discussions.
This will eventually be more properly implemented through the PublicPermissions table.
=> dev: Add custom public discussion disable

server/collectionAttribution/queries.js, server/pubAttribution/queries.js, server/rss/queries.js, server/utils/citations.js, server/utils/collectionQueries.js, shared/utils/ensureUserForAttribution.js
This pull request implments the temporary fix suggested in #784. For shadow authors, the assumption for last name parsing (as used to generate citation data) is that everything after the final space is the last name. 
A bit of cleanup to use the `ensureUserForAttribution` everywhere is also included.
Finally, the `id` field has been removed from the citation data in `server/utils/citations.js` as it was causing strange caching behavior. APA and Harvard citations weren't being updated to reflect new author information. Cite must keep a working cache in memory that is references with the `id` field.
=> update: Change shadow author last name assumption

client/containers/Search/Search.js
This PR fixes the issue where loading Search with a query in the URL would not launch a search request. This addresses part of #800.
_Test Plan:_
- Navigate to the review app below
- append `/search?q=a` to the URL and verify that the search completes with results.
=> fix: Search on page load bug

client/components/Editor/plugins/headerIds.js, client/containers/Pub/PubHeader/headerUtils.js
This PR addresses #780. Article headers with leading numbers were not properly linking in the ToC. The HTML generated for the headers was formatted (by Prosemirror I believe) to be compliant with HTML standards that say you're not allowed to start a tag `id` with a number. In both the editor plugin and ToC generator, our regex was skipping this part, but because ProseMirror handled it for us in HTML, the ToC and HTML content became out of sync.
The fix is to add a regex that strips leading numbers from header ids in both the Editor plugin and the ToC generator.
=> fix: Strip leading numbers from TOC

server/routes/pubDocument.js, server/utils/queryHelpers/pubSanitize.js
This PR adds a couple checks to resolve a couple bugs related to `/pub/release` route handling.
=> fix: Add releaseNumber check

client/components/Menu/Menu.js
This PR fixes a popover Menu flipping bug that was showing up on the MemberPermissionPicker component.
=> fix: Prevent Menu component flipping

client/containers/Pub/PubHeader/pubHeader.scss
This PR addresses #783. The issue seems to be a difference in how chrome renders `box-decoration-break`. Adding an additional margin equal to the column-gap makes ensures that Chrome breaks each line in time to avoid overlap.
=> fix: header-block chrome overflow bug

client/containers/Pub/PubHeader/DraftReleaseButtons.js, client/containers/Pub/PubHeader/PubHeaderContent.js, client/containers/Pub/PubHeader/UtilityButtons.js
This PR addresses #794. It sets the contents button to consistently render in the right-hand list for all cases: Release, Draft, and mobile on both.
=> update: Use consistent ToC placement

server/pub/queries.js, stubstub/modelize/builders.js
This PR fixes a bug that was causing new pubs to be inaccessible to their creator because no Member object was created. Additionally, it adds a default userId to Pub modelize builder as createPub should never be called without a creating User.
_Test Plan:_
- Log into a community with an account that is not a community-level admin or manager.
- Click any public 'New Pub' button
- Verify that you are redirected to a pub you can access, and not a 404 page.
=> fix: Create Member on new pub creation

client/components/FormattingBar/media/Media.js, client/components/FormattingBar/media/MediaGithub.js, client/components/FormattingBar/media/MediaYoutube.js, client/utils/index.js, package-lock.json, server/editor/api.js
Got a number of requests for Gists and/or syntax highlighting for code blocks recently from folks coming over from Medium.
This PR allows users to embed Gists via the media bar. Unfortunately, GitHub no longer maintains oembed URLs. So, this pings the GitHub API to verify that the Gist exists, and if so, reconstructs the script tag embed tag and adds it to the iframe src as a data url, along with some styling.
This approach looks basically native for single-file gists, has few security implications, fits well into our existing embed model, and avoids having to build a new block in the editor for Gists. 
But there are two downsides: for multi-file gists, there's an additional scrollbar that's a little wonky (see screenshot). And because we use a data url for the iframe source, changing the …
=> GitHub gist embed

client/containers/Pub/PubDocument/pubBody.scss, workers/tasks/export/styles/printDocument.scss
- Moves errant print declarations out of `pubBody.scss` into `printDocument.scss` (side note: at some point we should see what happens if we use `printDocument.scss` as a print stylesheet when people try to just cmd/ctrl-p a pub)
- Manually sizes down a bunch of elements for print version to a base size of 14px, including headers, which a few folks have said are too big for PDFs.
_Test_
Export a PDF? Here's an attached one that shows all the new sizing.
[74b345af-c3e9-4062-8cdd-1f8d8e865f6e (5).pdf](https://github.com/pubpub/pubpub/files/4652785/74b345af-c3e9-4062-8cdd-1f8d8e865f6e.5.pdf)
=> fix: bullet and header size

client/utils/hydrateWrapper.js, server/server.js, server/utils/initData.js, shared/utils/environment.js, workers/environment.js, workers/queue.js
This PR adds release information to our `Sentry.init` configuration, thanks to the recently discovered [Dyno Metadata lab option](https://devcenter.heroku.com/articles/dyno-metadata). I've set this flag for both `pubpub-v6-dev` and `pubpub-v6-prod`.
I also added a Sentry initialization to `workers/queue.js` which (from what I can tell) was missing altogether.
=> dev: Update sentry to use release info

client/components/PubShareDialog/PubShareDialog.js
This PR resolves #814. Sharing URLs now include `/draft` to avoid unwanted redirection to a Release (if it exists).
=> fix: Add draft to Sharing URLs

client/containers/Search/Search.js, package.json, utils/hooks.js
This PR resolves #819. A search will now execute at the tail end of user input into the search text box.
=> fix: always update search results after user stops typing

client/containers/Search/Search.js, utils/hooks.js
Follow-up PR to #866 that splits options object for `useThrottled` into two boolean args, `leading` and `trailing`. This simplifies the code a bit and fixes an issue where the throttling would not behave as expected when either option was undefined.
=> fix: use positional args in useThrottled and provide boolean defaults for leading/trailing options

package-lock.json, package.json, server/pub/model.js, tools/index.js, tools/migration2020_06_24.js, workers/tasks/import/bulk/README.md, workers/tasks/import/bulk/directives/pub.js, workers/tasks/import/import.js, workers/tasks/import/metadata.js
This PR makes two changes to support upcoming bulk imports:
- Adds a `metadata` field to the `Pub` model that can support a JSON blob of arbitrary metadata, to hold onto later. I'm open to calling this something else.
- Provides the ability to extract metadata from YAML document headers in non-Markdown documents, which Pandoc doesn't seem to support without some kludges.
_Test plan:_
Colocate these two files in the same directory:
test.html:
```html
---
title: This Pub Has a Title
subtitle: It really does, wow
authors:
- Travis Rich
- Mystery Author
- Gabriel Stein
date: 2019-05-25
pubMetadata:
hi: hello
yes: it works
---
<h1>Hello!</h1>
<p>This is a test.</p>
```
config.pubpub.yaml
```yaml
type: community
subdomain: test
children:
test.html:
type: pub
extractMetadataFromDocument: true …
```
=> update: Improve metadata imports

client/components/Footer/footer.scss
This PR resolves #828 by removing the `width: 100%` rule from the footer logo element. The image will retain its original aspect ratio, and will not scale up to a larger width or height than the source image's base dimensions.
In addition, this PR fixes the alignment of the footer left/right elements in smaller viewports (around tablet dimensions).
Before:
After:
=> fix: maintain aspect ratio of footer logo

client/containers/Search/Search.js, server/Html.js
This PR fixes a couple of issues on the Search page with pagination and mode transitions that I suspect are the same issues outlined in #853, specifically the second and third bullet points:
> Sometimes an initial search (under "Pubs") produces results; then clicking on the "Pages" tab produces similar results, and then clicking on the "Pubs" tab no longer shows results (but results continue to appear under "Pages").
and
> In either case above, in the "Pages" results-view, search results include pubs, but the URL of each result is missing "/pub/", and so does not resolve (generating a "Page Not Found" error). Adding "/pub/" back in makes them resolve as expected.
I believe these two points are caused by the same issue - that pubs would still appear in the results when the user attempted …
=> refactor: refactor search and fix issues with pagination and mode transitions

client/components/FormattingBar/controlComponents/ControlsFootnoteCitation/InlineLabelEditor.js, client/containers/DashboardSettings/PubSettings/CitationChooser.js, server/editor/citeStyles/apa-7.csl, server/editor/queries.js
This PR makes two largely aesthetic changes to citations that were waiting in my stash until I finished dashboards. Both of them will speed up TMB production by 20-30 minutes or more per article.
1. It adds the APA 7th Edition, released last year, as a citation option, and renames the built-in citation.js style to APA 6th Edition. I [submitted a PR](https://github.com/citation-js/citation-js/pull/89) for citation.js that was accepted, but the release date is unknown. For TMB, we need to support APA 7, but there are also a number of highly visibly changes from APA 6 to 7 (ie shortening to et al after 2 authors instead of 4) that add to the production time of TMB articles. In a future update (probably triggered by the next citation.js update), I suggest we move to not using any of the …
=> update: Add APA 7th CSL, better custom inline experience

client/components/Editor/utils/branches.js, client/components/Editor/utils/discussions.js, client/components/PubReleaseDialog/PubReleaseDialog.js, client/components/PubReleaseDialog/pubReleaseDialog.scss, server/discussion/queries.js, server/release/api.js, server/release/queries.js, server/utils/firebaseAdmin.js
We have a Commonplace piece with a draft containing lots of annotations that need to carry over to the Release. In other words, we need to do the following:
- Batch-update the `Visibility` of every discussion in the Pub draft to set `access = public`
- Update the Release branch in Firebase with the correct discussion anchor information
I have wrapped these two things into a new checkbox in the Release modal, as seen here:
This solves our immediate problem, but my question is, do we want to give everyone the ability to do this? Without a more robust toolkit for managing discussion visibility it feels like this is a potentially dangerous thing to give to users. So I've made it accessible only to the superadmin account for the time being.
_Test plan:_
- I created a discussion on the draft of …
=> feature(?): Make it possible to "release" draft discussions with Release

server/pubEdgeProposal/api.js, utils/crossref/isDoi.js, utils/crossref/parseDoi.js
This PR adds support for resolving DOIs from doi.org URLs.
**Test Plan:**
* Run:
```sh
curl http://localhost:9876/api/pubEdgeProposal\?object=http%3A%2F%2Fdx.doi.org%2F10.1155%2F2014%2F413629
```
* Review the response: it should have an `externalPublication` field that conforms to the `ExternalPublication` shape.
=> feature: resolve data from doi.org URLs in pubEdgeProposal endpoint

client/components/Editor/plugins/collaborative/document.js, client/components/Editor/utils/branches.js, client/components/Editor/utils/firebase.js, client/components/Editor/utils/firebaseDoc.js, client/containers/Pub/PubSyncManager.js, server/utils/firebaseAdmin.js
A failure mode I encountered recently that was causing an uptick in timeouts:
- Someone creates a very long Pub (30k firebase changes)
- They can load the draft just fine because of incremental checkpoints
- They create a Release, which bunches all of the changes into a merge, but doesn't create a checkpoint
- Loading that Release is slow because it has to reassemble the doc from changes 0 to 30k, causing timeouts/OOM
To solve this I have added functionality to create a checkpoint when two branches are merged, e.g. when a Release is created. It will only be a bit of extra work to arrive at one of these more stable solutions:
- drop Release branches entirely and read Release content from `(draftBranchId, key)` pairs
- just store Release docs in Postgres and load them from there
...but this …
=> fix: Create checkpoints on branch merge

client/containers/DashboardImpact/DashboardImpact.js, client/containers/DashboardMembers/DashboardMembers.js, client/containers/DashboardPages/DashboardPages.js, client/containers/DashboardReviews/DashboardReviews.js
While working on the dashboard tab for Pub edges, I realized that the `details` prop of the `DashboardFrame` is criminally underused, and could be employed to give brief explanations about what each Dashboard tab does. I've taken a stab at the copy here, feel free to poke holes in it or just tell me that this is a silly idea.
Here's what it looks like when text is rendered into `details`:
=> update: Add one-line explanations to the top of most dashboard pages

server/pubEdgeProposal/api.js, server/pubEdgeProposal/queries.js, server/utils/scrape.js
This PR fixes an error that would occur if the crossref REST API returned a 404 for a (probably invalid) DOI. In addition, it adds support for Highwire/Google Scholoar `citation_*` meta tags, and adds some clarifying/structural comments to the scraper module.
=> fix: support citiation_ tags and fix error on crossref 404

client/components/PubEdge/PubEdge.js, client/components/PubEdge/pubEdge.scss, client/components/PubEdgeListing/PubEdgeListingCard.js, client/components/PubEdgeListing/pubEdgeListingCard.scss, server/pubEdgeProposal/queries.js
This PR addresses the following feedback:
1. `.pub-edge-component .title-container` : change font-size to 18px and line-height to 24px (using px instead of em for specificity)
2. `.pub-edge-listing-card-component>.relation .drop-return`: change bottom to 1px (for better alignment with adjacent text layer's baseline)
3. Use multidisplay font for metadata.
4. Use 12px font size for metadata.
5. Use lighter border when PubEdge card is inactive/not hovered. This was accomplished using `mouseenter`/`mouseleave` events.
6. Drop return icon now has accent color before and after hovering.
=> fix: improve pub edge styling; use anchor instead of clickable div

client/components/PubEdge/PubEdge.js, client/components/PubEdgeListing/PubEdgeListing.js, client/components/PubEdgeListing/PubEdgeListingControls.js, client/components/PubEdgeListing/pubEdgeListingCard.scss, client/containers/DashboardEdges/NewEdgeInput.js, server/pubEdgeProposal/queries.js, server/utils/scrape.js
This PR is a fast-follow to #905 that addresses PR feedback and fixes some additional feedback from team including:
- Author email and ORCID information showing up in contributors from Medrxiv pub edge proposal
- "or DOI" missing from pub connection search/fuzzy finder
- Carousel controls remaining active when only item existed in filtered array of connections
=> Pub Connection Tweaks

client/containers/DashboardSettings/PubSettings/CitationChooser.js
It was spelled right in our hearts/accents.
=> fix: Misspelled Harvard

client/components/PubEdge/PubEdge.js, client/components/PubEdge/pubEdge.scss
This PR improves the meta key + click and keyboard enter behavior of the PubEdge element. cmd+clicking the parent (when `actsLikeLike==true`, as well as cmd+clicking internal links (except for description toggle) will now consistently open the target URL in a new tab.
=> fix: improve keyboard/mouse a11y of pub edge card

client/containers/DashboardSettings/CollectionSettings/CollectionMetadataEditor.js, client/containers/DashboardSettings/PubSettings/Doi.js, server/doi/__tests__/api.test.js, server/doi/api.js
This PR adds a new endpoint `GET /api/doiPreview` that essentially does the same thing as the `POST /api/doi` endpoint without submitting the deposit to Crossref.
The endpoint has the same authN rules as the `POST` endpoint, and returns an object with both the raw JSON and compiled XML forms of the deposit. The JSON is provided in case we want to show tabs for both XML and JSON representations of the deposit in the dashboard in the future. I'm also using the JSON payload in the API tests.
**Test Plan:**
* Set `PUBPUB_LOCAL_COMMUNITY` to `'test'`
* Start PubPub and log in
* Visit http://localhost:9876/api/doiPreview?pubId=4f54941a-bdaa-446d-bf8b-72aced92e028&communityId=df04b703-65a6-4b8d-8c58-ebdf76c94c4a&target=pub
=> feature: add deposit preview endpoint

client/components/PubEdge/PubEdge.js, client/components/PubEdge/PubEdgeEditor.js, client/components/PubEdge/PubEdgePlaceholderThumbnail.js, client/components/PubEdge/pubEdgePlaceholderThumbnail.scss, client/components/PubEdge/pubEdgeStories.js, client/components/PubEdgeListing/PubEdgeListingCard.js, client/components/PubEdgeListing/pubEdgeListing.scss, client/components/PubEdgeListing/pubEdgeListingCard.scss, client/components/PubEdgeListing/pubEdgeListingStories.js, client/containers/Pub/PubDocument/pubDocument.scss
Based on feedback from @djagdish, this PR:
* Changes the un-hovered border color to `#dddddd`
* `.pub-edge-listing-card-component` -- increases margin-bottom to 30px to add a bit more breathing space between cards when viewed in list format
* `.pub-edge-listing-component` -- adds padding-top and padding-bottom of 20px to add a bit more space between Pub body and the related pubs.
* Adds placeholder thumbnails when a connected pub or external publication doesn't resolve with an avatar.
**Without hover state:**
**With hover state:**
=> fix: pub connection styling fixes and placeholder thumbnails

workers/tasks/export/styles/printDocument.scss
Very quick fix to make bullets in exports the same size as everything else. Previously, they were much larger. I also commented out some CSS that I had added but realized didn't actually take effect yet because I didn't capitalized Mirror in ProseMirror. I intend to go back and make these changes eventually
_Test Plan_
1. Export a PDF with a paragraph, an unordered list, and an ordered list (ie: https://demo.pubpub.org/pub/md4wb7lk/draft). Make sure it's all the same size.
=> Export bullet font size fix

client/components/PubReleaseDialog/PubReleaseDialog.js, client/containers/DashboardEdges/NewEdgeInput.js, client/containers/Pub/PubHeader/DraftReleaseButtons.js, server/release/__tests__/api.test.js, server/release/api.js, server/release/queries.js, stubstub/stub.js, workers/tasks/import/bulk/README.md, workers/tasks/import/bulk/cli.js, workers/tasks/import/bulk/publish.js
This PR includes a bundle of fixes related to Releases that have been piling up:
- There is a UI bug that appears to let you create a Release from an empty Pub, which is something we need to continue to disallow for the time being due to technical debt in our Firebase infra (cc @metasj)
- Last week we had a conversation the possibility of Releases created from bulk import clogging up the worker queue. I dug into it and it turns out this is behavior we _should_ be seeing, but aren't — the dashboard-adjacent migration from branch-merges to Releases didn't carry over the desired behavior of kicking off exports at publish time. So not only do we need to restore that, we also need a flag to selectively disable the newly-restored behavior during bulk import!
- Sort of central to all of this, …
=> Some Release fixes

client/components/AssignDoi/AssignDoi.js, client/components/AssignDoi/AssignDoiPreview.js, client/components/AssignDoi/assignDoi.scss, client/components/AssignDoi/assignDoiPreview.scss, client/components/index.js, client/containers/DashboardSettings/PubSettings/Doi.js
This PR adds a new component `AssignDoi` which handles previewing and submission of DOI deposits to Crossref. Existing deposit submission logic was removed from the `<Doi>` component used in Pub settings and replaced with `<AssignDoi>`. The deposit preview has both a human-readable view of the deposit and the raw XML that will be sent to Crossref. Previews are supported for journal articles, conferences, and books.
Resolves #908
=> feat: deposit preview for journals, conferences, books

client/components/PubEdge/PubEdge.js, client/components/PubEdge/pubEdge.scss, client/components/PubEdgeListing/PubEdgeListingCard.js
- Screenreader will not read the arrow icon on `PubEdgeListingCard`
- Only one URL tab-target per card
- URL hostname does not have link-like hover effect
- Simplified `PubEdge` markup and handlers
_Test plan:_
Check out the Storybook fixtures and make sure it still looks like it works!
=> fix: Some cleaner markup in PubEdge-related components

workers/tasks/search.js
The `updateCommunityData` worker task references an obsolete Algolia API function — I've updated it to use the new equivalent here.
_Test plan:_
I ran the `updateCommunityData` task locally on a community and verified that it completed without error.
=> fix: Fix the updateCommunityData worker task

server/collection/model.js, server/crossrefDepositRecord/model.js, server/crossrefDepositRecord/queries.js, server/doi/__tests__/api.test.js, server/doi/api.js, server/doi/queries.js, server/models.js, server/pub/model.js, tools/migrations/2020_07_22_addCrossrefDepositRecord.js
This PR adds a new model, `CrossrefDepositRecord`, which is upserted each time a Collection or Pub is deposited in Crossref (via `setDoiData`). The presence or absence of this property on a Pub will determine whether or not that Pub's DOI is editable in a future PR.
=> feature: persist deposit record for deposited pubs and collections

tools/backfillCrossrefDepositRecords.js, tools/index.js, utils/crossref/communities.js
This PR adds a new tool which creates CrossrefDepositRecords for Pubs and Collections that have a "managed DOI prefix" found in `utils/crossref/communities`.
**Test Plan**
* Update a Pub or Collection with a unique DOI prefix, e.g. `10.111111`
* Modify the script so that the `managedDoiPrefixes` variable contains that single prefix, e.g. `['10.111111']`
* Run the script: `npm run tools backfillCrossrefDepositRecords`
* Respond yes to the following prompt:
```
prompt: Create CrossrefDepositRecords for 1 Pubs with the following DOI prefixes: 
10.111111?:  (no) yes
```
* Run the script. Verify that a new `CrossrefDepositRecord` was created and the Pub's `crossrefDepositRecordId` is equal to the new record's `id`
=> chore: add deposit record backfill tool

workers/tasks/import/rules.js, workers/tasks/import/util.js
Updates the import task to use the `content` of a citation as the `customLabel` if available. This typically applies to JATS, which can have custom citation content. If no citation content is available, it reverts to the default. This saves a ton of time importing files from pre-formatted JATS that have custom citation labels.
_Test plan_
1. Import a JATS file with both citation content (ie `<xref ref-type="bibr"...>content</xref>` and without (ie `<xref ref-type="bibr" />` (attached as text – change extension to xml, for your convenience)
1. Verify that the first citation, `rid="c8"` which has no content, uses the default inline for the Pub
1. Verify that custom citation labels match the text between xrefs (ie `<xrex...>content</xref>`) for other citations in the file
1. Switch citation …
=> update: parse content of citation and use as customLabel if available

client/components/AssignDoi/AssignDoi.js, client/components/AssignDoi/assignDoiPreview.scss, client/containers/DashboardSettings/PubSettings/Doi.js, client/containers/DashboardSettings/PubSettings/PubSettings.js, client/containers/DashboardSettings/PubSettings/doi.scss, server/pub/permissions.js
This PR adds an editable DOI field to the Pub settings page. The DOI is editable when users have the correct permissions and a Crossref deposit has not been submit. Once a Crossref deposit record is created, the DOI field will become uneditable.
* Create a new Pub.
* Log in with a user without manage permissions.
* Go to the settings page.
* The DOI field should not be editable.
* Log in with a user with manage permissions.
* Go to the setting spage.
* The DOI field should be editable.
* Enter an invalid DOI, e.g. `10.116299608f92.834c6596`
* An error message should appear in red and the DOI should not be updateable.
* Enter a valid DOI, e.g. `10.1162/99608f92.834c6596`
* Click "Update DOI"
* The error message should disappear and be replaced by the "DOI updated successfully" message in …
=> feature: editable doi field

server/routes/pubDocument.js, server/utils/ssr.js
Resolves #948 by updating the pub route to use the `getPubPublishedDate` helper instead of relying on now nonexistent `publishedAt` fields in `pubData`.
Also adds dc.date metadata if there is a published on date.
_Test plan_
1. Visit a Pub that is not released (ie http://demo.duqduq.org/pub/b7ag4toy/draft), verify that no `dc.date` nor `citation_publication_date` meta tag is present.
1. Visit a pub that is released (ie http://demo.duqduq.org/pub/xp0zizup/release/1), verify that `dc.date` meta tag is present with a result in the `YYYY-MM-DD` format, and verify that `citation_publication_date` meta tag is present with a result in the `YYYY/MM/DD` format.
=> fix: use date helper to get published date for meta tags

server/utils/ssr.js, utils/pub/metadata.js
Sorry, one more! Resolves #923 by ordering downloads by date and exports by historyKey.
=> fix: use the latest formatted PDF or export in metadata

client/components/PubEdge/PubEdge.js, client/components/PubEdge/PubEdgeEditor.js, client/components/PubEdge/util.js, utils/dates.js
Resolves #945 
This is a quick PR to fix my rather goofy attempt at using the native `input type="date"` in the `ExternalPublication` connection creator interface. Things that change:
- We use the `input.valueAsDate` property where available, and fall back to parsing `input.value` in browsers where this isn't supported — as far as I can tell, this is just Safari, which makes you input a date by hand as well.
- We render the stored `publicationDate` in UTC time, so users in western time zones don't see it rendered as the day before.
_Test plan:_
- Make sure you can still create Connections to other Pubs as always
- In (Chrome, Firefox, Edge) make sure that you can select a publication date, and that the date, rather than an adjacent date, is actually chosen and displayed.
- In Safari make …
=> fix: Fixes for date picking and display for ExternalPublication objects

client/components/FormattingBar/controlComponents/controls.scss, client/components/FormattingBar/media/media.scss, client/components/FormattingBarLegacy/Controls/controls.scss, client/components/FormattingBarLegacy/Media/media.scss, client/components/MinimalEditor/minimalEditor.scss, client/components/PubHistoryViewer/pubHistoryViewer.scss, client/containers/Pub/PubDocument/PubFileImport/fileImportDialog.scss, client/containers/Pub/PubHeader/collections/collectionBrowser.scss
Recently I dragged myself kicking and screaming back to the macOS setting with real scroll bars, and to my horror there are quite a few places where we are using `overflow: scroll` (which always shows a scrollbar whether one is needed or not) instead of `overflow: auto` (which only shows a scrollbar if there is overflowing content to scroll). Most of these usages can be chalked up to my past misunderstanding of how this property works, so I have gone in and removed `overflow: scroll` wherever I found it.
I'll include screenshots inline to demonstrate the before/after of these usages.
=> fix: Remove the scourge of overflow: scroll

client/components/AssignDoi/AssignDoi.js, client/components/AssignDoi/AssignDoiPreview.js, client/containers/DashboardSettings/PubSettings/Doi.js, client/containers/DashboardSettings/PubSettings/doi.scss, package.json, server/crossrefDepositRecord/queries.js, server/doi/queries.js, tools/backfillCrossrefDepositRecords.js, utils/crossref/communities.js, utils/crossref/createDeposit.js
This PR makes the DOI suffix editable for communities with custom DOI prefixes. The field is no longer editable after the first deposit is made. If no custom DOI prefix is specified, the DOI will be automatically generated in the same manner it usually is.
A delete button was added to remove a DOI from a Pub. This button is also only accessible while the DOI is editable.
**Test Plan**
1. Create a new Pub within a community with a custom DOI prefix.
2. Navigate to the Pub settings page in the dashboard.
2. Assign a custom DOI prefix using the text field and clicking "Update".
3. Open the deposit preview by clicking the "Preview Deposit" button. The custom suffix should be applied to the DOI within the preview.
4. Assign a new custom DOI prefix by repeating step 2.
5. The custom suffix …
=> feature: Editable DOI suffix for communities with custom DOI prefix

client/components/AssignDoi/AssignDoi.js, client/components/AssignDoi/AssignDoiPreview.js, client/components/AssignDoi/assignDoi.scss, client/containers/DashboardSettings/PubSettings/Doi.js, server/doi/api.js, server/doi/queries.js, server/utils/queryHelpers/pubOptions.js, utils/crossref/createDeposit.js, utils/crossref/parseDeposit.js, utils/crossref/render/preprint.js, utils/crossref/schema/book.js, utils/crossref/schema/conference.js, utils/crossref/schema/conferencePaper.js, utils/crossref/schema/contentItem.js, utils/crossref/schema/doiData.js, utils/crossref/schema/journal.js, utils/crossref/schema/journalArticle.js, utils/crossref/schema/journalIssue.js, utils/crossref/schema/postedContent.js, utils/crossref/transform/collection.js, utils/crossref/transform/pub.js
Closes #912
This PR adds a new field to the deposit form that allows a Pub admin to update the resource's `content_version`.
The field's options are detailed below:
* **(None)** un-sets the `<resource>` element's `content_version` attribute of the work
* **Advance Manuscript** sets the `<resource>` element's `content_version` attribute to `"am"`(advance manuscript)
* **Version of Record** sets the `<resource>` element's `content_version` attribute to `"vor"`
* **Preprint** converts the record to a `posted_content` item
Since changing the content version of the work results in changes to the deposit, the entire deposit preview is re-fetched each time the dropdown's selected item changes, as demonstrated below:
(sorry for the blurry gif)
**This PR does not include:**
- Automatically …
=> feature: add content version field and preprint (posted_content) deposits

client/components/DatePicker/DatePicker.js, client/components/DatePicker/datePickerStories.js, client/components/PubEdge/PubEdge.js, client/components/PubEdge/PubEdgeEditor.js, client/components/index.js, client/containers/DashboardSettings/PubSettings/PubSettings.js, server/pub/permissions.js, utils/dates.js, utils/pub/pubDates.js
This PR allows users to set the `customPublishedAt` field that is displayed in place of the first Release date for a Pub as its publication date, as shown here:
There is a new `DatePicker` component in this PR that will make this sort of thing easier in the future. It uses the browser's built-in datepicker, which is good and getting better in most browsers, but still requires desktop Safari users to manually type dates in the indicated YYYY-MM-DD format, which is not the worst fate. The innards of this component do not look like idiomatic React, but its interface is much nicer than `<input type="date">` as it will only return a valid `Date` object or `null`.
_Test plan:_
- In the Storybook fixture for `DatePicker`, make sure the component works (including picking, typing, and clearing …
=> feature: Custom publication date picker for Pubs

client/components/AssignDoi/AssignDoi.js, client/components/AssignDoi/AssignDoiPreview.js, client/components/AssignDoi/assignDoi.scss, client/containers/DashboardSettings/PubSettings/Doi.js, client/containers/DashboardSettings/PubSettings/doi.scss, package-lock.json, package.json, server/doi/api.js, server/doi/queries.js, server/pub/model.js, server/routes/dashboardSettings.js, tools/migrations/2020_07_22_addCrossrefDepositRecord.js, utils/crossref/createDeposit.js, utils/crossref/createDoi.js, utils/crossref/parseDeposit.js, utils/crossref/render/review.js, utils/crossref/render/supplement.js, utils/crossref/schema/componentList.js, utils/crossref/schema/doiBatch.js, utils/crossref/schema/doiData.js, utils/crossref/schema/helpers/date.js, utils/crossref/schema/peerReview.js, utils/crossref/transform/collection.js, utils/crossref/transform/pub.js, utils/pubEdge/relations.js
Closes #911
Supplements, Preprints, Reviews (oh my). This PR does a lot of things:
> Note: Looks like GitHub is auto-collapsing the first file (AssignDoi.js), so make sure to expand it when reviewing.
- Derives `sa_component` deposit type for deposited Pub when it `isSupplementTo` another Pub.
- Derives `peer_review` deposit type for deposited Pub when it `isReviewOf` another Pub.
- Derives `posted_content` deposit type for deposited Pub when it `isPreprintOf` another Pub.
- Allows user to set the Content Version of a work deposited to Crossref with a dropdown (unavailable to preprints).
- Allows user to set the Review Type and Review Recommendation of a peer review.
- Automatic re-loading of the deposit preview when any of the above information changes.
- Automatic generation of DOIs for …
=> feature: deposit supplements, preprints, and peer reviews

client/components/AssignDoi/AssignDoi.js, client/components/AssignDoi/AssignDoiPreview.js, client/containers/DashboardSettings/PubSettings/Doi.js, server/doi/api.js, server/doi/queries.js, utils/crossref/__tests__/__snapshots__/createDeposit.test.js.snap, utils/crossref/__tests__/createDeposit.test.js, utils/crossref/__tests__/data/pubHasPreprint.js, utils/crossref/__tests__/data/pubHasReview.js, utils/crossref/__tests__/data/pubHasSupplement.js, utils/crossref/__tests__/data/pubIsPreprintOf.js, utils/crossref/__tests__/data/pubIsReviewOf.js, utils/crossref/__tests__/data/pubIsSupplementTo.js, utils/crossref/createDeposit.js, utils/crossref/createDoi.js, utils/crossref/parseDeposit.js, utils/crossref/transform/pub.js, utils/pubEdge/relations.js
This PR:
- Fixes linting errors and tests.
- Adds new snapshot tests for the more complex relationship types: preprints, peer reviews, and supplements.
- Updates the component IDs to use truncated pub ids as the component suffix,e.g. `{community}/{parent.collection.id}.{parent.id}/{supplement.id}`
- Filters out PubEdges for preprints and supplements when the relationship approved by the target for both inbound AND outbound connections (was previously just for outbound).
=> feature: Pub Connection DOI deposits cleanup

server/collectionPub/model.js, server/member/__tests__/api.test.js, server/pubHistory/__tests__/api.test.js, server/utils/collectionQueries.js, tools/index.js, tools/migrations/2020_08_12_noNullCollectionPubRanks.js, tools/rerankCollections.js, utils/rank.js
A ticket came across Freshdesk today where a user was prevented from reordering a Collection in the Collection Dashboard. An intermediate cause of this was that some of the `CollectionPubs` in the Collection had `rank = NULL`, which makes it impossible to find a rank between it and another Pub.
While we originally allowed null ranks in Collections (either I was lazy or the old Collections editor might have handled this gracefully?) we do now need to enforce that `CollectionPubs` have a string rank. So this PR contains:
- A change to the Sequelize model definition
- A migration to make this change to the live database schema
- A small script to identify Collections with null ranks lurking in them and re-rank them. It's important that this script preserves ordering in these Collections as …
=> fix: Forbid null CollectionPub ranks

utils/crossref/__tests__/__snapshots__/createDeposit.test.js.snap, utils/crossref/schema/journal.js
Closes #985
Fixes an issue where deposits for communities with long titles would fail due to a 150 character restriction on the `abbrev_title` field. This PR simply removes the optional `abbrev_title` element from `journal_metadata` deposits.
=> feature: remove abbrev_title from journal deposits

client/components/AssignDoi/AssignDoiPreview.js
A small falsy check to prevent fatal error when deposit doesn't contain a contributors property in the case of no Pub attributions.
Fixes #992
=> fix: don't crash when depositing pub with zero contributors

stubstub/determinize.js, stubstub/index.js, stubstub/stub.js, tools/searchSync.js, workers/utils/__tests__/__snapshots__/searchUtils.test.js.snap, workers/utils/__tests__/searchUtils.test.js, workers/utils/searchUtils.js
Unexpected changes to the behavior of the functions in `searchUtils.js` force us to retroactively update the Algolia index, which is time consuming and expensive, so I've added a bit of snapshot testing for them here.
_Test plan:_
Run `npm run test workers/utils`
=> dev: Add snapshot testing for searchUtils functions

package-lock.json, package.json, server/routes/index.js, server/routes/robots.js, server/routes/sitemap.js, static/robots.txt, utils/canonicalUrls.js
Closes #976
This PR adds sitemaps to communities.
The static robots.txt file is replaced with a dynamic file which builds the robots file on a per-community basis. The robots.txt file for communities will now point to the sitemap via the `Sitemap` rule, e.g. `Sitemap: http://community.pubpub.org/sitemap-index.xml`.
If a sitemap has not been generated for a community, or the sitemap was updated over 24 hours ago, a sitemap index and child sitemaps (e.g. sitemap-0.xml, sitemap-1.xml, ...) will be generated and uploaded to a new S3 bucket, `sitemaps.pubpub.org`. The new bucket structure looks like:
```
sitemaps.pubpub.org
dev/
1acefbd-99ecba-301dbe-ffc9ae/
sitemap-index.xml
sitemap-0.xml
...
prod/
...
```
Where dev and prod directories correspond to the application environment, and the hash …
=> feature: sitemap index and dynamic robots.txt

client/components/Header/Header.js, client/containers/App/Breadcrumbs/Breadcrumbs.js, server/collection/queries.js, server/pub/__tests__/api.test.js, server/pub/api.js, server/pub/permissions.js, server/pub/queries.js, server/pubEdge/api.js
Here we fix some permissions problems with the Pub API, and add some tests to assess this issue.
_Test plan:_
- Ensure you can create a Pub from the global header
- Ensure you can create a Pub from both the Community and Collection dashboards, and that the Pub is inserted into the appropriate scope.
- `npm run test server/pub/`
=> fix: Update Pub API and add tests

client/components/LengthIndicator/LengthIndicator.js, client/components/LengthIndicator/lengthIndicator.scss, client/components/index.js, client/containers/Pub/PubHeader/EditableHeaderText.js, client/containers/Pub/PubHeader/TitleGroup.js, client/containers/Pub/PubHeader/editableHeaderText.scss
This PR adds a new component LengthIndicator which shows a simple counter where the numerator is the current length of a text input and the denominator is the maximum acceptable length. By default the component will show after the current length is greater than or equal to 90% of the maximum length.
In addition, this PR adds a maximum length of 280 to the Pub description field (in TitleGroup.js) to prevent unwanted truncation of long descriptions.
Closes #920 
**Test Plan**
1. Create a new Pub
2. Enter some text that approaches 200 or more letters. Eventually you should see the length indicator pop up (at 90% of the maximum 280 length).
3. When you reach 280 characters, the text should turn red.
4. You should be unable to enter more than 280 characters in the Pub description field.
=> fix: add max length to pub description to prevent truncation

client/containers/App/SideMenu/SideMenu.tsx, utils/dashboard.ts
Fixes #1008 
**Test Plan**
- Open the dashboard of a Collection.
- The Impact tab should not be visible.
- Ensure the Impact tab is still visible for Pubs and Communities.
=> fix: exclude collection scope from impact tab

client/components/AssignDoi/AssignDoi.tsx, client/containers/App/SideMenu/SideMenu.tsx, client/containers/DashboardOverview/PubOverview/PubOverview.tsx, client/containers/DashboardReviews/DashboardReviews.tsx, client/containers/Pub/PubHeader/Download.tsx, workers/tasks/export/html.js
This implements a series of small string changes that have been requested by our users over the last few weeks.
Previously, the downloads dropdown would say "Downloads" if no Formatted download was present, but "Auto Generated Downloads" if a Formatted download was present. This caused some confusion about what was and was not auto-generated.
_Test plan_
- Visit a pub with no formatted download, verify that the dropdown says "auto generated download"
- Visit a pub with a formatted download, verify that the dropdown says "auto generated download"
With guidance from MITP, we've added a disclaimer to the non-PDF and HTML export types to clarify that the export is auto-generated and may contain slight errors. We feel confident enough about PDF and HTML export proofing that we haven't added …
=> update: Download, deposit, and review string changes

.jest/setup-env.js, client/containers/Page/LayoutBanner.tsx, package-lock.json, package.json, server/pub/__tests__/api.test.js, server/pub/api.js, server/pub/permissions.js, server/pub/queries.js, server/pub/tokens.js, server/utils/__tests__/tokens.test.js, server/utils/queryHelpers/pageGet.js, server/utils/tokens.js
This PR re-enables a couple of ways that non-Members can create Pubs that I inadvertently disabled in #1001  
- The global header's Create Pub button when shown to non-Members
- A Page banner block with a Pub creation button enabled (which I only learned about this week!)
Previously these were permitted because there was no permission gating on Pub creation. Re-enabling the global header button is as easy as checking `hideCreatePubButton` on a Community (though this field should be renamed). Enabling this for Page banner blocks proved a little trickier since the permission exists by virtue of the visitor being able to see the Page — ultimately, I went with an approach where we issue expiring JSON web tokens to users visiting Pages with these banner blocks, allowing them to create Pubs. …
=> fix: Shore up guest Pub creation mechanisms

server/utils/queryHelpers/communitySanitize.js
This PR updates page sanitation logic to also include collection pages (even when they are private) in page results when the requesting user has collection-level manage permission.
_Test Plan_
* Link a private page to a collection.
* Log in to a user with community-level view or edit permissions (without any collection permissions).
* The page should not be visible in the nav bar.
* Assign the user collection-level view or edit permissions.
* The page should still not be visible in the nav bar.
* Assign the user manage permissions.
* The page should now be visible in the nav bar, and clicking on the link should take you to the private page.
=> update: include pages where user is collection manager

server/utils/queryHelpers/communitySanitize.js
This PR removes the predicate that you must be a manager or admin of a collection to see its private pages. This means that anyone with explicit collection-level permissions can see a private page linked to that collection, regardless of their access level (i.e. view and above).
=> feature: show private collection pages to users with explicit collection-level permission

client/components/Editor/Editor.tsx, client/components/Editor/plugins/reactive.ts, client/components/Editor/plugins/table.ts, client/components/Editor/schemas/audio.ts, client/components/Editor/schemas/equation.tsx, client/components/Editor/schemas/image.ts, client/components/Editor/schemas/reactive/label.ts, client/components/Editor/schemas/reference.ts, client/components/Editor/schemas/table.ts, client/components/Editor/schemas/video.ts, client/components/Editor/styles/latex.scss, client/components/Editor/styles/table.scss, client/components/Editor/utils/references.ts, client/components/Editor/utils/renderStatic.ts, client/components/Editor/views/ReferenceView.ts, client/components/Editor/views/index.ts, client/components/FormattingBar/controlComponents/ControlsReference.tsx, client/containers/DashboardOverview/CollectionOverview/CollectionControls.tsx, client/containers/Pub/PubDocument/PubBody.tsx, client/containers/Pub/PubSyncManager.tsx
This PR adds automatic labeling of audio, video, images, equations, and tables. The labels aren't customizable yet, but this code adds a hook into the labeling logic via the `blockNames` object injected via document state.
=> feature: add automatic labeling of media, equations, and tables

client/components/Byline/Byline.tsx, client/components/Byline/bylineStories.tsx, client/components/PreviewImage/PreviewImage.tsx, client/components/PubByline/PubByline.tsx, client/components/PubEdge/PubEdge.tsx, client/components/PubEdge/PubEdgePlaceholderThumbnail.tsx, client/components/PubEdgeListing/PubEdgeListingCard.tsx, client/components/PubMenuItem/PubMenuItem.tsx, client/components/PubPreview/ManyAuthorsByline.tsx, client/components/PubPreview/PubPreviewEdges.tsx, client/containers/DashboardEdges/DashboardEdges.tsx, client/containers/DashboardEdges/NewEdgeEditor.tsx, client/containers/DashboardEdges/NewEdgeInput.tsx, client/containers/DashboardOverview/CollectionOverview/PubSelect.tsx, client/containers/Pub/PubHeader/TitleGroup.tsx
Resolves #1005
This PR updates Pub Connections cards to only show authors of a Pub, rather than all of its contributors. I also fixed a related problem where non-author contributors would be shown in the dropdown used to select connected Pubs.
_Test plan:_
Create a Pub with author and non-author contributors and verify that only the authors are shown in a PubEdge card pointing towards that Pub.
=> feature: Only show author contributors in PubEdge

server/routes/index.js, server/routes/pubDownloads.js
Resolves #1027 
This PR adds a new `/pub/:slug/download` route that directly downloads (using `Content-Disposition: attachment`):
- The formatted download for a Pub, if it exists
- The latest automatically generated PDF export for the Pub's latest release, otherwise
throwing a 404 if neither is available.
_Test plan:_
Verify that `/download` downloads the formatted download for a Pub if it exists, or the latest public PDF export if it exists, and otherwise produces a 404. Pubs with no Releases should likewise produce a 404.
=> feature: Add route to directly access 'best' Pub download

client/containers/Page/page.scss
This small change makes the wrapper for HTML blocks `position: relative` so that we can position elements absolutely within them.
=> update: support position: absolute within HTML page blocks

.eslintrc, client/components/FileUploadButton/FileUploadButton.tsx, client/containers/DashboardSettings/PubSettings/DownloadChooser.tsx, client/containers/DashboardSettings/PubSettings/downloadChooser.scss
Resolves #797 
The "formatted download" is the (typically PDF) file that we allow users to associate with their Pubs to be downloaded for offline reading. Currently there is a way to add a file to act as this download, but no way to remove it. Until now:
Of note in this change is that `Pub.downloads` is actually an array of files, and this change causes _all_ the contents to be overwritten when the download is removed. I think this is a vestige of a more feature-rich use of `downloads,` and can be safely ignored, since only one download is currently made available to users at this time anyway. But @isTravis please validate or correct this assumption!
_Test plan:_
Visit the Settings for a Pub and verify that you can add, remove, and download files as formatted downloads.
=> feature: Enable removal of formatted download

server/routes/pubDocument.js, server/routes/pubDownloads.js, server/utils/ssr.js, utils/canonicalUrls.js, utils/pub/downloads.js, utils/pub/metadata.js
Actually resolves #1027 
...so that archival services and indexes can link to PubPub or third-party domain URLs rather than `assets.pubpub` ones.
This PR adds the `/pub/:slug/download/:format` route to complement `/pub/:slug/download`. The former will only resolve files of the type `format`. The latter will resolve any formatted download, defaulting to PDF when selecting among the auto-generated exports. Then, `https://<domain>/pub/:slug/download/pdf` is set as the `citation_pdf_url` meta tag value.
_Test plan:_
- `/pub/:slug/download` still works as before, resolving _any_ formatted download or a PDF export
- `/pub/:slug/download/:format` will return a file of type `format`, preferrably a formatted download, but otherwise an export.
- Pubs have a `citation_pdf_url` meta tag linking to …
=> update: Use the PubPub-internal download URL in the citation_pdf_url meta tag

client/containers/Pub/PubDocument/PubHistoricalNotice.tsx, client/containers/Pub/PubDocument/pubHistoricalNotice.scss
It had a null property access on `release.noteText`, but I streamlined/deduped a few calculations. The diff is kind of ugly, sorry. I also changed the border-radius on the little VIEWING/LATEST things 'cause I couldn't resist :^)
_Test plan:_
I ran `PUBPUB_PRODUCTION=true PUBPUB_LOCAL_COMMUNITY=kfg-notes npm start` and then navigated to [an older release of a Pub we spotted issues with in prod](http://localhost:9876/pub/pubpub-roadmap/release/17). I verified that all of the release numbers, dates, and links in the notice and the changelog appear correct.
=> fix PubHistoricalNotice

server/routes/dashboardPage.js, server/routes/page.js, server/utils/queryHelpers/layout.js, server/utils/queryHelpers/pageGet.js
A few weeks(?) back I wrote a bit of code to do more performant Page loading by only fetching the Pubs that are actually needed to render the Page. Because it was late and I wasn't sure whether the code really worked, I scoped it to a specific community that was suffering from degraded homepage performance due to a large number of Pubs.
This PR enables that code for all communities. It has a few differences:
- Variable names changed to reference "layouts" as a nod to our upcoming Collections work, and Collection-Page layout functionality broken into a new `layout.js` in `queryHelpers`
- A few bugs are fixed: the Page editor will still load all Pubs in a community (as it must) and we will never send more than one copy of a Pub down to the client.
_Test plan:_
Create [a …
=> update: More performant Page layout loading

client/components/NavBar/NavBar.tsx, client/containers/DashboardSettings/CommunitySettings.tsx, client/containers/DashboardSettings/NavBuilder.tsx, client/containers/DashboardSettings/NavBuilderList.tsx, client/containers/DashboardSettings/NavBuilderRow.tsx, client/containers/DashboardSettings/PageCollectionAutocomplete.tsx, client/containers/DashboardSettings/navBuilder.scss, client/containers/DashboardSettings/navBuilderContext.ts, client/utils/__tests__/navigation.test.ts, client/utils/navigation.ts, server/community/queries.js, server/page/queries.js
More progress on #1058 
Since Collections will no longer by represented by linked Pages, we need a way to add them to the Community navigation. This PR does that, with a new "Add Collection" dropdown joining the "Add Page" one.
There are quite a few weird TypeScript casts in here to deal with the fact that a `CommunityNavigationEntry` can be a `string` right now (representing a Page ID). Once I have migrated all of those to objects, we can remove these casts, and I've left some TODOs reminding me where to do that.
_Test plan:_
In the demo community, verify that you can add and remove Pages, Collections, links, and submenus without crashing the editor, and that any changes are persisted. Create a new Community and verify that it has a valid `navigation` field.
=> feature: Allow adding Collections to Community nav

client/containers/DashboardSettings/PubSettings/CitationChooser.tsx, client/containers/Pub/PubHeader/CitationsModal.tsx, client/containers/Pub/PubHeader/CitationsPreview.tsx, server/utils/citations/generateCitationHtml.js, server/utils/citations/structuredCitations.js, utils/citations.ts, utils/crossref/__tests__/data/pub.js, utils/storybook/data/dataPub.js
Resolves #1075 
- Adds "default" citation HTML to the enriched pub object and displays that in the cite menu rather than always defaulting to APA.
- Refactors how we generate both pub citations (in the cite menu) and inline citations slightly by moving the list of supported citations into a shared util consumed by both
- Updates the citation 'more options' modal to show the default citation along with the most common ones (labeling the common one as default if it exists)
- Modifies generateCiteHtml to fall back to a collection-level DOI if there is no DOI for the pub itself but there is for the collection.
_Test plan_
General cites:
1. Visit a pub, add some inline cites in various formats (doi, bibtex, etc.)
1. Make sure they display properly
1. Make sure the pub cite displays properly
1. …
=> update: Use Pub citation style preference for Pub cite

client/components/Editor/Editor.tsx, client/components/Editor/plugins/onChange.ts, client/components/Editor/schemas/audio.ts, client/components/Editor/schemas/equation.tsx, client/components/Editor/schemas/image.ts, client/components/Editor/schemas/reactive/counter.ts, client/components/Editor/schemas/table.ts, client/components/Editor/schemas/video.ts, client/components/Editor/utils/references.ts, client/components/Editor/utils/selection.ts, client/components/FormattingBar/controlComponents/ControlsEquation.tsx, client/components/FormattingBar/controlComponents/ControlsMedia/ControlsMedia.tsx, client/components/FormattingBar/controlComponents/ControlsTable.tsx
This PR adds the ability to toggle labeling of specific nodes via the editor controls of block equations, media, and tables. Hiding the label of a node should decrement the counter on labels of subsequent, labeled nodes. Nodes with hidden labels will no longer be referenceable, and any existing references will fall back to the **(ref?)** placeholder.
I also snuck in a change to group nodes with shared custom labels into the same reactive counter state. e.g. if both images and audio are labeled "Figure", they will share the same list of potential counter values.
_Screenshots_
Standard block editor controls
Table controls
_Test Plan_
1. Create a Pub and enable labeling of images and tables.
2. Update the custom of images and tables to "Figure".
3. Add an image and a table to the Pub.
4. …
=> update: toggle referencing of media, equations, and tables

client/components/FormattingBar/media/Media.tsx, client/components/FormattingBar/media/MediaTwitter.tsx, client/utils/editor.ts, server/editor/api.js
Someone recently asked for better social embedding. It turns out Twitter has recently updated their [oembed](https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview) [capabilities](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview) to make this quite easy, so, I went ahead and added it. Because Twitter returns "rich" oembeds (ie, not iFrames), it uses the same "hack" as Gists, encoding the html and using a data uri to render it into the iFrame. (As a sidenote, I think we should eventually use this approach – well, in fact, srcdoc because we won't be able to validate the content – to allow people to create arbitrary embeds of html code of their choosing. But that needs a bit more work).
_Test Plan_
1. Embed a Tweet (e.g. …
=> new: Twitter embed

client/components/Editor/ReferenceFinder.tsx, client/components/FormattingBar/FormattingBar.tsx, client/components/FormattingBar/FormattingBarButton.tsx, client/components/FormattingBar/FormattingBarMediaButton.tsx, client/components/FormattingBar/buttons.tsx, client/components/FormattingBar/controlComponents/ControlsEquation.tsx, client/components/FormattingBar/controlComponents/ControlsMedia/ControlsMedia.tsx, client/components/FormattingBar/controlComponents/ControlsReference.tsx, client/components/FormattingBar/controlComponents/controlsReference.scss, client/components/FormattingBar/types.ts, client/components/FormattingBar/utils.ts, client/components/ReferencesDropdown/ReferencesDropdown.tsx, client/components/SettingsSection/SettingsSection.tsx, client/components/SettingsSection/settingsSection.scss, client/containers/DashboardSettings/PubSettings/PubSettings.tsx, client/containers/Pub/PubSyncManager.tsx, client/types/editor.ts, package-lock.json, utils/dashboard.ts, utils/workers/constants.js, workers/tasks/import/rules.js
This PR improves Pub internal references with the following enhancements:
- The references button is disabled when the Pub has no block nodes enabled for labeling.
- When disabled, the button will show a tooltip that contains a link to the references section of the Pub settings.
- The "Hide label" options in node formatting controls is now disabled instead of hidden when referencing is not allowed.
- Each of the "hide label" buttons now shows the same message from the tooltip to help guide the user to Pub settings.
Tooltip:
Disabled "Hide Label" checkbox:
I'm not 100% happy with how the hide label checkbox text came out, but it was the most straightforward way I could come up with using Blueprint's `<Checkbox>` component. I'm looking for some feedback (paging @djagdish) on both the …
=> update: references feature discoverability and conditional disabling

client/components/Layout/Layout.tsx, client/components/Layout/LayoutPubs.tsx, client/components/PubPreview/PubPreview.tsx, client/containers/Pub/PubDocument/PubBottom/ReadNextSection.tsx, client/containers/Pub/PubHeader/collections/CollectionBrowser.tsx, client/utils/collections.ts
We want to ensure that when a Pub in a Collection layout is clicked, that Pub is loaded in the context of that Collection, meaning it will be shown prominently in the Pub Header and used for Read Next. We accomplish that with the `readingCollection` URL parameter. This PR adds that param where appropriate to links in Pubs blocks in Collection layouts.
_Test plan:_
- Visit a Collection layout and ensure that the `readingCollection` param is specified on Pub hrefs as expected.
- Visit a Page layout and a User profile and ensure the PubPreviews in those views still work.
=> update: Add the readingCollection URL param to Collection layout PubPreviews

server/routes/collection.js
Quick fix to prevent the collection route handler from resolving a collection via partial ID when the pattern is `{community root}/:slug`
=> fix: dont attempt to resolve collection via /:slug route pattern

client/components/Editor/plugins/table.ts, client/components/Editor/schemas/table.ts, client/components/Editor/utils/renderStatic.ts, client/components/FormattingBar/controlComponents/ControlsTable.tsx, package-lock.json, package.json, workers/tasks/export/styles/printDocument.scss
Resolves #1128 
This PR fixes two issues related to tables in Prosemirror:
- Tables are not appearing in exports
- Table resizing doesn't work
A lot of the core of what fixes these issues is accounted for in the version bump of `prosemirror-reactive`.
_Test plan:_
- Create tables in a new Pub. Verify that they are labeled correctly and that columns can be resized. Verify that the various table commands accessible from the inline context menu work as expected.
- Export the Pub to HTML and verify that the tables appear.
=> fix: Tables in exports and column resizing

server/collectionPub/__tests__/api.test.js, server/collectionPub/api.js, server/collectionPub/model.js, server/collectionPub/permissions.js, server/collectionPub/queries.js, stubstub/modelize/builders.js, tools/migrate.js, tools/migrations/2020_10_27_addPubRanks.js, tools/migrations/2020_10_27_backfillPubRanks.js
This is the first bit of work to remove `isPrimary` from CollectionPubs and replace it with a ranking-based scheme to determine which Collection should be used in which contexts. Just as the model has a `rank` field that determines its order with respect to its Collection, it will now also have `pubRank` which determines its importance to the Pub.
All this PR does is add the field to the db schema, updates the `createCollectionPub` helper function, and provides a data migration to backfill `pubRanks`: currently-primary CollectionPubs appear earliest in a Pub's list, and the rest are sorted by creation date.
_Test plan:_
Run the CollectionPub unit tests:
```
npm run test-dev server/collectionPub
```
=> dev: Add pubRanks to CollectionPubs

client/containers/DashboardSettings/CollectionSettings/CollectionMetadataEditor.tsx, client/containers/DashboardSettings/CollectionSettings/collectionMetadataEditor.scss
Closes #988 
This PR removes the existing "Assign DOI" button from the collection settings DOI field and adds a new button to the bottom of the form. The new button behaves similarly to the old one by assigning a DOI when it is clicked for the first time, but also allows the collection to be deposited again.
=> update: allow re-depositing of collections

client/components/PubEdge/PubEdge.tsx, client/components/PubEdge/PubEdgeEditor.tsx, client/components/PubEdge/util.ts, client/components/PubEdgeListing/PubEdgeListing.tsx, client/components/PubEdgeListing/PubEdgeListingCard.tsx, utils/arrays.js, utils/pubEdge/helpers.ts, utils/pubEdge/index.js
Folks are using Pub Connections to build some real complicated "I'm my Own Grandpa" kinds of non-tree graphs between their Pubs, with the result that Pubs can appear more than once in the `PubEdgeListing` of a Pub as a parent, child, or sibling by multiple different parents. No matter what, we really want to make sure that every Pub only appears once in this listing — so that's what this PR does.
_Test plan:_
I ran 
```
PUBPUB_LOCAL_COMMUNITY=hdsr PUBPUB_PRODUCTION=true npm start
```
and then visited [this Pub](http://localhost:9876/pub/cqncbp3l/release/3), verifying that there are no duplicates in its connections listing. I'll probably want to check about a dozen other Pubs, too.
=> fix: Only show a given Pub once in a PubEdgeListing

client/components/Editor/schemas/image.ts, client/components/Editor/styles/figure.scss, client/components/Editor/utils/index.ts, client/components/Editor/utils/media.ts, client/components/FormattingBar/controlComponents/ControlsMedia/ControlsMedia.tsx, client/components/FormattingBar/controlComponents/controls.scss, client/components/FormattingBar/media/MediaImage.tsx, client/utils/upload.ts
Resolves #1161 
This PR adds (restores?) support for gif and webp images by not passing them through the resizer. We also add a new control for other resizable image formats (jpg, png, did I miss any?) to allow them to skip the resizer as well, so that anyone who really wants a high-resolution image in their Pub can add one.
_New "full resolution" checkbox in `ControlsMedia`:_
_Test plan:_
- Add .gif and .webp files to a Pub and verify that they load correctly and the "full resolution" checkbox is hidden for them. 
- Add a .jpg and verify that it loads and that you can choose whether to resize it or not with the checkbox.
- Add a video and verify that the `ControlsMedia` works for it and the checkbox is hidden
- Check an existing image on an older Pub and verify that it loads.
[Here is a …
=> feature: Full-resolution image support (including .gif and .webp)

client/components/AssignDoi/AssignDoiPreview.tsx
This PR adds journal issue (collection) information to the human-readable DOI deposit preview.
_Test Plan_
* Preview the deposit for an article that belongs to an Issue collection.
* Ensure the collection name and publication date appear in the deposit preview.
=> update: render journal issue in DOI deposit

server/release/__tests__/api.test.js, server/release/model.js, server/release/queries.js, stubstub/modelize/builders.js, tools/migrations/2020_12_02_addReleaseHistoryKey.js, tools/migrations/data/2020_12_02_addReleaseHistoryKeys.js, tools/migrations/util/index.js
In order to eliminate Merges and treat Releases as simple pointers into a Pub draft, we need to be very sure which key of the draft a given Release points to. Our current understanding of that is surprisingly shaky — we have some Releases that don't correspond to a draft, some missing `branchKey` or `sourceBranchKey` fields that hint at the source of the Release, and some that appear to be duplicates of each other. In practice, when we load `/pub/:slug/release/:x` we just grab the `x-1`th merge without any regard for what Release it "actually" corresponds to, which gets us into trouble sometimes because database Release objects and Firebase merges aren't created atomically with each other during the release process, and sometimes we end up with one but not the other.
This PR contains:
- …
=> dev: Add a historyKey to every Release

package.json, workers/tasks/import/images.ts, workers/tasks/import/resources.ts, workers/tasks/import/util.ts
Resolves #1184 (I hope)
This PR enables the importer to ingest referenced image files with spaces in their names.
_Test plan:_
I created a file like this:
```
```
and verified that both of the related images were converted to PNG and added to the Pub.
=> fix: Permit spaces in Pandoc-imported filenames

client/containers/Pub/Pub.tsx
This is a band-aid fix for #1170 and #1171. This code simply executes a function 500ms after a Pub loads before scrolling to the element who's id is `window.location.hash`, only if that element is not already in the viewport.
=> fix: correctly scroll linked element on Pub load

client/containers/Pricing/Pricing.tsx, client/containers/Pricing/pricing.scss
This PR has a couple small CSS updates to:
- Simplify the CSS code
- Make paragraph font sizes consistent
- Simplify margin spacing
I made the DOI asterisk text the same size as other paragraph text because it felt too small for accessibility reasons. I could see us making it a lighter color if we wanted to de-emphasize it still.
=> update: Small css simplifications

client/components/Editor/utils/branches.ts, server/doc/queries.ts, server/release/__tests__/api.test.ts, server/release/model.ts, server/release/queries.ts, stubstub/modelize/builders.js, tools/migrations/2020_12_14_addReleaseDoc.js, tools/migrations/2020_12_14_makeReleaseDocNonNull.js, tools/migrations/data/2020_12_14_backfillReleaseDocs.js
This is the thing that's kind of at the heart of our plan to move Releases to Postgres — here, we store the Pub content in a Doc associated with every Release. We're not _reading_ from them, yet, though — that will be a much more complicated set of changes that we'll have to host in parallel with the existing Firebase code for a bit until it's clear that it works. For now we'll just get the codebase in the habit of storing Docs, and run a migration to backfill Docs for existing Releases.
_Test plan:_
Run `npm run test-dev server/releases`
=> update: Create Doc model for each Release

client/components/Editor/styles/file.scss
Fixes an issue brought to our attention by @pkgw that caused long file names to overflow the download card and push the download button out of it. This still causes some awkwardness for file names with underscores or dashes, since that's not technically a CSS break character, but it's better than the name overflowing the card.
_Test plan_
1. Upload a file with a really long name (look here's one: 
[A File With A Bizzarely Long Name That Is Really Too Long Why Is It This Long.txt](https://github.com/pubpub/pubpub/files/5704392/A.File.With.A.Bizzarely.Long.Name.That.Is.Really.Too.Long.Why.Is.It.This.Long.txt)
). 
1. Make sure the name breaks rather than overflowing the card.
=> fix: Wrap long file names in download cards

client/components/FormattingBar/controlComponents/ControlsLink.tsx, client/containers/Pub/Pub.tsx
Fixes #1171
Clicking on internal URLs (with hashes) within a Pub will scroll to the correct element, but the browser doesn't account for the sticky pub header, so the top of the element isn't visible. This PR overrides the default scroll behavior of hash links and scrolls to the element with a 50px offset so the entire element is visible. In addition, code was added to automatically convert internal links to hashes when pasted into the URL field in the anchor controls.
_Test Plan_
- In a Pub with enough content to scroll
- Copy a link towards the bottom of the Pub using the click-to-copy button
- Create a link at the top of the Pub and paste the URL in. The URL's host and path should automatically be removed, leaving only the hash.
- Publish the Pub.
- Click on the link in the release …
=> fix: scroll to top of element and account for sticky pub header

client/components/Editor/plugins/table.ts, package-lock.json, package.json
Earlier this morning I made a change to `prosemirror-reactive` that cause reactive NodeView wrappers to return the value of `update()` provided from the NodeViews they wrap. This fixes behavior in highly stateful NodeViews like resizable tables, but breaks out table labeling code in our custom TableView subclass.
The fix has two parts:
1. In `prosemirror-reactive`, make sure wrapped NodeViews always receive a reactive copy to their update method. (See https://github.com/pubpub/prosemirror-reactive/commit/026d6135f5b2b3682cc47ba506679a80a308e56b)
2. In our Table view, call `syncCaption` from `update`. Don't forget to remove `caption` nodes left over from previous calls.
All I can say is...thank god for React.
=> fix: sync Prosemirror table captions in update() method of NodeView

client/containers/DashboardSettings/NavBuilder.tsx, client/containers/DashboardSettings/NavBuilderRow.tsx, client/utils/__tests__/navigation.test.ts, client/utils/navigation.ts
I was clicking around this morning and found that to my horror I forgot to remove some shim code from the Page/Collection migration. So I'm doing it now. To make sure there really are no bare strings IDs left in the community nav JSON I tried this in the devshell:
```
cms = await Community.findAll();
const isProblematicNavEntry = entry => typeof entry === 'string' || entry.children && entry.children.some(isProblematicNavEntry);
const isProblematicNav = nav => nav.some(isProblematicNavEntry);
cms.filter(c => isProblematicNav(c.navigation)); // []
```
I'll still do some spot-checking on duqduq before deploying.
=> dev: Some TS cleanup for Community Navigation code

client/components/Editor/schemas/audio.ts, client/components/Editor/schemas/iframe.ts, client/components/Editor/schemas/image.ts, client/components/Editor/schemas/video.ts, client/components/FormattingBar/controlComponents/ControlsMedia/ControlsMedia.tsx, client/components/FormattingBar/controlComponents/controls.scss, client/components/FormattingBar/formattingBar.scss, client/components/FormattingBar/usePendingAttrs.ts
Resolves #1208
Our current attempt at screenreader support for images and other captionable media has been to use a `figure`/`figcaption` pair, which should cause the `figcaption` contents to be read in a way similar to an image's alt text. As described in #1208, Gabe (and a Twitter user) found that this is not actually the case for many OS/reader/browser combinations. So this PR has two changes:
- We add an `aria-describedby` (or occasionally `aria-labelledby`) to `img`, `video`, `audio`, `iframe` tags that points at the `figcaption`, to improve the odds of the caption being associated with the media by the SR.
- For instances where SR users would benefit from more detail than is appropriate for a caption, we add an `altText` field to the image node schema, and a corresponding control to …
=> feature: Add support for image alt text and improve a11y of figcaptions

client/components/Editor/Editor.stories.tsx, client/components/Editor/Editor.tsx, client/components/Editor/ReferenceFinder.tsx, client/components/Editor/clientServerDiffStories.tsx, client/components/Editor/hooks/useEditorView.ts, client/components/Editor/hooks/useInitialValues.ts, client/components/Editor/hooks/useSuggestions.ts, client/components/Editor/plugins/collaborative/document.ts, client/components/Editor/plugins/collaborative/index.ts, client/components/Editor/plugins/index.ts, client/components/Editor/plugins/onChange.ts, client/components/Editor/plugins/placeholder.ts, client/components/Editor/types.ts, client/components/Editor/utils/doc.ts, client/components/Editor/utils/renderStatic.ts, client/components/FormattingBar/FormattingBar.stories.tsx, client/components/LayoutEditor/LayoutEditorText.tsx, client/components/MinimalEditor/MinimalEditor.tsx, client/components/ThreadInput/ThreadInput.tsx, client/containers/DashboardOld/DashboardContent/Page/LayoutEditor/LayoutEditorText.tsx, client/containers/Pub/PubDocument/PubBody.tsx, client/containers/Pub/PubDocument/PubDiscussions/Discussion/DiscussionInput.tsx, client/containers/Pub/PubDocument/PubDiscussions/Discussion/ThreadComment.tsx, client/utils/suggestions/suggestionManager.ts, workers/tasks/export/html.tsx
I wanted to make some changes to the editor (in an upcoming PR) but I didn't feel comfortable doing so because the file has gotten a bit too big for its britches, so I decided to split it out into a few smaller files. There's no big rethink of how things work here and there should be _almost_ no behavioral changes — just smaller files and more types.
The one thing I _have_ changed here is that the a couple of the editor props — specifically `onError`, `onKeypress`, `onScrollToSelection`, and `isReadOnly` now follow the React model and update when the props update. We accomplish this by calling `editorView.setProps` within a set of `useEffect` hooks. One consequence of this is that the callbacks passed in here should be memoized using `useCallback`, which is good practice anyway. In the …
=> dev: Split Editor.tsx into more files and add stronger typing

client/components/Footer/Footer.tsx, client/containers/Landing/Landing.tsx, package-lock.json
Updates the landing page to include the roadmap and discussion forum in two places. The "open source" section, which has been modified to add other parts of our open source communities, not just repos:
And the www footer, which now includes a link to the forum:
_Test plan_
Click all the links.
=> update: Include forum and roadmap on landing page

utils/pub/metadata.js
Hotfix fix for issue brought up in #2856 (freshdesk). We were not checking for existence of the date-part object before trying to access it by key, causing a 500. This simply checks for existence. The longterm fix is to use typescript.
This also adds a check for the existence of `author.literal`, and uses that if it exists rather than `author.first author.last,` as I noticed in my debugging that two citations in the doc used author.literal rather than first and last. I've verified in the citejs spec that it will always send one or the other, not both.
_To test_
1. Visit https://idmil.pubpub.org/pub/9w8wo2j1/draft on local (prod env) and verify it loads
2. Visit articles that use citations and verify that the google scholar tags show up correctly (easiest way to do this is to load zotero …
=> hotfix: Check for existence of date-parts in google scholar meta tags

server/routes/robots.ts, server/server.ts
`robots.ts` was not properly returning a `res` for `www.pubpub.org`, which would cause the request to never resolve and simply hang. It resulted in requests to `/robots.txt` hanging indefinitely (this may be the cause for all those Heroku timeout errors).
This PR refactors the code a bit in addition to applying the fix. It also removes the deprecated static serving line for `robots.txt` that was in `server.js`.
_Test Plan:_
- Try to access `/robots.txt` from a community and verify that it returns with the sitemap URL detail.
- Try to access `/robots.txt` from the base `www` subdomain and verify that it returns without the sitemap URL detail.
=> fix: robots.txt was not resolving on www.pubpub.org 

client/containers/Pub/PubDocument/PubFileImport/FileImportDialog.tsx, workers/tasks/import/import.ts
Improves PubPub's import UX to show Pandoc warnings when importing LaTeX documents. This is helpful because it shows the places where Pandoc has had to skip or modify LaTeX functions to successfully import the document, making it easier for production teams to understand why and how they'll need to fix errors introduced due to the unavoidable incompatibilities of the LateX schema, the pandoc schema, and PubPub's prosemirror schema.
I've tried to keep this incredibly simple, with the understanding that at some point we might want to parse these messages to show more info or give an indication of severity, but my sense is we actually won't quite know how to do that until we get more user feedback on the feature, and that this additional info, combined with a link to our new [help …
=> new: Show pandoc warnings when importing LaTeX

client/containers/Pub/PubHeader/PubHeaderSticky.tsx, client/containers/Pub/PubHeader/PubToc.tsx, client/containers/Pub/PubHeader/UtilityButtons.tsx, client/containers/Pub/PubHeader/pubToc.scss
Resolves #1241
Some very long Pubs like [this one](https://openscientist.pubpub.org/pub/play/) have tables of contents which overflow from the `PubHeaderSticky` which appears below the fold, making it impossible to select its lower elements. This PR fixes that.
_Before:_
_After:_
_Test plan:_
Visit a Pub with a loooong TOC. I ran:
```
PUBPUB_PRODUCTION=true PUBPUB_LOCAL_COMMUNITY=openscientist
```
and then navigated to localhost:9876/pub/play. I observed that I was able to scroll the `PubHeaderSticky` TOC (the one in the Pub header itself remains unchanged)
=> fix: Allow long sticky TOC to scroll

client/components/Editor/plugins/discussions/decorations.ts, client/components/Editor/plugins/discussions/index.ts, client/components/Editor/plugins/discussions/plugin.ts, client/components/Editor/plugins/discussions/types.ts, client/containers/Pub/PubDocument/PubBottom/Discussions/DiscussionsSection.tsx, client/containers/Pub/PubDocument/PubDiscussions/discussionUtils.ts
Resolves #1179
This PR fixes this thing:
(Relatedly, I found a weird issue where collapsing the Pub-bottom discussions section hides all anchored discussions in the Pub — which makes sense based on how it's implemented, but we should fix it)
_Test plan:_
Visit a couple of Pubs on draft and Release with anchored Discussions and verify that this toggle works.
=> fix: Fix the 'Show anchored comments' toggle

client/containers/DashboardSettings/PubSettings/Doi.tsx
Adds a settings page warning for the case where a Pub has a DOI assigned, and is released, but has never been submitted to Crossref (this only happens in communities with their own Crossref prefix). Currently, the released UI displays the DOI, and the Settings page displays DOI submission but no warning, which can lead to confusion about why the DOI isn't resolving. (Yes, a better eventual solution to this is to make depositing part of the release flow).
It also adds a success intent to the update suffix button to indicate that this action is permanent (whereas merely generating a suffix does not save it).
_Test Plan_
1. Visit a duqduq community with a custom prefix
2. Create a new pub
3. In settings, generate a suffix (or add a custom one)
4. Warning should show.
=> update: Add warning if Pub is assigned DOI and released but not submitted to Crossref

client/components/Avatar/Avatar.tsx, client/components/CommunityPreview/CommunityPreview.tsx, client/components/Header/Header.tsx, client/components/Layout/LayoutBanner.tsx, client/components/Layout/LayoutText.tsx, client/components/LayoutEditor/LayoutEditorBanner.tsx, client/components/LayoutEditor/LayoutEditorText.tsx, client/components/PagePreview/PagePreview.tsx, client/components/PreviewImage/PreviewImage.tsx, client/components/PubEdge/PubEdge.stories.tsx, client/components/PubPreview/PubPreview.tsx, client/containers/DashboardOld/DashboardContent/Page/LayoutEditor/LayoutEditorText.tsx, client/containers/Search/Search.tsx, utils/images.ts, utils/strings.js
This PR updates our Image Resizer stack to use version [5.2 of the Serverless Image Handler](https://github.com/awslabs/serverless-image-handler) and resolves #1257. 
The new Image Resizer lives as `resizer-v3.pubpub.org` and has a different API given that it's based on [Sharp](https://sharp.pixelplumbing.com/) rather than [Thumbor](http://thumbor.org). I find the documentation and formatting of Sharp much more modern and ergonomic - so that's a plus! The PR refactors the `getImageResizer` function to use the new API and also applies the slight modification to all invocations of `getImageResizer`. The main update is in `utils/images.ts` and most of the other changes are just function call refactors.
I'm hopeful that the more modern library also improves some of the compression issues we …
=> Refactor getResizedUrl function and calls to use new resizer

.gitignore, client/components/Footer/Footer.tsx, client/containers/DashboardSettings/CommunitySettings.tsx, server/community/model.ts, server/community/permissions.ts, tools/migrations/2021_03_16_addCommunityFooterLogoLink.js
Add option to link on footer logo in community settings.
To test: from community settings page, upload a logo image and add a 'Footer Logo Link' value. Save, then click footer logo in the preview.
=> feature: add custom linking to Community footer logo

client/components/Editor/plugins/paste/upload.ts, client/components/Editor/schemas/image.ts, client/components/Editor/utils/media.ts, client/components/FormattingBar/controlComponents/ControlsMedia/ControlsMedia.tsx, client/containers/Pub/PubDocument/PubBody.tsx, utils/images.ts
addresses #1274
Generate a srcset for resized images in pubs to accommodate devices of any pixel density.
Does not address banners and instances where resized images are applied as background-image via css.
_Test plan_
+ In inspector, enable devices of at least two different pixel densities (e.g., Chrome inspector's emulated 'laptop with HiDPI' and 'laptop with MDPI')
+ disable cache in inspector
+ with inspector open and lower DPI device activated, navigate to any pub with an image in pub body
+ note image size in bytes
+ switch emulated device to HiDPI device
+ reload page
+ note + compare image size, HiDPI size should be greater
=> feature: Enable srcset for pub images

client/components/Editor/utils/view.ts, client/containers/Pub/PubDocument/PubDiscussions/Discussion/DiscussionInput.tsx
Comments without text but with an image triggered the 'post button' to be disabled. No longer.
_Test Plan_
create and submit a comment to any pub with an image and no text
=> bug: permit comments with image but no text

client/components/Editor/styles/main.scss, client/containers/Pub/PubDocument/pubBody.scss
We want center-aligned lists to look like this:
```
- a
- b
- c
```
and not like this:
```
-      a
-      b
-      c
```
Our first few attempts:
1. Setting `display: inline-block` on `li > p`. This turned out not to work in Safari, and also created problems with bullet placement on tall `li` elements.
2. Setting `list-style-position: inside` on `ul, ol`. This caused multi-line `li` content to appear on a line beneath the bullet.
Ultimately, the problem is that our Prosemirror schema, all text content is contained within paragraphs, but `ul > li > p` adds an extra box within the list item that we could do without. So, our third attempt: use `display: contents` on `li > p` to remove the `p` from the box model entirely. Here is what this looks like:
Note that the final list item actually …
=> fix: Use display:contents on li > p to fix text-algined lists

client/components/CommunityPreview/CommunityPreview.tsx, client/components/Header/Header.tsx, client/containers/DashboardSettings/CommunitySettings.tsx
Now that the updated resizer gives us some more image options, this PR proposes changing the strategy for resizing header background images from 'inside', which seeks to keep images to a dimension without going over in either width or height (keeping proportionality), to 'outside', which seeks to keep them to a dimension without going under in either width or height (keeping proportionality). By doing so, it drastically improves the quality of already uploaded background images without leading to drastic increases in pageload or major changes to how weirdly sized images are displayed. This doesn't replace doing image-sets (or not using css background images) eventually, but it does make it much more tolerable for now.
I noticed this issue when looking into a bg image for Allison. Right …
=> fix: change banner bg image strategy

client/containers/App/paths.ts, client/containers/DashboardCustomScripts/CustomScriptPanel.tsx, client/containers/DashboardCustomScripts/DashboardCustomScripts.tsx, client/containers/DashboardCustomScripts/customScriptPanel.scss, client/containers/DashboardCustomScripts/dashboardCustomScripts.scss, client/containers/DashboardCustomScripts/types.ts, client/containers/index.ts, package-lock.json, package.json, server/Html.tsx, server/apiRoutes.ts, server/customScript/__tests__/api.test.ts, server/customScript/api.ts, server/customScript/model.ts, server/customScript/permissions.ts, server/customScript/queries.ts, server/models.ts, server/routes/collection.tsx, server/routes/dashboardCustomScripts.tsx, server/routes/index.ts, server/routes/page.tsx, utils/types.ts
Though we're planning to roll this out verrrry slowly, one Community needs this functionality starting next week so I went ahead and added it today. This is a bit of an MVP and we can always revisit some of these design decisions:
- Custom scripts are stored directly in the database and inlined with the request rather than stored as a separate asset in S3. I think we'll probably want to change this.
- We're using the `@monaco-editor/react` editor as a code editor here instead of CodeMirror or something else.
- Right now this is only suitable for use in Communities that we trust. For untrusted Communities we'll need to do some heavy-duty CSS sanitization, and I sort of doubt we'll ever want to turn on custom JS by default.
_Test plan:_
I wrote a few basic tests:
```
npm run test-dev …
```
=> feature: Custom CSS and JS for Communities

server/pub/permissions.ts
Makes the changes @idreyn suggested to simplify license checks.
_Test Plan_
- Make sure any community can use any of the 5 cc-by licenses for a Pub by selecting them all and refreshing and making sure they stick.
- Make sure non-premium communities cannot select the copyright license.
- Make sure a "premium" community (e.g. https://covid-19.mitpress.mit.edu/) can use the Copyright license.
=> fix: add licenseSlug and premiumLicenseFlag checks back

server/pub/queryMany.ts
A quick one to enable searching for Pubs by author name wherever we use `queryMany`, including in the dashboard overview and some assorted Pub selection widgets.
_Test plan:_
- From the Dashboard overview, try searching for Pubs by author name. Test for authors with PubPub accounts as well as "shadow authors" without accounts
- Check on the Pinned Pubs picked to make sure this also works here
=> feature: Query Pubs by author name

client/components/LayoutEditor/LayoutEditorPubs/PinnedPubs.tsx, client/components/PubMenuItem/PubMenuItem.tsx, client/containers/DashboardEdges/DashboardEdges.tsx, client/containers/DashboardEdges/NewEdgeEditor.tsx, client/containers/DashboardEdges/NewEdgeInput.tsx, client/containers/DashboardEdges/newEdgeInput.scss, client/containers/DashboardOverview/CollectionOverview/PubSelect.tsx, client/utils/apiFetch.ts, server/routes/dashboardEdges.tsx
This PR addresses one of the last places where we load all Pubs into scope on the Dashboard: the Connections tab.
_Test plan:_
Visit the Connections tab for a Pub and make sure:
- You can search for a Pub from within the Community and add a Connection
- You can also add a Connection by pasting in an external URL or DOI
Resolves #1358
=> update: Load Connections dashboard tab without all Pubs

client/components/Editor/utils/firebaseDoc.ts
Resolves #1408 (I think)
This definitely fixes a problem, and I believe it's the same problem reported above where Pubs won't load into their history at keys that are multiples of 100. This is happening because we create history checkpoints ever 100 changes, and I conflated the `checkpoints` and `checkpointMap` properties of a Firebase draft...the former has the entire checkpoint while the latter is just a timestamp — essentially I was trying to pull a `number` off of a `number`. Ultimately this sends an undefined timestamp to the client, which crashes when trying to render it as a human-readable date string.
What I don't understand is why this is causing the server to hang instead of just giving us a white screen of death in production — but let's definitely get this onto Heroku and see …
=> fix: Look up timestamp in Firebase from draft checkpoint instead of checkpointMap

client/containers/Pub/usePubNotes.ts, server/utils/citations/structuredCitations.ts, types/pub.ts, utils/notesCore.ts
Resolves #1393 
`NoteManager` currently holds notes in this shape:
```ts
Record<StructuredValue, {structuredValue: StructuredValue, renderedStructuredValue: RenderedStructuredValue}>
```
but the `initialStructuredCitations` it receives from the server has the shape:
```ts
Record<StructuredValue, RenderedStructuredValue>
```
This causes us to call `/api/citation-format` for each of the citations in a Pub when it's loaded. My chosen fix is to change `NoteManager` to use the type provided by `initialStructuredCitation`, since I don't think we're using `note.structuredValue` anywhere in `NoteManager`.
_Test plan:_
Add some citations to a Pub and verify that they render correctly. Then refresh the page and verify that the same citations appear in the document with their rendered values intact, …
=> fix: Match NoteManager state to initialStructuredCitations

workers/tasks/export/styles/printDocument.scss
Resolves #1172 
Resolves #1400
Adds an `.editor` directive to the `figure`s in printDocument.scss styles so that all figures display as flex rather than block. This makes it so that figures (and their captions) never display larger than 800px height, which prevents pagedjs errors caused by unsplittable multi-paged images.
_Test plan_
1. Create a doc with a really tall image and some surrounding text (e.g. http://demo.duqduq.org/pub/zk4hj3js/draft) and make sure the PDF generates with the correct image.
2. For good measure, download a really long Pub with lots of multi-sized images (e.g. https://openscientist.duqduq.org/pub/play/release/2) and make sure that the PDF downloads with all its pages and the images all display well in their different sizes.
Gotchas:
- Forgetting to delete a …
=> fix: add .editor to print styles to prevent display block override

client/utils/activity/renderers/pub.tsx, client/utils/activity/titles/user.ts, server/activityItem/fetch.ts, server/activityItem/model.ts, server/activityItem/queries.ts, server/models.ts, tools/activityItem/backfillCommunity.ts, tools/activityItem/singleCommunityCli.ts, tools/index.js, types/activity/base.ts, types/activity/pub.ts, types/activity/thread.ts, types/util.ts
Resolves #1441
In this PR we add a tool that creates as many `ActivityItems` as can be inferred from the history of a Community. Also note:
- I made the `actorId` property of an `ActivityItem` nullable because it's not possible to infer an actor in many cases here
- There are some changes to some of the `ActivityItem` types and creation queries to best reflect their actual use (for instance, I discovered that not every created Review comes with a ThreadComment).
_Test plan:_
I ran
```
npm run tools backfillCommunityActivity -- --community kfg-notes
```
and observed that it completed, creating about 4,000 items in the database. I did the same thing with `hdsr` for good measure.
=> update: Community ActivityItem backfill tool

client/components/Layout/LayoutPagesCollections.tsx, client/components/Layout/layout.scss, client/components/LayoutEditor/LayoutEditorPagesCollections.tsx, client/components/LayoutEditor/LayoutEditorPubs/LayoutEditorPubs.tsx, client/components/LayoutEditor/layoutEditor.scss, client/components/index.ts, utils/layout/types.ts
Resolves #1459 
This feature allows users to change the alignment of pages and collections in the Collections & Pages Block editor. More selections can be made in regard to justification (see [here](https://css-tricks.com/almanac/properties/j/justify-content/)).
Test plan:
Visit the Pages dashboard of a Community and verify that:
Collections & Pages Block has a Justify Content section
justification can be be changed in the editor
justification setting persist after saving changes by going to the home page
a user that is not logged in also sees the changes
=> feature: Alignment options for Pages & Collections blocks

client/containers/App/App.tsx, client/containers/App/SideMenu/SideMenu.tsx, client/containers/DashboardActivity/ActivityFilters.tsx, client/containers/DashboardActivity/ActivityItemRow.tsx, client/containers/DashboardActivity/DashboardActivity.tsx, client/containers/DashboardActivity/activityFilters.scss, client/containers/DashboardActivity/activityItemRow.scss, client/containers/DashboardActivity/dashboardActivity.scss, client/containers/DashboardActivity/useActivityItems.ts, client/utils/activity/renderers/collection.tsx, client/utils/activity/renderers/itemRenderer.tsx, client/utils/activity/renderers/member.tsx, client/utils/activity/titles/user.ts, client/utils/activity/types.ts, server/activityItem/api.ts, server/activityItem/fetch.ts, server/apiRoutes.ts, server/models.ts, server/routes/dashboardActivity.tsx, server/utils/queryHelpers/scopeGet.ts, types/activity/filters.ts, types/activity/index.ts, types/request.ts, utils/activity.ts, utils/urls.js, utils/urls.ts
Resolves #1443
Resolves #1444
Hey hey at long last, here it is, the Activity tab of the dashboard. This PR gets us pretty far but we still need to do things like:
- Figure out the best way to display times (current format isn't ideal)
- Add mobile support
One fun thing here — I've finally cracked and started to use CSS variables (specifically `--community-accent-dark`) for community specific styles!
_Test plan:_
Visit the Activity dashboard tab for each of a Community (just `kfg-notes` for now), Collection, and Pub, and verify that:
- Activity items render
- Links work
- Lazy-loading on scroll works
- Filters work
Log in as a user who is not a scope member and verify that they cannot see this page.
_Screenshot:_
=> feature: Activity dashboard tab

client/containers/DashboardActivity/DashboardActivity.tsx, client/containers/DashboardActivity/activityItemRow.scss, client/containers/DashboardActivity/boundaries.ts, client/containers/DashboardActivity/dashboardActivity.scss
Couldn't resist a good idea here — I added some time bucketing for Activity items (e.g. `Today`, `Yesterday`, `Last Week`, etc) to help break them up visually.
_Test plan:_
Visit a few Activity dashboards with different filters enabled and make sure items are bucketed correctly.
_Screenshot:_
=> update: Activity dashboard item time bucketing

client/containers/DashboardPage/DashboardPage.tsx, client/containers/Page/Page.tsx, server/page/model.ts, server/page/queries.ts, server/routes/__tests__/collection.test.ts, stubstub/modelize/builders.js, tools/migrations/2021_06_29_makePageLayoutNonNullable.js, tools/migrations/data/2021_06_29_backfillPageLayouts.js, utils/pages.ts
Resolves #1494 
We currently allow Pages to be created with `layout = null`. When we load such a Page, the client uses the value of `getDefaultLayout()` as a fallback layout, but the server doesn't send down Pubs for that layout, which results in an error. We solve this problem by enforcing that Pages do have a non-null `layout`, by backfilling existing null layouts to the default value, and using `getDefaultLayout()` — renamed to `generateDefaultPageLayout()` — to give Pages a layout when created.
This also fixes two minor bugs:
- The existing default layout blocks have an invalid `content.size` which has been replaced with `content.pubPreviewType`
- There is currently the possibility of adding a `null` value to `Community.navigation` during Page creation.
I ran the following to backfill …
=> fix: Enforce that Pages have a non-null layout

server/community/__tests__/queries.test.ts, server/community/queries.ts, server/routes/user.tsx
addresses issue #1429 
This fixes an issue where bad actors can impersonate members of communities they are not apart of. We now verify that a user has contributed to a community before their user page can be shown. If they are not, they will be redirected to the main pubpub page. 
Test:
1. Unit test for user redirect
2. Go to a pubpub community(https://www.pubpub.org/explore) you are not part of. At the end of the community homepage url type: /user/<firstname-lastname>. If you are not a member, this should redirect you back to the main pubpub site
=> fix: more robust community check to avoid impersonation, phishing, and other hacks

client/containers/DashboardActivity/ActivityFilters.tsx, client/containers/DashboardPage/PageDelete.tsx, client/utils/activity/renderers/collection.tsx, client/utils/activity/renderers/index.ts, client/utils/activity/renderers/page.tsx, client/utils/activity/titles/index.ts, client/utils/activity/titles/page.ts, server/activityItem/fetch.ts, server/activityItem/queries.ts, server/activityItem/utils.ts, server/hooks.ts, server/page/api.ts, server/page/hooks.ts, server/page/queries.ts, tools/activityItem/backfillCommunity.ts, types/activity/associations.ts, types/activity/collection.ts, types/activity/filters.ts, types/activity/index.ts, types/activity/page.ts, types/page.ts
Resolves #1454 
During our first pass through Activity I left Pages alone because it was just one less thing to contend with. Now that we're almost ready to launch this feature I've gone back and added new activity items for Page creation, updating, and deletion as well as hooks to create these items and updates to the backfill to include them.
_Some Page items in Activity:_
_Test plan:_
Unfortunately we have no unit tests for the Pages API, so you can test this by creating, changing, and deleting Pages and ensuring that these actions create corresponding activity items that appear in the Community-level Activity dashboard tab.
=> update: Add activity items for Pages

client/components/Editor/styles/main.scss
Sets the line height for footnotes, so that they don't add height to interior lines of paragraphs. Fixes #1491.
Before:
After:
_Test Plan_
1. Visit any Pub with a footnote on an interior (e.g. not the first) line of a paragraph. Make sure that line is not bigger vertically than surrounding lines.
2. Export the Pub to a PDF and make sure the footnote also looks good in the PDF export.
=> fix: add line height to footnote

workers/tasks/import/xslt/jats-to-bib.xsl
Updates our XSLT JATS-to-bib pre-processor to handle collab fields, which MITP is making use of. I also took the opportunity to clean up a little weirdness, including some odd formatting and the accidental repetition of editor and lack of translator matches in a few cases.
Resolves #1517.
_Test Plan_
- Import an MITP JATS file (ask Gabe) and make sure citations are imported as expected. In particular, make sure a citation with a `<collab>` field places the text of that field into the author in the bibtex.
- Import a recent APA JATS file (ask Dawit) and make sure citations are still imported as expected.
=> update: add collab handler to jats-to-bib

client/containers/Pub/PubHeader/details/pubDetails.scss, client/containers/Pub/PubHeader/pubHeader.scss
Resolves #1526
Before:
After:
I'm curious how this happened, since I don't remember changing anything in this area for a long time, and I'm a little concerned this isn't the simplest fix. But it works.
_Test plan:_
Visit a Pub (like `/pub/k11o9bus/` on dev) that has more contributors than will fit above the fold of the "Show Details" view of the Pub header. Verify that they scroll instead of getting cut off.
=> fix: Make sure long list of Pub contributors in PubDetails will scroll

server/utils/slugs.ts
We have a function called `findAcceptableSlug` that takes a `desiredSlug` for a new Community or Page and hyphenates it so that it doesn't collide with any other slugs in the Community. This PR fixes two problems with that function:
- It doesn't check the `definitelyForbiddenSlugs` with routes like `/dash` that belong to PubPub
- It intends to load every slug in the Community's Pages and Collections to check against `desiredSlug` but there's an extra `{ slug: desiredSlug }` clause on those queries that prevents most items from loading, which breaks the hyphenation.
_Test plan:_
- Create three Pages or Collections by the same name (I used `iantest`). These should automatically derive the following slugs: `iantest`, `iantest-2` and `iantest-3`.
- Create a Page or Collection called `dash` …
=> fix: Let findAcceptableSlugs check all Community slugs for collisions

server/utils/citations/generateCitationHtml.ts, server/utils/ssr.tsx, utils/citations.ts, utils/crossref/createDeposit.js, utils/crossref/render/journal.js, utils/crossref/schema/journal.js, utils/crossref/transform/community.js, workers/tasks/export/metadata.ts
this addresses issue #1537 
When rendering information for crossref, metadata, exports, and citations the journal name is being created for all collections. The set journal name should only apply to issues. I have written changes so that the expected behavior happens for issues journal title/citation-journal-title/container-title/title.  
Test plan(the only thing that changed):
With journal citation set and in a primary issue collection, create a crossref deposit for a pub. Be sure the journal metadata title is set to the journal citation name. Export the pub, be sure the header includes the journal name. Look at the citations in pub overview or details and be sure the Journal Name is listed. Use the inspector to make sure the the citation-journal-title is set to the journal name.
With …
=> fix: Citation data rendering

Aptfile, client/containers/Pub/PubDocument/PubFileImport/MetadataEditor.tsx, package-lock.json, package.json, server/server.ts, workers/tasks/import/bibliography.ts, workers/tasks/import/import.ts, workers/tasks/import/metadata.ts, workers/tasks/import/rules.ts
Also a few related things:
- Updated the importer rules to accommodate these changes
- Migrated off `pandoc-citeproc` to equivalent new command in Pandoc for citation processing
- Snuck in a fix to hide the `MetadataEditor` when it has nothing interesting to say
=> update: Upgrade to prosemirror-pandoc 0.7.0 and to latest Pandoc

client/containers/DashboardCustomScripts/DashboardCustomScripts.tsx, client/containers/DashboardCustomScripts/dashboardCustomScripts.scss, client/containers/DashboardSettings/CommunitySettings.tsx, client/containers/DashboardSettings/communitySettings.scss, client/containers/DashboardSettings/dashboardSettings.scss, server/customScript/__tests__/api.test.ts, server/customScript/api.ts, server/customScript/permissions.ts, server/customScript/queries.ts, server/routes/dashboardCustomScripts.tsx, utils/customScripts.ts
addresses issue #1546 
Adds custom css for all communities. Community admins can now access a custom scripts editor via the settings dashboard. 
Test plan
go to community settings as an admin
scroll to custom css link, hover over ⚠️ symbol and read the tooltip disclaimer 
click on custom css link
most community admins should only see the css tab. if you are hardcoded to have js access you will see both
run test suite locally for custom scripts
=> enhancement: Custom css for communities

client/styles/variables.scss, workers/tasks/export/html.tsx
addresses issue #1509
CJK fonts cannot be loaded via bundle on Heroku because they are huge. Having dynamic subsetting allows fonts to be loaded during export as opposed to resting on the Heroku bundle. 
before
after
Test:
Add Korean, Japanese, and Chinese characters in header of pub doc
Add Korean, Japanese, and Chinese characters in body of pub doc
verify that all characters a re rendered
heres a pub with all three
https://demo.duqduq.org/pub/t0tkgi74/draft
=> bug: CJK fonts render for export

package-lock.json, package.json, workers/tasks/export/html.tsx
Bumps KaTeX to 0.13.18, resolving #1551 and making our LaTeX support much better.
I did basic QA on a number of HDSR articles with lots of LaTeX, particularly: http://localhost:9876/pub/fxz7kr65/release/6 and https://localhost:9876/pub/y9vc2u36/release/7.
Luckily, it doesn't look like this will break our implementation of KaTeX in any way. In the future, we may want to take advantage of some new features like the improved error messages in particular, and we will want to make the fix described in #1577 to take full advantage of the new features. But that's beyond the scope of this PR.
There were a few breaking changes in KaTeX's support of LaTeX, however, and I searched the Docs table in the db for Pubs that may have these issues. Once we release, we'll want to fix these pubs
Very hard to …
=> dev: bump katex to 0.13.18

client/utils/suggestions/suggestionManager.ts
Resolves #1578
This bad boy fixes the positioning of the menu that gives suggestable items which appears when you type "@". I think I broke this a while ago by adding `position: relative` to `.pub-body-component`.
_Test plan:_
Visit [this Pub](http://localhost:9876/pub/igh7ltk4/draft) and make sure the menu appears when you type "@"
=> fix: Correctly position the reference suggestion (@-menu) popover

client/containers/Pub/PubHeader/themes.scss
Resolves #1554
This adds an exception to the `color: white` on the `black-blocks` header theme for the text input part of an `EditableText` — since the background of the text input is still light, we want the text to remain dark as shown:
_Test plan:_
Create a Pub and use the "Edit Theme" button in the header to turn on the "Black Blocks" theme. Click the Pub title to edit it and verify that the text is black on a light background while editing.
=> fix: Use black text when editing black-blocks themed Pub title

server/utils/citations/structuredCitations.ts, utils/promises.ts
There is currently [an issue with Crossref](https://twitter.com/CrossrefSupport/status/1445788491275587584) that prevents Citation.js from loading structured citation data — in turn, this is causing some Pubs to not load. We should consider caching this data — a quicker fix is to let these citations error out if they do not load quickly enough.
_Test plan:_
Create a new Pub and add a citation with a DOI as its structured data. Refresh the page and see that it loads.
=> fix: Don't block forever on Cite.async

client/styles/variables.scss
Resolves #1640. See that issue for context.
This adds the font 'DejaVu Serif' to the stack for exports, because it's the only truetype serif that exists on our Heroku Ubuntu machine. It's ... not too far from Georgia, and generates non-janky PDFs that can be copy/pasted and annotated! Huzzah.
Long term, we should execute on our plan to move the export pipeline to another machine where we don't have the same slug constraints and can provide required fonts locally.
Weirdness it's doing now:
Georgia (local):
DejaVu Serif:
_Test plan_
1. Export a complex PDF and make sure it looks decent!
E.g.:
[394acb67-40e4-4b0d-be19-5c937815bba1 (2).pdf](https://github.com/pubpub/pubpub/files/7429700/394acb67-40e4-4b0d-be19-5c937815bba1.2.pdf)
=> fix: Font issues in PDF exports

server/apiRoutes.ts, server/models.ts, server/pub/model.ts, server/submission/__tests__/api.test.ts, server/submission/api.ts, server/submission/model.ts, server/submission/permissions.ts, server/submission/queries.ts, types/index.ts, types/submission.ts, utils/pub/pubDates.ts
implements #1612 
Testing via API tests.
Largely boilerplate.
Question this raises: are we only ever interacting with `Submissions` directly when we are changing their statuses? For creation/deletion, that would only occur when the `Spub` is created/deleted, yes? So operations on `Submissions` then are typically side-effect like?
=> Submissions model, query, api, and tests

client/containers/Pub/PubDocument/PubDiscussions/Discussion/Discussion.tsx, types/pub.ts, types/thread.ts
Resolves #1655 
When displaying anchored Pub discussions at the bottom of a Pub, we used to show a helpful box with the anchor text to provide context for the discussion. That probably disappeared during our discussion refactor last year, but now it's back!
_Test plan:_
- Visit the draft of a Pub and make an anchored comment
- Check the discussions section at the bottom of the Pub and make sure the highlighted text appears alongside it.
=> fix: Restore anchored discussion text on Pub bottom

server/pub/__tests__/queryMany.test.ts
The `queryPubIds` function is pretty critical across PubPub but we don't have any unit tests for it. Except now we do!
_Test plan:_
```
npm run test-dev server/pub/__tests__/queryMany.test.ts
```
Resolves #1666 👹
=> dev: Add tests for queryPubIds

client/containers/DashboardSubmissions/NewSubmissionWorkflowEditor.tsx, client/containers/DashboardSubmissions/SubmissionWorkflowEditor.tsx, client/containers/DashboardSubmissions/validators.ts, server/submissionWorkflow/__tests__/api.test.ts, server/submissionWorkflow/model.ts, server/submissionWorkflow/queries.ts, stubstub/modelize/builders.js, types/submissonWorkflow.ts
After realizing that we want submission workflows to have a title independent of the Collection's title, I have broken the `layoutBlockContent` column of `SubmissionWorkflow` into `title` and `introText` so the title can be easily reused. I also fixed up some stuff I borked on the tests on this branch with my last commit.
_Test plan:_
```
npm run test-dev server/submissionWorkflow
```
You can also visit the Submissions tab of a Collection to make sure the workflow editor is still working.
=> update: Changes to SubmissionWorkflow model in response to design

client/components/Layout/LayoutCollectionHeader.tsx, utils/collections/getMetadata.ts, utils/dates.ts, workers/tasks/import/metadata.ts
Resolves #1642
Quick one to make sure Collection metadata dates in a Collection Header block are always shown as the inputted date, even though they have UTC complications.
_Test plan:_
Set a Collection metadata field that's a date to `2021-11-04` and make sure that same date renders in the Collection Header block in its Layout.
=> fix: Always show correct 'calendar date' for Collection metadata

.eslintrc, client/components/DialogLauncher/DialogLauncher.tsx, client/containers/Pub/PubDocument/PubBottom/Discussions/DiscussionsReleaseDialog.tsx, client/containers/Pub/PubDocument/PubBottom/Discussions/DiscussionsSection.tsx, client/containers/Pub/PubDocument/PubBottom/Discussions/discussionsReleaseDialog.scss, server/discussion/api.ts, server/discussion/permissions.ts, server/discussion/queries.ts, server/discussion/utils.ts, server/discussionAnchor/__tests__/queries.test.ts, server/discussionAnchor/queries.ts, tools/migrations/data/2020_12_01_createDiscussionAnchors.js, types/visibility.ts
Resolves #1668
In response to a recurring need from the content team to manually move discussions from draft to release, here's a little widget that does this. For now it's only for the `pubpub-team` user, but we could make it part of the release process in the future. To use it, click the little arrow-out icon in the Discussions section:
Then choose which ones you want to move:
(Don't know why that vertical spacing is goofy but I'm out of time to fix it.)
_Test plan:_
- Open a Pub draft, add some discussions, and then make a Release. Return to the draft and use this newfangled button to move the discussions to the release
- Make sure this button does not appear if you are not logged in as the PubPub team, if there are no discussions, or if you're viewing the draft.
=> feature(?): Top secret Release Discussions dialog

client/containers/Pub/PubHeader/citationsPreview.scss
removes a line from the citations preview
test: 
Set a pubs citation style to AMA. Go to the pub header and look at citations, the `1.` and the line break should now be gone
=> bug: hide 1 from citation preview 

client/containers/DashboardOverview/DashboardSubmissionsOverview/SubmissionItems.tsx, server/pub/__tests__/queryMany.test.ts, server/routes/dashboardSubmissions.tsx, server/submission/__tests__/api.test.ts, server/submission/queries.ts, types/submission.ts
this just changes the fields 'submitted' to 'pending'. this feels more in line with how the field is being used and has been talked about
test:
run submission test to be sure changes do not effect expected behavior
=> update: Change language from submitted to pending

workers/tasks/export/metadata.ts, workers/tasks/export/pandoc.ts, workers/tasks/export/types.ts
Resolves #1688 and adds some other needed fields for Portico.
_Test plan_
1. Create a pub in a community with "publisher" and "cite as" set, in journal issue collection with all its metadata filled out.
2. Add two or more authors, one of whom has an orcid ID (you can use Gabriel Stein with the photo if needed, or create a shadow author and make one up).
3. Download a regenerated JATS file and check that all of the following are properly filled out:
- journal-title: community cite as setting
- issn (print): collection print issn setting
- issn (electronic): collection electronic issn setting
- publisher-name: community publisher setting
- author orcid id
- volume: collection volume setting
- issue: collection issue setting
- elocation-id: pub slug
- pub-dates with proper year, date, and …
=> update: add issn, publisher, dates, issue, volume, elocation to jats output

server/userNotification/__tests__/api.test.ts, server/userNotification/queries.ts, server/userNotificationPreferences/model.ts, server/userNotificationPreferences/queries.ts, types/userNotification.ts
I've had this crazy idea for a tool that prevents compulsive notification-checking for a while, that I call _notification cadence_. The rules go like this:
1. You pick a cadence `c`, which is a time interval, given in minutes, that we store
2. When you check your notifications, we mark this time as `t0`
3. Your notifications are now frozen in time — no more new ones will appear for `c` minutes
4. At `t1 >= t0 + c` you can check again and we'll show you all your notifications, including those created on `[t0, t1]`
5. Your notifications are now frozen again until `t1 + c`. The cycle continues...
(For `c = 0` you'll receive notifications instantly)
We have a field in `UserNotificationPreferences` for notification cadence, and a dropdown that lets you select one:
This PR just implements the …
=> Implement "notification cadence" in PubPub

client/components/Avatar/Avatar.tsx, client/components/Footer/Footer.stories.tsx, client/components/Footer/Footer.tsx, client/components/Header/Header.tsx, client/components/LayoutEditor/LayoutEditor.tsx, client/components/LegalBanner/LegalBanner.tsx, client/components/NavBar/NavBar.tsx, client/components/ScopeDropdown/ScopeDropdown.tsx, client/containers/App/SideMenu/ScopePicker.tsx, client/containers/App/usePageState.ts, client/containers/DashboardEdges/DashboardEdges.tsx, client/containers/DashboardEdges/DashboardEdgesListing.tsx, client/containers/DashboardSettings/CollectionSettings/CollectionSettings.tsx, client/containers/DashboardSettings/CommunitySettings.tsx, client/containers/DashboardSettings/navBuilderContext.ts, client/containers/Pub/PubDocument/PubDiscussions/PubDiscussions.tsx, client/containers/Pub/PubDocument/PubFileImport/MetadataEditor.tsx, client/containers/Search/Search.tsx, client/containers/User/User.tsx, client/utils/activity/types.ts, client/utils/navigation.ts, types/community.ts, types/context.ts, types/index.ts, types/request.ts, utils/hooks.ts
The `usePageContext()` hook is everywhere but we always have to cross-reference other callsites to remind ourselves what values it provides. No longer! I have defined its return value in TypeScript and fixed all the resulting little type issues.
_Test plan:_
Going out on a bit of a limb to say there shouldn't be any behavioral changes (except for a bug I found in `PubDiscussions` that the new types caught). So a typecheck should be sufficient?
=> dev: Add type definitions to `usePageContext`

workers/tasks/export/transforms/extractMetaContent.ts
Resolves #1695
An `<abstract>` tag in well-formed JATS should have its text wrapped in `<p>` tags. This change tweaks our exporter to make that happen.
_Test plan:_
Create a new Pub with an "Abstract" H1 and add some text to the following paragraph. The JATS XML export of the Pub should have an `<abstract>` tag containing a `<p>` tag which itself contains the abstract content.
=> fix: Export abstract to JATS with <p> wrapping intact

client/components/Layout/LayoutSubmissionBanner.tsx, server/routes/index.ts, server/routes/submit.tsx, server/submission/api.ts, server/submission/queries.ts
In #1685 I created a "really basic Submissions banner" that gets added to the layout of a Collection with submissions enabled. It's still really basic, but I've fixed one major flaw — for logged-out users, instead of silently 403'ing, it will redirect you to `/login` and _then_ create the Spub after you've logged in.
I accomplished this by moving the actual Submission creation to a hard-linked route at `/submit/:submissionWorkflowId`. This will redirect you to the Pub that gets created if you're logged in, or to `/login` if you're not logged in, or throw a 403 if you're trying to pull a fast one.
Maybe I should remove the `/api/submissions` POST handler, because it no longer gets any use?
_Test plan:_
VIsit a Collection with a Submissions banner (like [this …
=> update: Move submission creation out of API to support login-redirect

server/doi/api.ts, server/doi/permissions.ts
Fixes #1745
This PR moves the releases check in our DOI generation's `assertUserAuthorized` function into a new function called `pubExistsAndIsMissingReleases`. Removing this check allows users to generate DOIs for Pubs without releases.
The new `pubExistsAndIsMissingReleases` function is called in the Crossref preview/deposit code because we still want to guarantee that a Pub has at least one release before depositing.
* Create a new Pub. Don't release it.
* Go into the Pub settings, you should be able to generate a DOI without error!
=> fix: allow DOI updates for Pubs without releases

client/components/Editor/plugins/collaborative/document.ts, client/components/Editor/types.ts, client/components/Editor/utils/firebase.ts, client/containers/Pub/PubDocument/PubBody.tsx, client/containers/Pub/PubSyncManager.tsx, client/utils/firebaseClient.ts
Resolves #1753
We've had a few reports of folks losing their work because `Editor` lets them add content in a stalled `connecting` state. This change makes the editor read-only until `status = 'connected'`. I've done a little work moving the responsibility for monitoring the connection around, and a little type-safety/cosmetic overhaul.
_Test plan:_
Check that:
- The editor works and persists your changes after refreshing
- You cannot type while the status bar says "Connecting..." (maybe try throttling your connection here)
- The collab-status indicator works as expected: `connecting -> connected -> (saving <-> saved) -> disconnected`
=> fix: Make Editor read-only until Firebase finishes connecting

client/components/ConfirmDialog/ConfirmDialog.tsx, client/containers/DashboardOverview/CollectionOverview/DashboardCollectionOverview.tsx, client/containers/DashboardOverview/CommunityOverview/CommunityItems.tsx, client/containers/DashboardOverview/helpers/OverviewSearchGroup.tsx, client/containers/DashboardOverview/overviewRows/PubOverviewRow.tsx, client/containers/DashboardOverview/overviewRows/labels.tsx, client/containers/DashboardSubmissionWorkflow/SubmissionWorkflowEditor.tsx, client/containers/DashboardSubmissions/ArbitrationMenu.tsx, client/containers/DashboardSubmissions/DashboardSubmissions.tsx, client/containers/DashboardSubmissions/SubmissionItems.tsx, client/containers/DashboardSubmissions/SubmissionRow.tsx, client/containers/DashboardSubmissions/VerdictDialog.tsx, client/containers/DashboardSubmissions/arbitrationMenu.scss, client/containers/DashboardSubmissions/types.ts, client/utils/useLazyRef.ts, client/utils/useManyPubs/types.ts, client/utils/useManyPubs/useManyPubs.ts, types/util.ts
This PR chamfers some edges on the Submissions dashboard that's coming together across tasks.
- Move a bunch of state management for individual Spubs out of `PubRow` and `SubmissionItems` into a new `SubmissionRow` that wraps `PubRow`. This component is responsible for managing its own `submission.status` state, and hiding itself if the Pub has been deleted. It also renders Submission-specific details (like the status) instead of delegating that to the more general `PubRow`.
- Add a `cacheQueries` option to the `useManyPubs()` monstrosity. By default the hook caches Pubs from different filters/queries to `/api/pubs/many` — these filters correspond to e.g. the Pending and Accepted tabs of the Submissions listing. This is a great experience on the Overview dashboard tab but creates problems …
=> update: Some glue for Submissions

client/components/Editor/schemas/citation.ts, client/components/Editor/utils/notes.ts, package-lock.json, package.json
This PR fixes two problems with citations:
- Citations with identical `unstructuredValue` are no longer deduped because the `ids` plugin is now generating random identifiers for each paragraph in the unstructured content HTML. To restore this behavior, I have added the [`striptags`](https://www.npmjs.com/package/striptags) package to get raw text from this HTML. We now dedupe on the basis of that raw text. This will restore the correct behavior retroactively to Pubs created since this breaking change.
- The citation `customLabel` attribute doesn't get preserved in copy+paste. Well, it does now!
_Test plan:_
- Create two separate citations with the same unstructured content and verify that they are deduped in the Pub bottom citations section. Refresh the page and make sure this works on …
=> Two citation fixes

client/components/PubReleaseDialog/PubReleaseDialog.tsx, client/components/PubReleaseDialog/pubReleaseDialog.scss, client/containers/DashboardSubmissions/ArbitrationMenu.tsx, client/containers/Pub/PubHeader/DraftReleaseButtons.tsx
#1684
Adds a 'release pub' button to the Submission Overview Rows for `accepted` spubs.
_Test plan:_
1. navigate to Submissions Overview
2. filter pubs based on `accepted`  status
3. click "social-media" icon for releasing pubs
4. proceed through pub-release process, same as from a pub draft
If it differs in any way from the release experience in the pub draft view, that's a problem.
=> feature: pub release dialog

server/utils/email/digest.tsx, tools/emailActivityDigest.ts
This PR fixes a bug that would crash the Activity digest sending script when it encountered an object in `ActivityAssociations` that was deleted after its Activity items were created. I also added a try/catch wrapper around the code that renders and sends an individual email, so if one fails the script will plow on undeterred.
_Test plan:_
Let's land this and see whether it works tonight.
=> fix: Activity digest emails not sending due to deleted associations

client/components/PubAttributionEditor/PubAttributionEditor.tsx, client/containers/Pub/SpubHeader/SpubHeader.tsx, client/containers/Pub/SpubHeader/SubmissionTab/Contributors.tsx, client/containers/Pub/SpubHeader/SubmissionTab/SubmissionTab.tsx, client/containers/Pub/SpubHeader/SubmissionTab/TitleDescriptionAbstract.tsx, types/pub.ts
This adds contributor functionality to the submission tab in the spub header
test
Run local environment and add contributors. refresh page to be sure contributors are still saved
=> Submission Contributors

package-lock.json, package.json, workers/tasks/export/notes.ts
Our attempt to insert JATS `mixed-citation` elements using an XML parse/write roundtrip (in #1795) stripped too much important info from the XML. So in this PR I use regex to accomplish the same thing 🙃 I also limited the tags that can go inside a `mixed-citation` so that the JATS will validate.
_Test plan:_
Create a document with multiple unstructured citations and at least one structured one (`/pub/7w7jd9y9/draft` will do nicely) and check the JATS export:
- `element-citation` elements should remain for structured citations
- `mixed-citation` elements should appear for unstructured citations
- The only rich text content allowed inside `mixed-citation` should be `bold`, `italic`, and `ext-link`. `p` tags should be stripped.
=> fix: Use regex instead of XML parser to insert mixed-citation

client/containers/CommunityCreate/CommunityCreate.tsx, client/containers/UserCreate/UserCreate.tsx
Fixes a 🤦 I did when I updated this form.
_Test plan_
Technically, you should visit the community creation page and follow the privacy links, and do the same for a user signup.
=> fix: privacy link on signup/community page

server/collectionPub/queries.ts, server/utils/citations/generateCitationHtml.ts, server/utils/queryHelpers/pubSanitize.ts, workers/tasks/export/metadata.ts
A Pub's byline will include the contributors to its primary Collection, but there are two places in the Pub header where we don't incorporate that information:
1. the Collection browser:
2. the Cite dropdown:
This PR fixes that problem, resolving #1807. This is kind of a cheap fix — what I would really like to do is create a computed/materialized `primaryCollection` association from `Pub` to `Collection` so we don't have to load _all_ a Pub's Collections and compute the primary collection in business logic — but after reading the documentation for a while, I can't figure out how to do this from Sequelize.
_Test plan:_
Create a public, non-Tag Collection and add attributions in Settings. Create a Pub inside that Collection and verify that you see those attributions:
- In the Cite dropdown …
=> fix: Always show Collection-level contributors in Collection browser and CitationsModal

client/components/Email/digest/ActivityBundle.tsx, client/components/Email/digest/ActivityBundleRow.tsx, client/components/Email/digest/Digest.tsx, server/routes/email.tsx, server/utils/email/digest.tsx
Resolves #1793
This PR
* adds links to Pub and Collection activity item titles in digest emails
* uses `colspan` to prevent discussion snippets from overflowing
*Test Steps*
* Visit http://localhost:9876/email/digest
* Verify that Pub and Collection titles are clickable and take you to the correct URL
* Verify that discussion snippets are contained within the width of the email (i.e. they do not overflow to the right).
=> feat: add digest links; fix discussion overflow

workers/tasks/export/pandoc.ts
A few fixes for JATS exports. This PR:
- Fixes a bug where we were checking for the existence of a print ISSN in order to render an electronic ISSN
- Uses YYYY date formatting instead of YY
=> fix: use YYYY for export publication date; include electronic issn

client/components/GridWrapper/GridWrapper.tsx, client/components/PubShareDialog/PubShareDialog.tsx, client/containers/Pub/SpubHeader/SpubHeaderTab.stories.tsx, client/containers/Pub/SpubHeader/SpubHeaderTab.tsx, client/containers/Pub/SpubHeader/spubHeaderTab.scss, client/utils/useViewport.ts
Implements #1849
Test: view in storybook. To check the expanded size behavior, open inspector (or like) with dimensions:responsive and monitor the `min-height` css property on the wrapper div while changing the viewport; the light-grey background wrapper should resize to fill to the bottom of the viewport.
=> Create expandable tab wrapper

workers/tasks/export/templates/article_pubpub.jats_publishing, workers/tasks/export/templates/default.jats_archiving, workers/tasks/export/templates/default.jats_publishing
A quick fix that removes the empty `<journal-id></journal-id>` elements from our JATS XML exports which caused issues with PubMed.
I copied the existing article.jats_publishing file, removed a block that explicitly rendered the empty element in the case of no configured pmc/nlm-ta/publisher-id, and updated the jats templates to target the new file.
Below are the contents removed from the original article.jats_publishing file:
```
$-- Fallback: an empty journal-id in case none is available.
$if(journal.publisher-id)$
$elseif(journal.nlm-ta)$
$elseif(journal.pmc)$
$else$
<journal-id></journal-id>
$endif$
```
**Test Plan**
1. Export a Pub as JATS XML. There should be no empty `<journal-id />` element.
=> fix: strip empty journal-id element from jats exports

server/pubHistory/api.ts
`/api/pubHistory` currently expects a `historyKey` GET param — but when that value is not specified, it becomes `NaN`, which is passed deep into our Firebase code and eventually prevents us from using a checkpoint to load a Firebase document. Without a checkpoint, we have to load every individual change in the document, which can cause major hangs.
Instead, we want to use `null` as a fallback. When we pass `historyKey = null` into the Firebase draft retrieval code, it's interpreted to mean "the latest key", and the API will retrieve the latest document as expected.
_Test plan:_
(We tested this synchronously on a call)
Call `/api/pubHistory` without a `historyKey` GET param (e.g. by opening and then closing the Pub History viewer) and verify that `getRequestIds` returns `{ historyKey: null …
=> fix: Don't pass `NaN` as history key from `/api/pubHistory`

client/containers/DashboardOverview/overviewRows/labels.tsx, utils/dates.ts, utils/pub/pubDates.ts
addresses #1887
Now when you submit a pub, it shows as having just submitted:
1. create a spub
1. submit it
2. check the submitted at line
=> bugfix: display correct submittedAt time ago

client/containers/Pub/PubDocument/PubHeaderFormatting.tsx, client/containers/Pub/PubDocument/PubWordCountButton.tsx, client/containers/Pub/PubDocument/pubWordCountButton.scss
Closes #1769 
This PR adds a button to the `PubHeaderFormatting` component that can be used to perform a one-off calculation of the total word and character count of the Pub. A line chart icon was chosen for this button because it represents statistical... stuff. But I'm not totally happy with it so I'm open to other ideas.
When clicked, a popover containing word and character count should appear immediately below the button.
These counts are computed only once when the popover component mounts. Clicking on the page or changing focus from the button immediately hides the popover.
1. Make a new Pub.
2. Type some words and add some figures.
3. Things that *should not* be included in the word or character counts:
- Whitespace and punctuation (except punctuation surrounded by spaces, e.g. " …
=> feat: add pub word count button to formatting bar

client/components/Timeline/Timeline.stories.tsx, client/components/Timeline/Timeline.tsx, client/components/Timeline/TimelineCondenser.tsx, client/components/Timeline/TimelineItem.tsx, client/components/Timeline/util.ts, client/containers/DashboardOverview/PubOverview/PubOverview.tsx, client/containers/DashboardOverview/PubOverview/PubTimeline.tsx, client/containers/DashboardReviews/DashboardReviews.tsx, server/pub/queryMany.ts, server/utils/citations/generateCitationHtml.ts, server/utils/layouts/layoutPubs.ts, server/utils/queryHelpers/communityOverview.ts, server/utils/queryHelpers/index.ts, server/utils/queryHelpers/pubEnrich.ts, server/utils/queryHelpers/pubSanitize.ts, tools/layoutcheck/query.ts, types/pub.ts
Closes #1913
A quick PR that matches the ordering of the reviews on a Pub's Overview dashboard page to the order on the Reviews page (time descending).
=> fix: equate ordering of review items on review and overview pages

client/containers/DashboardOverview/CollectionOverview/DashboardCollectionOverview.tsx, server/routes/dashboardCollectionOverview.tsx
This fix adresses #1947 
The submission banner should now be present when submissions are enabled and not when they are not.
=> fix: Render Submissions Banner on Workflow Enabled 

client/containers/DashboardSubmissions/SubmissionItems.tsx
For some collection X, when viewing the Submissions tab of X's overview, only show spubs submitted directly to X, filtering out spubs that were added to the collection from elsewhere.
=> Fix: show only native submissions in submissions overview

client/containers/Pub/PubHeader/DraftReleaseButtons.tsx, client/containers/Pub/PubHeader/ResponsiveHeaderButton.tsx, client/containers/Pub/PubHeader/SmallHeaderButton.tsx
Resolves #1952
Test Plan
1. Load a Pub release
2. Scroll the page so the sticky banner appears and sticks to the top of the viewport.
3. The banner should not have extra "padding" at the top.
=> fix: extra height on sticky banner in Pub release view

client/containers/Pub/SpubHeader/SpubHeaderToolBar/SpubHeaderToolbar.tsx
fixess #1946 
issue: On submit `submision.status` will change accordingly. This causes `Spubheader` to rerender. In order to show the modal element, we will simply hide the button on submit.
=> bug: Fixes Submission Modal Flicker

workers/tasks/export/notes.ts, workers/tasks/export/pandoc.ts
Resolves #1943
Test Plan
1. Create a Pub. Add a structured citation and an unstructured citation.
2. Download the Pub as a Word document.
3. Open the file using a word processor like Pages (mac)/Word
4. Repeat steps 2-3 for epub, open with an epub viewer like Books (mac).
5. Repeat steps 2-3 for a text format like markdown and an XML format like JATS.
6. The JATS export should have one `mixed-citation` and one `element-citation`.
=> fix: use pandoc tmp file output instead of reading from stdout

server/utils/citations/generateCitationHtml.ts, types/attribution.ts
In making some collection-level attribution changes, we introduced a small regression that was including all Pub-level contributors who were not marked as "byline" contributors in citations. This fixes that so that only authors at the Pub level, or contributors at the collection level, are shown in Pub-level citations.
Thanks to @3mcd for the fancy type-guarding.
_Test plan_
1. Create a pub.
2. Add a contributor and uncheck "display on byline"
3. Add the pub to a collection
4. Add a contributor to the collection
5. Verify: pub-level citation shows only collection-level contributor and any pub-level contributors with "byline" checked, but not pub-level contributors without "byline" checked.
=> fix: Citations including non-byline pub-level contributors

client/containers/Pub/SpubHeader/SpubHeaderToolBar/SpubHeaderToolbar.tsx
Nothing fancy, just hiding the submission button when the spub is not 'incomplete'.
when bugged:
=> fix: hide submit button on submitted spubs

client/components/Layout/LayoutBanner.tsx, client/components/LayoutEditor/LayoutEditorBanner.tsx
fixes #1974
_Test plan_
1. visit page at slug `banner-buttons-custom-text-fix` on the demo community
2. confirm that the button text reads "If you read this custom text, the bug has been fixed up."
=> fix: show custom layout banner button text

client/components/Editor/utils/notes.ts, client/containers/Pub/usePubNotes.ts, server/utils/citations/structuredCitations.ts, workers/tasks/export/notes.ts, workers/tasks/export/pandoc.ts, workers/tasks/import/rules.ts
Resolves #1932
This PR fixes an issue where citations with identical unstructured content (rich text) were ignored during export as a consequence of the de-duplication we do in the Pub draft/release views. This leads to an error when the ignored citations ultimately [resolve to pandoc-prosemirror as `undefined`](https://github.com/pubpub/pubpub/pull/1948/files#diff-ea11e8b0c7b2344f85a556dc5c0c1495381fc968175db446821607c75c35b99eR137).
I solve this issue by making the de-duplication (in [`getNotes`](https://github.com/pubpub/pubpub/pull/1948/files#diff-526150d6dea117144c9fddffcf0444902a5a7bcd7b4971f8610004135bb1a54eR33)) optional. `getNotes` now accepts an optional `CitationFingerprintFn` that, when provided, skips duplicate citations that produce the same fingerprint. All citations are …
=> fix: use prosemirror ids in citations; don't de-dupe exported citations

client/containers/Pub/PubDocument/PubDocument.tsx, client/containers/Pub/PubDocument/PubLinkController/LinkPopover.tsx, client/containers/Pub/PubDocument/PubLinkController/PubLinkController.tsx, client/utils/dom.ts
Fixes #1905 by using `pubUrl()` instead of `locationData` to pick a base URL for Pub body permalinks
Test plan:
- Visit a Pub draft and copy a link to a header, paragraph, etc.
- Verify that the link doesn't have `/draft` in it
- Verify that the link still takes you back to the intended page element
- Repeat the same process with a Release.
=> fix: Don't include draft/release info in copied node links from Pub body

client/containers/Pub/SpubHeader/AbstractEditor.tsx, client/containers/Pub/SpubHeader/DetailsTab.tsx, utils/pub/abstract.ts
Resolves #1970
*Test Plan*
1. Create a submission with an abstract.
2. Submit it.
3. Go back to the Submission tab and remove the abstract from the Pub body.
4. The editor should not crash, and you should see the message "The abstract was removed from the submission body after submission and may need to be re-added before release." above the workflow's abstract field.
5. Add another abstract using `# Abstract` (be sure to add some content in a paragraph below the heading).
6. The warning message should disappear, and the text content of the abstract should appear in the workflow's abstract field.
=> fix: wsod when removing abstract from submitted submission; add warning

client/components/AssignDoi/AssignDoiPreview.tsx, client/components/AttributionEditor/roles.ts, client/components/PubByline/PubByline.tsx, client/components/PubPreview/ManyAuthorsByline.tsx, client/components/PubPreview/PubPreview.tsx, client/containers/DashboardOverview/PubOverview/PubOverview.tsx, client/containers/Pub/PubHeader/details/PubDetails.tsx, server/routes/pubDocument.tsx, server/rss/queries.ts, server/utils/citations/generateCitationHtml.ts, server/utils/ssr.tsx, utils/contributors.ts, utils/crossref/schema/contributors.js, utils/pubEdge/helpers.ts, workers/tasks/export/metadata.ts
addresses #1972 
Putting the mapping here again bc it may be useful
| PubPub Role List | CSL-JSON | HTML Meta | Crossref contributor_role |
| --- | --- | --- | --- |
| none selected (default) | author | citation_author | author |
| --- | --- | --- | --- |
| Illustrator | illustrator | n/a | n/a |
| --- | --- | --- | --- |
| Visualization | illustrator | n/a | n/a |
| --- | --- | --- | --- |
| Writing - Review & Editing | editor | citation_editor | editor |
| --- | --- | --- | --- |
| Editor | editor | citation_editor | editor |
| --- | --- | --- | --- |
| Series Editor | collection-editor | citation_editor | editor |
| --- | --- | --- | --- |
| Translator | translator | n/a | translator |
| --- | --- | --- | --- |
| Chair | chair | n/a | chair |
- Collection level contributors are listed …
=> Map Contributor Roles to Citations

client/components/Editor/commands/textAlign.ts
Resolves #1978 
Simple fix for a tricky bug!
*Test Plan*
- Create a non-`h1` heading
- Move your cursor to the beginning of the heading node/line
- Hit 'Enter'
- The heading should not be converted into an `h1`
=> fix: don't clear attrs of target node when splitting block

server/utils/queryHelpers/communitySanitize.ts, server/utils/queryHelpers/scopeGet.ts
addresses issue #1998 
Community scoped members with view permissions can view private collections that are descendants of the community scope
test:
login as a user with view permissions
from the community dashboard be sure you can see collections that are private
navigate to a collection with a collection layout that has private collections: [here](http://localhost:9876/erics-submission-collection)
hopefully, you can see those
=> View Level Permissions

client/components/Byline/Byline.tsx, client/components/Byline/byline.scss, client/components/Layout/LayoutCollectionHeader.tsx, client/components/PubByline/PubByline.tsx, client/components/PubEdge/PubEdge.tsx, client/components/PubPreview/ManyAuthorsByline.tsx, client/components/PubPreview/PubPreview.tsx, client/components/PubPreview/PubPreviewEdges.tsx, client/components/WithinCommunityByline/WithinCommunityByline.tsx, client/containers/DashboardOverview/overviewRows/overviewRowSkeleton.scss, client/containers/Pub/PubHeader/pubHeader.scss
New and improved refactoring!
When Arcadia's community is loaded: 
1. Overrides the byline with an alphabetically sorted list and an `Az` icon with a tooltip. Not implemented in exports (lower priority since it doesn't have the word by, and needs a more major refactor), search (we send algolia a string containing the word 'by'. Will need more of a refactor), or `PubMenuItems` (really tough to enforce type, will take suggestions if you have them).
2. Per request, uses the title of connections instead of authors to display all connections (since they care less about authorship).
3. Fixes #1999 (a bug I'm pretty sure, because there's code for it that was never being accessed) that made it so external child connections were never displayed in pub blocks, also requested by Arcadia.
One todo …
=> enhancement: Az byline for Arcadia

Aptfile, client/components/PubPreview/PubPreview.tsx, utils/import/formats.js, workers/tasks/import/bibliography.ts, workers/tasks/import/images.ts, workers/tasks/import/import.ts
Bumps pandoc to 2.18 and fixes a tif-to-png conversion bug.
This gets us:
-  Importing Word citations from Mendeley, Endnote, and Zotero (uses the code we built for processing jats-extracted references to do the same for Word docs). There's probably a universe where we handle that in pandoc-prosemirror instead, but doesn't seem worth it for now.
- Importing JATS footnotes!!!
- Importing LaTeX footnotes!!
- Some other cool stuff I'm sure...
_Test plan_
I tested import and export of complex docs heavily, using [this collection](http://localhost:9876/pandoc-importexport-tests), but you should also take it for a spin. The easiest way to do this is locally, making sure you have pandoc 2.18 installed via brew.
We should also do some group smoke testing on dev before release, particularly of the …
=> Bump pandoc and support JATS footnotes and Word citations from Mendeley, Endnote, Zotero

client/containers/About/About.tsx, client/containers/About/about.scss
So........nesting ULs in P tags, which I guess react doesn't like, created some kind of client/server mismatch that resulted in a single link to our roadmap ("on GitHub") inexplicably being overwritten with a link to our membership page? ¯\\_(ツ)_/¯
_To test_
1. Visit about.
1. Click on all the links and make sure they
=> fix: About link

workers/tasks/import/rules.ts
This PR fixes an issue where detached references (references whose referenced nodes have been deleted, appearing as `(ref?)`) cause exports to fail.
_Test Plan_
1. Create a Pub.
2. Enable node labels (hover the `@` in the editor toolbar for instructions).
3. Create a referenceable node, like an image/table/equation.
4. Create a reference to the node (you can use the `@` keyboard shortcut in the Pub body)
5. Delete the referenced node. The reference should now show appear as `(ref?)`.
6. Export the document. It shouldn't break!
=> fix: export detached references

package.json
Fixes an small issue with a specific Pub not being exportable due to empty `<tr>` elements.
=> chore: bump prosemirror-pandoc

package-lock.json, package.json, server/utils/citations/citeStyles/arcadia-science.csl, server/utils/citations/generateCitationHtml.ts, server/utils/citations/structuredCitations.ts, utils/citations.ts
1. Updates citation.js to `0.5.7`. We had been using `0.5.0-alpha2`. No breaking API changes, but a lot of bug fixes since then.
2. As of citation.js 5, the built-in Harvard style had switched from a key of `harvard` to `harvard1`. So we haven't actually supported Harvard styles for some time. We're using `harvard` as our key in the db, so I aliased `harvard` to `harvard1` in the two callsites for `Cite.format`. Eventually we'll probably want to update in the db.
3. Switches citation generation in `generateCitationHtml` from `Cite.get`, which was deprecated in `0.5.x`, to `Cite.format`. This was causing an issue loading newer CSL files, which were defaulting to APA. We are already using `Cite.format` to generate Cites in the editor, and they're both sync functions, so this seems …
=> Update citation.js, fix Harvard, add Arcadia csl

client/containers/Pub/PubDocument/pubBody.scss
The final word.
swap in `break-word` for `break-all`
=> fix: break-word for <ol> in tables

server/pubEdge/queries.ts
Resolves #2019
_Test Plan_
* Add a connection to an external publication to a Pub (for example, use a URL like https://www.nature.com/articles/s41586-022-04645-w)
* Save the connection.
* Edit the connection description, title, and contributors list.
* Save the connection.
* Refresh the page. The edits you made should have persisted.
=> fix: correctly save changes to Pub connections

server/Html.tsx
resolves #2062
Adds classes to the site body based on the user, to help people target custom CSS changes to different types of users.
If logged out: no `user-*` classes, can target with :not()
If logged in but not a member at a given scope: `user-logged-in`
If a member at a given scope: `user-logged-in` and `user-member` and `user-permission-[permission]`
_To test_
1. Logout and visit. Should see no `user-*` body classes.
2. Login as a member and visit. Should see `user-member` and `user-permission-[permission]` as a body class.
3. Login as a non-member and visit. Should see `user-logged-in` as a body class.
4. Add user as a member to a non-community-wide scope.
6. Visit that scope.
7. Should see `user-member` and `user-permission-[permission]` as a body class.
8. Visit another scope …
=> Update: add helper body css class for user status

utils/crossref/schema/contributors.js
Very simple enhancement that will help a lot with Crossref support. Crossref will now automatically ask authors permission to add pubpub-deposited documents to their profiles.
_To test_
1. Create a pub with four users: a registered user with an ORCID in their profile, a registered user without one, a shadow author without an ORCID, and a shadow author with an ORCID.
2. Release & generate a deposit for the pub
3. Check the XML for the deposit: registered user with ORCID and shadow user with ORCID should have `<ORCID>https://orcid.org/ORCID-ID-NUMBER</ORCID>` as an attribute in the `<person>` record, per [Crossref](https://www.crossref.org/documentation/content-registration/descriptive-metadata/contributors/) docs. The users without ORCID should not have an `<ORCID>` attribute, as an empty …
=> Update: deposit ORCID IDs to crossref

.gitignore, utils/arrays.ts, workers/tasks/export/html.tsx, workers/tasks/export/metadata.ts, workers/tasks/export/styles/printDocument.scss, workers/tasks/export/types.ts
This is a bit of a patch job while we figure out what to actually do here
- Don't pass `communityData.title` in as fallback to `communityData.publishAs`
- Don't show the same string twice in the header (thanks @qweliant)
- Actually pass in a `primaryCollectionKind` value...previously was undefined
=> fix: Patch up logic for what's shown above title in PDF exports

client/components/Editor/views/notePopover.scss, client/components/FormattingBar/buttons.ts, client/containers/Pub/PubDocument/PubDiscussions/Discussion/ThreadComment.tsx, client/containers/Pub/PubDocument/PubDiscussions/Discussion/discussion.scss, client/containers/Pub/PubDocument/PubDiscussions/Discussion/threadComment.scss, client/containers/Pub/PubDocument/PubDiscussions/DiscussionGroup/discussionNav.scss
addresses issue #2058
We recently added RTL to the main editor. This adds RTL directionality to other editors. 
test:
Create text in the layout editor, submission workflow, submission abstract, discussion, citation, and footnotes. Observe RTL persist when rendered
*also fixes some padding added to comments to the right caused by being a child of a prosemirror node
=> enhancement: Add RTL to Additional Editor Fields

client/components/Editor/utils/notes.ts, client/containers/Pub/PubDocument/PubBottom/Notes.tsx, client/containers/Pub/PubDocument/PubBottom/SearchableNoteSection.tsx, client/containers/Pub/usePubNotes.ts, server/utils/citations/structuredCitations.ts, utils/notes.ts, utils/notesCore.ts, workers/tasks/export/SimpleNotesList.tsx, workers/tasks/export/notes.ts, workers/tasks/export/types.ts
Resolves #2082
Pubs have an "inline citation style" that dictates how in-text citation nodes should be displayed. Two common values are `count`, which looks like `[4]` and `author-year`, which looks like `(Deng et al., 2031)`. For styles besides `count`, readers expect to see citations in alphabetical order rather than by order of appearance. We implemented this behavior in #1349, but never added it to the separate codepaths that render citations for HTML/PDF exports. Until now!
Some notes-to-future-self: This PR is reminding me how much complexity there is around citation rendering in PubPub, and how much it needs to be streamlined. Basically there are four steps that happen in places all over the codebase:
1. Grabbing a set of `Note` objects with structured values (like a DOI) from …
=> fix: Alphabetize citations in HTML/PDF exports, where appropriate

package-lock.json
Bring `package-lock.json` into alignment with `npm i` w/ npm version 8.9.0 and node version 18.2.0
=> fix: sync package-lock with npm/node versions

client/components/Layout/LayoutCollectionHeader.tsx
The DOI field gets printed twice in the LayoutCollectionHeader, this PR filters out the DOI in the second printing.
There's probably better ways to do this, but I'll leave that up to your discretion!
This is related to https://github.com/pubpub/pubpub/discussions/1565#discussioncomment-3063822
=> fix: prevent double doi field in Layout header

client/components/FormattingBar/controlComponents/ControlsTable.tsx
Fix a small typo, i don't think a column row is what was meant here
=> fix: typo column row -> header column

client/components/Editor/schemas/math.tsx, package-lock.json, package.json, utils/import/formats.js, workers/tasks/import/rules.ts
Fixes bug [pointed out here](https://github.com/pubpub/pubpub/discussions/1869#discussioncomment-3186517) where importing from markdown wasn't working so well.
_test plan_
+ write a pub with both inline and display math nodes
+ export that pub to md
+ import the md
+ check for consistency
+ repeat above steps for LaTeX filetype
=> fix: unbreak pandox math node handling, bump prosemirror-pandoc

server/routes/sitemap.ts
Resolves #2130 
This PR adds a `sitemap.xml` file to the root of communities that serves as a simple alias to `sitemap-index.xml`.
_Test plan_
- Navigate to the `/sitemap.xml` path of any community. It's response should match `/sitemap-index.xml`
=> feat: add sitemap.xml endpoint

client/components/TitleEditor/TitleEditor.tsx, client/containers/DashboardSettings/PubSettings/PubSettings.tsx, server/pub/queries.ts
In order to launch rich text titles for all of PubPub, we need to add this capability to Pub Settings. This turns out to be pretty easy! Adding the `.bp3-input` class to the `TitleEditor` component's rendered div styles it perfectly. The only other substantial change I made was to add an `onInput` callback to the `TitleEditor` so we can get changes on keypress instead of blur, and a new check in the Pub PUT handler to convert `htmlTitle` to `title` by stripping tags.
_Test plan:_
- Visit Pub Settings for a Pub and verify that you can use bold and italics in the title, and persist those changes. The title at the top of the dashboard won't change, but that's an existing issue.
- Also make sure the `TitleEditor` in the Pub header continues to work.
=> update: Add HTML title editor to Pub Settings

server/utils/ssr.tsx
Fixes metadata for things that have ISSNs so it actually shows up.
_To test_
1. Visit a pub that's in a journal issue collection that has an ISSN (electronic or print) entered in the settings.
2. Open the inspector and make sure the `<meta name="citation_issn" content="XXXX-XXXX" />` tag displays properly, with the ISSN you entered in step 1.
=> fix: use right key for issn meta display

client/components/Editor/utils/notes.ts, client/containers/Pub/usePubNotes.ts, server/utils/citations/structuredCitations.ts, utils/notes.ts, workers/tasks/export/html.tsx, workers/tasks/export/notes.ts, workers/tasks/export/pandoc.ts, workers/tasks/export/types.ts, workers/tasks/import/rules.ts
Resolves #2146
This fixes a problem where identical `citation` nodes in a Pub document are de-duped "too early" in `getNotesByKind()`, which prevents them from being processed by `getPandocNotesById()`. We want to de-dupe a list of notes only shortly before displaying it to users, so I've moved that functionality into `renderNotesForListing()`.
_Test plan:_
- Create a Pub with several identical citation nodes (feel free to copy [this one](https://openpresstiu.pubpub.org/pub/kritisch-wetenschappelijk-4/release/1?readingCollection=19a3c21e) from the linked bug report)
- Make sure that both Pandoc (JATS, Markdown, ...) and non-Pandoc (HTML) exports work propertly
- Verify that identical citations are de-duped properly in both the Pub footer and HTML exports (easiest to see when they are …
=> fix: De-dupe notes in `renderNotesForListing()` instead of `getNotesByKind()`

client/components/DevCommunitySwitcherMenu/DevCommunitySwitcherMenu.tsx, client/components/DevCommunitySwitcherMenu/DevCommunitySwitcherMenuItems.tsx, client/components/DevCommunitySwitcherMenu/communities.ts, client/components/DevCommunitySwitcherMenu/index.ts, client/components/GlobalControls/GlobalControls.tsx, client/components/ScopeDropdown/ScopeDropdown.tsx, client/components/index.ts, client/containers/App/SideMenu/ScopePicker.tsx, server/apiRoutes.ts, server/dev/api.ts, server/utils/initData.ts, server/utils/routes.ts
We need an easy way to examine "base PubPub" on dev. We desperately need a way to switch the Community we're looking at on dev without updating the `PUBPUB_LOCAL_COMMUNITY` env var and restarting the dev server. 
So I made one! You can access it from two places:
From the `ScopeDropdown` inside a Community...
Or from a new menu on "base PubPub"...
_Test plan:_
Check that:
- The switcher works (preset Communities and custom input) from a Community
- It also takes you to base PubPub
- It takes you back to a Community from base PubPub
- If you enter an invalid Community subdomain, it will not accept it
- (On prod) This whole thing does not appear and the `/api/dev` route errors out.
=> dev: Community switcher for dev environment

client/components/Editor/schemas/math.tsx, package-lock.json, package.json, server/editor/api.ts, utils/katex.ts, workers/tasks/import/rules.ts
See https://github.com/KaTeX/KaTeX/issues/3680 for a detailed writeup of our problem. I'm likely to propose a patch to KaTeX at some point, but to keep PubPub afloat we make the following changes here:
1. Fork `@benrbray/prosemirror-math` so that it catches all errors that KaTeX could throw (our changes [here](https://github.com/pubpub/prosemirror-math/commit/ccf5737f75485925a25515818a1516ee59e76f90))
2. Write our own wrapper around KaTeX that also catches all errors
_Test plan:_
- Add a suspicious Unicode character like `𝛾` to a math node
- Make sure it doesn't immediately brick the Pub
- Refresh and make sure it doesn't brick the server-side render of the Pub
=> hack: Add extra error handling (and patched prosemirror-math) to recover from bad chars in KaTeX

client/components/ScopeDropdown/ScopeDropdown.tsx, client/components/ScopeDropdown/scopeDropdown.scss, server/utils/queryHelpers/scopeGet.ts
Resolves #788.
This PR basically does two things:
1. If a Pub is in a Collection and that collection is not 'Active', grabs the primary or first one and puts it as a scope in the dashboard menu.
2. If you can manage the community, collection, or Pub, adds icons to appropriate levels of the dashboard menu to make it more convenient to jump to various settings pages.
It could probably be released right now and be fine. Some outstanding issues/questions for a follow:
- We should talk about which settings to show for which levels. Collections are really long! And I didn't even include submissions, which I probably should?
- Also, it probably doesn't need to show the globe icon if you are on the public-facing version of a collection/page/pub already, but figuring that out felt complex.
_Test …
=> Enhance: Dashboard menu navigation

client/components/ScopeDropdown/ScopeDropdown.tsx, server/utils/queryHelpers/scopeGet.ts
Actually grabs the first or primary collection, and in so doing moves us closer to doing it all in ScopeGet.
_To Test_
1. Visit a pub where the primary collection is not the first one in the ordered list and make sure the primary still shows as the collection in the dash menu.
2. Visit a pub where there is no primary collections and all other collections are ordered in non-alpha order and make sure the first ordered collection shows in the dash menu.
=> Fix: actual first or primary

client/components/Editor/schemas/reference.ts, client/components/Editor/utils/references.ts
Makes block equations reference-able.
_Test plan_
1. Go to/create a pub with a math node
2. reference that math node
3. sha-bayum
=> fix: add nodetype patch for referencing block equations

client/containers/Pub/PubHeader/Review/review.scss
the color property of children of `.pub-header-background` can be overwritten. specifying the top-level color for the `.review-component selector` fixes this. 
also there was code to specify the icon color of the submit button. we thought it was unnecessary but it is. 
Before: 
After:
=> bug: Prevent css override

.eslintignore
Takes config.js out of .eslintignore so it gets linted.
=> fix: eslintignore

package.json
like it says on the tin
brings `prosemirror-history` compatibility to the `prosemirror-math` plugin, enabling undo and redo while remaining within a math node selection.
=> bump forked prosemirror-math to get history plugin

server/routes/noMatch.tsx, server/routes/search.tsx, server/routes/user.tsx
addresses #2264, bringing the community custom css to search, 404, and profile routes
_test plan_
1. set some identifiable custom css from the community settings (e.g. set background-color on html)
2. navigate to each of the following routes, confirm presence of custom CSS:
* [Search](https://demo.pubpub.org/search)
* [404](https://demo.pubpub.org/this-cant-be-a-real-page)
* [User profile pages](demo://tghp.pubpub.org/user/pubpub-team)
=> add custom CSS retrieval to search, 404, and user profile routes

package-lock.json, package.json, server/pub/queries.ts
Quick one!
_Test plan:_
- Create a new Pub
- Change its title to something with an ampersand in it
- Verify that after you refresh the page, the Pub title includes `&` and not `&amp;`
=> fix: Unescape entities like &amp; when updating Pub titles

client/components/PubPreview/PubPreview.tsx, server/routes/user.tsx
Currently broken because they attempt to load custom CSS scripts even on WWW. This fixes that, and also adds a quick fix for cases where there's no community header image.
_Test plan_
- Visit a profile on www, make sure it loads
- Visit a profile not on www with some custom css, make sure it loads with custom CSS
- Make sure that Pubs from a community where there's no header image load as a block with accentColorDark as the background and accentColorLight as the text.
=> fix: Profiles on www

client/components/FileUploadButton/fileUploadButton.scss, client/containers/Pub/PubDocument/PubDocument.tsx, client/containers/Pub/PubHeader/DraftReleaseButtons.tsx, client/containers/Pub/PubHeader/PubHeader.tsx, client/containers/Pub/PubHeader/TitleGroup.tsx, client/containers/Pub/usePubBodyState.ts, client/containers/Pub/usePubSubmissionState.ts, server/routes/pubDocument.tsx, server/utils/queryHelpers/pubGet.ts, server/utils/queryHelpers/pubSanitize.ts, server/utils/queryHelpers/scopeGet.ts, types/pub.ts
Resolves #2295 
The error described therein turned out to be down to an intentional line of code in `getScope()`:
```ts
canCreateReviews = !activePub.submission && ...
```
I added this check while developing Submissions because at the time the feature was intended to be mutually exclusive with Reviews — this is no longer the case. The practical effect of the change at the time was to hide the "Request Release" button in the Pub header. I think we want to continue to hide that, so I've moved this check to the frontend.
_Test plan:_
- Visit a Collection with open submissions to create a Spub
- Verify that the Request Release button is not shown
- (optional) Complete the submission process
- Visit `/pub/<slug>/review/1` and verify that you can add a review from the little dropdown bit
I also …
=> fix: Allow reviews to be submitted on Spubs

client/containers/User/UserNav.tsx
This allows pubs to style based on the count via `[data-tab-related-count="0"]`, or use it via `attr(data-tab-related-count)` in CSS. 
We want it for the latter, so that we can change the wording here, but still have the count
(e.g. `:before { content: 'Custom Title (' attr(data-tab-related-count) ')'; }`
This only changes the way this content is output and doesn't change any behaviour, the result to the user will be indistinguishable but increases the surface area for extendibility.
=> Add data-tab-related-count attribute to allow access in CSS to tabs in User Profile

client/components/Layout/LayoutCollectionHeader.tsx, server/utils/ssr.tsx
Improves Collection-level metadata for Zotero/Mendeley/etc. and fixes a bug where DOIs were appearing twice in collection headers.
_Test plan_
- Visit any collection with a DOI and make sure it only shows once in the collection header block
- Visit Conference and Issue collections with all metadata filled in. Make sure: citation_doi and citation_date HTML metadata are set according to the collection metadata.
- Visit a Book collection. Make sure citation_title, og:title, citation_book_title, citation_DOI are set according to metadata. Make sure og:type is set to 'book'.
- Visit a tag collection and make sure no metadata is set except basic og metadata.
- Visit pages and pubs in and out of collections and make sure they load as expected.
Thanks to @tefkah for initial pull request and …
=> fix/update: add metadata for collections and fix filter

client/components/Editor/plugins/code.ts, client/components/Editor/plugins/index.ts, client/components/Editor/plugins/keymap.ts, client/components/Editor/schemas/base.ts, client/components/Editor/styles/base.scss, client/components/Editor/styles/code.scss, client/components/Editor/utils/nodes.ts, client/components/FormattingBar/buttons.ts, client/containers/Pub/PubDocument/PubInlineMenu.tsx, package-lock.json, package.json
We are going with this approach!
_Test Plan_
create code block in a pub and play with them generally. Steps below. NB: the code blocks behave as a text block, which is to say, they are not deletable if they are the only text block in the document just as the only `paragraph` block would not be deletable. We can change this behavior, but it would be a departure from block behavior to accommodate image-block-like behavior.
Make sure to hit each of the below:
+ create a code block by typing three backticks to enter it
+ create a code block by clicking the lego-block-shaped codeblock toggle button in the formatting bar
+ create a code block by selecting `code` from the dropdown at the left edge of the formatting bar
+ exit the codeblock by pressing `return` from an empty line in the codeblock …
=> feature: code blocks w/ plugin

client/containers/DashboardOverview/CollectionOverview/PubMenu.tsx, utils/collections/primary.ts
Currently, any _non-tag, public Collection_ is eligible to act as a Pub's Primary Collection. You can choose which of those Collections will be primary in Pub settings:
This change removes the requirement that the Collection be public. This stipulation was originally added to prevent leakage of private Collection information in Crossref deposits and exports. But in practice, this usually doesn't matter. If a Pub has a Crossref deposit or PDFs floating around in public, "the cat is out of the bag" and it doesn't matter if a private Collection title or URL makes it into the world.
Allowing a Collection to be primary before it goes public makes it much easier for Community admins to reason about how its Pubs will behave, and — here's the kicker — it's absolutely a requirement to enable …
=> update: Allow private Collections to act as Primary Collection

server/routes/pubDocument.tsx
addresses #2282
Adds canonical url to pub so that all releases carry the correct target for the most-recent-release url.
+ open a 2nd or 3rd release for a pub
+ inspect the `<head>` content of the pub in browser
+ confirm presence of line like the following:
`<link rel="canonical" href="http://localhost:9876/pub/b439jo24">`
=> enhancement: add canonical url to pub metadata

client/components/ScopeDropdown/ScopeDropdown.tsx
addresses #2302
Globe icon for Community scope now points to base url, i.e. `''`.
=> bugfix: community ScopeDropdown globe icon link

workers/tasks/export/notes.ts, workers/tasks/import/rules.ts
Resolves #2296
There is a goof (in recent code that I wrote) that double-adds the `unstructuredValue` of a footnote (the rich text content) instead of including `structuredValue` (from Cite.js) as well. This fixes that. We also strip most of the HTML content from the structured value so it appears cleanly in Markdown.
_Test plan:_
Create a Pub containing a footnote with a structured and unstructured value. Export it to Markdown and Word and verify that both are shown in the footnote.
=> fix: Include `structuredValue` as HTML in Pandoc footnotes

package-lock.json, package.json
[`chokidar`](https://www.npmjs.com/package/chokidar) an npm package that abstracts over `fs.watchFile()` and some other platform-specific APIs for detecting when files change. We use it in the hot-reloading code, which is recently giving us trouble. I updated it to the latest version, and things seem a _little_ better, though I don't know if this is really the fix. Still, it's harmless to try!
_Test plan:_
Start your dev server and make sure hot reloading of server-side code is happening!
=> dev: Update `chokidar`

tsconfig.json
See the inline comment — this is specifically to appease VSCode and I'm hoping that (1) it has no effect on our builds and (2) we can remove it eventually.
_Test plan:_
If it builds in CI, it's good to go!
=> dev: Add node_modules and dist excludes to tsconfig to help VSCode

client/containers/DashboardSettings/PubSettings/Doi.tsx, client/containers/DashboardSettings/PubSettings/PubSettings.tsx, server/routes/dashboardSettings.tsx
Resolves #2343
Another facets merge issue here :/ Looks like we lost the `depositTarget` that was being passed down into `PubSettings`. In the future we could consider loading it as an association to `initialData.community` instead, but I like that we're only loading it precisely where it's needed here.
_Test plan:_
- On your devserver, switch to a Community with an associated `DepositTarget` (like `mitp-arch`)
- Create and release a new Pub
- From Pub Settings, start the process of depositing the Pub and verify that you can customize the DOI suffix with this control:
=> fix: Pass a DepositTarget into DOI settings

client/components/Popover/PopoverButton.tsx, client/containers/Pub/PubDocument/PubBottom/LicenseSection.tsx, client/containers/Pub/PubHeader/PubHeaderContent.tsx, client/containers/Pub/PubHeader/Review/Review.tsx, client/containers/Pub/PubHeader/Review/ReviewEditor.tsx, client/containers/Pub/PubHeader/Review/review.scss, client/containers/Pub/PubHeader/ReviewHeaderSticky.tsx, client/containers/Pub/PubHeader/UtilityButtons.tsx, client/containers/Pub/PubHeader/collections/CollectionsBar.tsx
Resolves #2334
A recent code change — I'm betting the facets merge — changed the Pub header so it has `overflow: hidden` set in a way that cuts off the new Review dropdown in the header. The best way to solve this problem is to put the `<Review>` component in a `<PopoverButton>` so it isn't a DOM child of the Pub header  — this method provides better keyboard accessibility as well.
I thought this would be a simple fix:
```tsx
<PopoverButton component={() => <Review {...} />} />
```
I just added some new `<FacetEditors>` to buttons in exactly the same way! But this caused the review editor to blur on every keystroke, making it unusably janky. So I checked to see how often the `<Review>` component was mounting:
```ts
// in Review.tsx
useEffect(() => console.log("<Review> mounted"), []);
``` …
=> fix: Launch the Review editor with a `<PopoverButton>`

server/export/queries.ts, server/release/queries.ts, server/routes/pubDownloads.ts
Resolves #2333 by making sure we regenerate a PDF export for a Pub's latest release if we are, for whatever reason, unable to retrieve one when the Pub's `/download` route is hit.
_Test plan:_
Create a Pub, release it, and then remove all of its exports (by `pubId` in the `Exports` table). Then visit `/pub/<slug>/download` and verify that, shortly after, those exports are recreated (it should be sufficient to check for new rows in the `Exports` table).
=> Generate exports if discovered missing when `/download` is hit

client/components/PubShareDialog/PubShareDialog.tsx, server/routes/pubDocument.tsx, server/utils/queryHelpers/pubGet.ts, server/utils/queryHelpers/pubSanitize.ts, types/pub.ts, utils/canonicalUrls.js
adressess #2357 #2363 
This removes duplicate routes and provides a generic share link for commenters. 
test plan:
Release a pub.
Go to a draft pub. Grab the review comment link
make sure the link is in the form `/pub/<slug>?access=<commentHash>`
navigate to the route.
as both a logged-in and logged-out user make comments.
=> enhancement: Comment Share URL and Routing

client/components/ScopeDropdown/ScopeDropdown.tsx
solves #2418
tooltips are now in the navigation dropdown
=> Adds Tooltips to Components

client/containers/CommunityServices/CommunityServices.tsx
This update adds four options to the services menu available at `/community-services`: Copyediting, Text to Audio, Archiving & Indexing, and OER Course Presentations.
=> update: Add new services menu items

server/routes/robots.ts
Bots seem to be caught not infrequently crawling their way through redirect loops on our login page, which ends up accidentally and temporarily DDOSing us.
This change to robots.txt allows bots to request `/login`, but not `/login?redirect=*`.
We should also make it so those loops can't happen by not allowing login redirects to `/login`, but I'll leave that to the pros.
Tested with: https://technicalseo.com/tools/robots-txt/
Example of a route requested by a bot during one of these moments:
```
/login?redirect=%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect%3D%2Flogin%3Fredirect% …
```
=> fix: disallow bot requests to login with redirect

client/components/Editor/schemas/iframe.ts, client/components/FormattingBar/media/MediaCodepen.tsx, client/components/FormattingBar/media/MediaIframe.tsx, client/components/FormattingBar/media/MediaVimeo.tsx, client/components/FormattingBar/media/MediaYoutube.tsx
Resolves #2360
Adds `allowfullscreen="true"` to iframes inserted with the editor (including youtube, vimeo etc.).
To test, compare: https://demo.duqduq.org/pub/kxf724hk/draft vs https://pubpub-pipel-kalilsn-al-5vkypc.herokuapp.com/pub/kxf724hk/draft
=> Allow fullscreen on iframe embeds

client/components/Editor/styles/table.scss
Adds some pretty meh table styling for mobile, mostly by setting `overflow-x: scroll` on the `tableWrapper` and a sane min-width for th and td (140px). I feel like there has to be a better way to do this, but the only other thing I can figure out is to set `white-space: nowrap` on table cells, which has the effect of...you guessed it...never wrapping, which is not good.
So, this effectively sets the width of every column to the min-width value (currently 140px), regardless of whether a custom width is set, which seems not great but potentially unavoidable (unless we set the table cells not to wrap at all).
_Test plan_
1. Create a table and don't set any column or table widths
2. View on mobile
3. Make sure columns are at least 140px wide
4. Set the widths of some of the columns, and of …
=> fix/enhancement: Mobile table styling

utils/notes.ts
addresses #2383 
Now, all of the footnotes will show
test plan: using this [doc](https://docs.google.com/document/d/1qjnN17jUp8_-iVXVi7ojH0XYzce0MoxwvEOS_oORPs0/edit?usp=sharing) you can test that there are 396 footnotes when importing to pubpub
before there would have only been 3
=> bug: Footnotes Won't be Deduped

client/components/AttributionEditor/AttributionEditor.tsx, client/components/AttributionEditor/AttributionRow.tsx, client/components/CollectionAttributionEditor/CollectionAttributionEditor.tsx, client/components/LayoutEditor/LayoutEditorCollectionHeader/PreviewElements.tsx, client/components/LayoutEditor/LayoutEditorPubs/PreviewElements.tsx, client/components/PubEdge/PubEdgeEditor.tsx, client/containers/DashboardEdges/DashboardEdges.tsx, client/containers/DashboardOverview/CollectionOverview/DashboardCollectionOverview.tsx, client/containers/Pub/PubDocument/PubBottom/Discussions/LabelFilter.tsx, client/containers/Pub/PubDocument/PubDiscussions/Discussion/LabelSelect.tsx, client/containers/Pub/PubDocument/PubDiscussions/Discussion/ManageTools.tsx, client/containers/Pub/PubDocument/PubFileImport/MetadataEditor.tsx, client/containers/Pub/PubHeader/BylineEditButton.tsx, client/containers/Pub/PubHeader/TitleGroup.tsx, client/containers/User/UserNav.tsx, server/discussion/__tests__/api.test.ts, server/pub/__tests__/queryMany.test.ts
Addresses #2261 - eliminates "author" in all instances where a wider range of contributor roles should be represented, and implements clean attribution/contribution taxonomy.
=> Kill author and implement contributor taxonomy

package-lock.json, package.json, server/depositTarget/queries.ts, server/doi/queries.ts, server/doi/submit.ts, server/editor/api.ts, server/login/api.ts, server/logout/api.ts, server/middleware/deduplicateSlash.ts, server/passwordReset/api.ts, server/review/api.ts, server/routes/adminDashboard.tsx, server/routes/dashboardCollectionOverview.tsx, server/routes/dashboardCommunityOverview.tsx, server/routes/pubRedirects.ts, server/routes/superAdminDashboard.tsx, server/search/api.ts, server/server.ts, server/spamTag/api.ts, server/workerTask/api.ts, types/global.d.ts, utils/superAdmin.ts
Closes #2446 
This PR fixes a couple of minor vulnerabilities:
1. Removes a potential phising attack vector where PubPub would redirect to arbitrary URLs when the pathname began with multiple slashes and were trailed by a single slash, e.g. `http://pubpub.org//google.com/`.
2. Filters sensitive properties from `DepositTarget` models before they are sent to the client when rendering dashboard settings pages (already privileged routes).
I also added `@types/express` so we have typing on our express middleware and route handlers. Still need to type the `wrap` function though.
=> fix: redirect issue

server/utils/ssr.tsx
Due to a change in #2307, some Pubs are being given their collections' `dc.title`, `og:title`, and `citation_title`. This lead to some citation managers and scrapers grabbing the collection title instead of the pub title. The behavior we want is:
- If the resource is a Pub, we use its title (without context) for all three.
- If the resource is a collection that has a title, we use the collection title (without context).
This PR accomplishes that.
_Test plan_
1. Visit a pub in a collection. Verify that:
- The page title and twitter title are titleWithContext (`pubTitle • communityTitle`).
- The og:title and dc.title are the pub title (without context)
1. Visit a pub not in a collection. Verify that it loads and that the titles are the same as above.
1. Visit a collection page. Verify that …
=> Fix: title handling in meta tags

client/components/GlobalControls/LoginButton.tsx
Addresses #2438
The long redirect chain in that issue can be recreated by going to the login page and then repeatedly clicking the login button. However, in my testing, a browser will not actually follow beyond the first one, so I doubt it's causing our mysterious timeouts.
Let me know if this isn't the right solution, but I don't really see a reason to have the login button on the login page or the signup page. Removing those should prevent bots (or inattentive humans) from ending up at those URLs in the first place.
=> Hide login button on login pages

client/containers/App/app.scss, client/containers/Pub/PubDocument/pubBody.scss, client/styles/base.scss
#2351 
This PR fixes the CSS intended to prevent pubpub from being wider than the screen, which didn't work on my browsers. Now if an element (really just math as far as I can tell) is wider than the viewport, it will have internal scrollbars, but the page itself will not expand.
This pub has some examples of content that overflows on small screens:
[duqduq version](https://demo.duqduq.org/pub/hilwxpnd/release/4)
[review app version](https://pubpub-pipel-kalilsn-ov-bfcnoe.herokuapp.com//pub/hilwxpnd/release/4)
Feedback I'm looking for:
- Are there other places where we might need to add an explicit `overflow-x: auto`? It seems like most elements from the editor get wrapped in a `<p>` tag, but I'm not so sure about other parts of the site.
- At intermediate sizes where the discussions are …
=> Improve mobile experience for content wider than the screen

server/routes/legal.tsx
Addresses #2445 
Explicitly specifies the routes under `/legal` that pubpub responds to ~since we weren't using the `:tab` parameter anyways.~ <-- untrue as Gabe pointed out below.
To test:
Working legal pages: https://pubpub-pipel-kalilsn-le-xv3ufv.herokuapp.com/legal/terms
404 from a bad route under legal: https://pubpub-pipel-kalilsn-le-xv3ufv.herokuapp.com/legal/term
=> 404 for nonexistent tabs under /legal

client/containers/DashboardSettings/PubSettings/Doi.tsx, server/depositTarget/queries.ts, types/depositTarget.ts
Resolves #2463.
A PubPub-managed Crossref deposit target has a username.
We disable depositing through PubPub if the community has an unmanaged deposit target. Otherwise, PubPub will deposit using the community's configured Crossref credentials (and an optional, customizable prefix). We fall back to PubPub's default prefix and credentials if the community does not have a deposit target.
=> fix: ignore credentials when disabling deposits due to unmanaged prefix

server/middleware/__tests__/deduplicateSlash.test.ts, server/middleware/deduplicateSlash.ts
Fixes #2468
Editor embeds weren't working because those requests always contained duplicate slashes (`https://`) within the query strings, e.g. `/api/editor/embed?type=youtube&input=https://www.youtube.com/watch?v=PL9iMPx9CpQ`. Since the deduplicateSlashes middleware searches the whole req.url (which is confusingly not a url) string for slashes, but only replaces them in the path. This caused our middleware to send a redirect back to the same URL, creating an infinite loop.
=> Only redirect from deduplicateSlash middleware when slashes are removed

server/activityItem/fetch.ts, server/activityItem/queries.ts, server/discussion/__tests__/api.test.ts, server/discussion/queries.ts, server/review/queries.ts, server/thread/queries.ts, server/threadComment/hooks.ts, server/threadComment/queries.ts, server/userNotification/__tests__/api.test.ts, types/activity/thread.ts, types/thread.ts, utils/crossref/__tests__/createDeposit.test.js
Resolves #2469. Back in #2289 we added a new abstraction that creates a new `Thread` and a `ThreadComment` in the same query function. This is a really good idea, and for months I didn't notice a small problem. When a `ThreadComment` is created, a [Sequelize hook](https://sequelize.org/docs/v6/other-topics/hooks/) fires that wants to create a `pub-discussion-comment-added` item. But unless the parent thread is already associated with a `Discussion`, we can't do that, and no item is created. So we really need to create a Discussion and a Thread and associate the two before we create a comment.
There are other potential fixes here (deferring the hook somehow, or maybe adding another hook to `Discussion.afterCreate`) but for now I've elected to re-order the creation of these items, and add a …
=> fix: Make sure ActivityItem is created with new Discussion

client/components/Editor/plugins/inputRules.ts
addresses #2476 
Links will now be automatically created when typing one
https://user-images.githubusercontent.com/34730449/216124349-29aa1540-3a4c-4619-b8ad-5eb6f49510e6.mov
test plan:
open a pub and type out a link.
the link inside the `ControlLink` editor should be the same as the one you typed
now type an email.
be sure the email has a mailto scheme for the email you typed out
=> Create Link While Typing

server/routes/authenticate.tsx, server/user/model.ts, tools/migrations/2023_04_17_addAuthRedirect.js, types/user.ts
#2598
Perform oauth flow from 2 consecutive communities
1. log in as community-picker-enabled user (e.g. team@pubpub.org)
2. navigate to user privacy settings
3. if zotero integration is currently active, remove it
4. click 'Activate' for zotero integration
5. proceed through zotero oauth login + screens (credentials available in onepass)
6. after login, you should be returned to user privacy settings page within same community
7. pick a new community
8. return to user privacy settings page
9. zotero integration _should_ be active
10. remove zotero integration
11. perform oauth flow again
12. you should be returned from zotero back to most recently visited community
=> store redirect host on user model in oauth flow

server/models.ts
#2585 
**Note: make sure to update your local config file with new connection pool URLs**
Mostly a smoke test
- Visit the test app and make sure it loads.
- Visit a few different communities, including www.
- Make sure pubs load, are editable, and can be released
- Make sure pages and layouts can be edited
- Visit a route with a lot of pubs on a page and make sure it loads (e.g. /user/gabriel-stein on www)
- Make sure tests run properly locally (should not use connection pool)
- Used some heroku CLI commands to add the pooling URL to our apps, described here: https://devcenter.heroku.com/articles/postgres-connection-pooling
- Had to manually add the env variables to review apps and the test suite. Should double-check that those target the dev db.
- Updated config.js with new ones. Please …
=> dev: Replace db url with connection pool URL

client/components/Editor/styles/figure.scss
https://github.com/pubpub/pubpub/issues/2624 (will close manually once this is deployed).
On the review instance (or duqduq after this is merged), visit a pub with an image and a link set, and make sure adjusting its size works properly outside of breakout mode. https://demo.duqduq.org/pub/wttb47yk/draft will show this failing!
This is reverting a change from https://github.com/pubpub/pubpub/pull/2611
=> Revert figure css change

server/login/api.ts, server/logout/api.ts
Adds a cookie for caching when logged in, and changes it when logged out. Went this route instead of a login cookie because it allows us to override it in the future if needed for caching purposes, rather than tying exclusively to login. Decided not to clear it on logout because it allows us to target it specifically in caching controls if needed (though the default will be to cache on pages, collections, and user profiles unless it sees pp-no-cache set).
Closes #2617 
1. Visit test deployment
2. Logout and clear cookies
3. Login
4. Verify that `pp-cache` is set to `pp-no-cache`
5. Logout
6. Verify that `pp-cache` is set to `pp-cache`
7. Clear cookies
8. Create a new test account
9. Login and verify cookie was set on first login.
I was unable to modify the existing cookie because it's …
=> feat: drop cookie on login/logout for caching

client/components/Editor/styles/suggestedEdits.scss
#2634 
Visit Safari browser and another browser and view http://localhost:9876/pub/pegl1ofe/draft
be sure the text looks like below in both browsers
the neater one line webkit solution did not work so i split them up
https://stackoverflow.com/questions/51181010/text-decoration-line-through-css-does-not-work-on-safari-with-my-completed-cla
=> Safari CSS Webkit Issue

client/components/Editor/schemas/video.ts, client/components/FormattingBar/controlComponents/ControlsMedia/ControlsMedia.tsx
Resolves #2618
- Open a pub draft
- Add a video (or choose an existing native video node)
- Turn loop on and off, test that the video does or does not repeat
Loop option checked:
Unchecked:
=> Add loop video option

client/containers/Login/Login.tsx, server/login/api.ts
Makes two improvements to the cache cookie.
1. Sets a cachebreaker on login redirects so that logged in users don't hit the browser cache on their first redirect and appear logged out. This was happening because, by default, most browsers will hit local cache when using `window.location` to redirect.
2. Adds a wildcard domain to cache cookies (e,g, `*.pubpub.org`). Previously, they would only apply to the subdomain where the user logged in.
n/a
In the test app:
1. Logout and clear cookies.
2. Open the dev console and preserve history in the networking pane.
3. Login.
4. Make sure the page contains a cachebuster
6. Verify that the `pp-cache` cookie is set to `pp-no-cache` and the domain is `.[domain]` (e.g. `.pubpub.org`)
7. In network history, verify that the request headers for the …
=> dev: Cache cookie tweaks

server/login/api.ts, server/logout/api.ts
Two more cookie fixes: first, uses hostname to get the actual hostname, not the host, which is for some reason always pubpub.org. Then, uses that hostname to unset the cookie as well.
n/a
- Load locally
- Logout
- Clear cookies
- Login
- Verify that the pp-cache cookie has the domain localhost
- Logout, verify that the domain is still localhost
- Repeat the above for the test app. Make sure the domain for the cookie is the supplied test app domain
Will need to be tested on duqduq before entering prod.
=> use hostname instead of host, add to logout

client/components/Editor/plugins/inputRules.ts, client/components/Editor/plugins/keymap.ts
Resolves #2518 
On the review instance or a local branch, navigate to a pub editor and test:
- typing a url or email address and pressing space
- typing a url or email address and pressing enter
Also be sure to test these with and without content preceding and following (like `example.comandarunonsentence`, then press enter after `.com`, or `example.com<inline math node>`)
=> Run link input rule on enter

client/components/LayoutEditor/LayoutEditor.tsx, client/components/LayoutEditor/useLayoutPubs.ts, client/containers/DashboardCollectionLayout/DashboardCollectionLayout.tsx, client/containers/DashboardPage/DashboardPage.tsx, package-lock.json, server/collection/model.ts, server/collection/permissions.ts, server/layout/api.ts, server/page/model.ts, server/page/permissions.ts, server/routes/collection.tsx, server/routes/dashboardCollectionLayout.tsx, server/utils/layouts/layoutPubs.ts, server/utils/queryHelpers/pageGet.ts, tools/layoutcheck/check.ts, tools/migrations/2023_05_08_addLayoutAllowsDuplicatePubs.js, types/collection.ts, types/page.ts
Resolves #2619
1. Navigate to a Page layout in the dashboard (e.g. [Home zone](https://pubpub-pipel-feat-layou-fn9odf.herokuapp.com/dash/pages/home)) and flip on the _Allow duplicate Pubs_ option.
2. Confirm that Pubs are no longer de-duplicated between Pub blocks within the layout editor.
3. Click save changes.
4. Vistit the page and confirm that Pubs are no longer de-duplicated on the Page.
5. Repeat steps 1-4 for a Collection layout with Pub blocks.
=> feat: add duplicate pubs option for page and collection layouts

client/components/GlobalControls/UserMenu.tsx, server/login/api.ts, server/logout/api.ts
- Adds a cachebreaker to the logout redirect.
- Uses env variables plus hostnames to set domains for cache cookies.
n/a
***Will need to be smoke tested on duqduq***
- On the test app, clear cookies (or use incognito) and login
- Make sure `pp-cache=pp-no-cache` cookie appears, and the domain is the same as the test app
- Logout, make sure url has a cachebreaker query param is set on the URL and the `pp-cache=cache` cookie appears.
To smoke test on duqduq: cache cookie domain should be set to `.duqduq.org`, except for the duqduqtest.underlay.org custom domain
To smoke test on prod: cache cookie domain should be set to `.pubpub.org`, except for custom domains
For some reason, we rewrite the request header to always be pubpub.org, so we can't use the request object to set the cache header. …
=> Dev: cachebreaker for logout, cache cookie domain fix

client/containers/User/UserEdit.tsx
Fixes #2663
Also fixes a console error where we were calling onblur on every field, even though only ORCID needs it for validation.
- Make sure you can edit and save a user profile.
- Make sure the ORCID field validates correctly.
- Make sure you can edit and save all other user profile fields.
Somewhere along the line, react changed the handling of events for textarea fields so that the synthetic events they generate `onChange` are recycled unpredictably, meaning they can't be used as-is in asynchronous functions like useState hooks (see [this blog](https://medium.com/trabe/react-syntheticevent-reuse-889cd52981b6)). Instead, best practice is to pull values out into variables prior to using them in hooks.
=> fix: User bio profile editing

server/login/api.ts
Last thing I swear — adds an expiry to the cache cookie for 30 days, which is the same as the login cookie. 
By default, if you don't set an expiry the cookie will be a session cookie, meaning it clears when the user's session ends. Setting the expiry to match the login cookie prevents a rare scenario that could cause cache leakage where a user is logged in and has the no-cache cookie, then closes the browser and visits again the next day when the cookie has expired. This would mean the user is eligible to be served the page from cache, even though they're logged in. That's not the end of the world, but if the user visited when the cache for the page had become stale, their logged in page would then become the cached page, which would leak their profile photo.
n/a
1. Visit the test app
2. …
=> fix: Set cache cookie expiry

tools/5to6/util/createFirebaseClient.js
One usage of the old googleapis library wasn't fully updated in https://github.com/pubpub/pubpub/pull/2158 which breaks `npm run tools syncDevFirebase`. This PR finishes that change.
=> Use jwt client correctly

client/components/Editor/plugins/suggestedEdits/appendTransaction/textAndStructure.ts, client/components/Editor/plugins/suggestedEdits/resolve.ts, client/components/Editor/styles/main.scss, client/components/Editor/styles/suggestedEdits.scss, client/components/FormattingBar/hooks/useControlsState.ts, package-lock.json, package.json
Fixes a number of bad interactions between suggested edits mode and lists by
- Changing the algorithm we use to restore deleted content:
- Previously it worked from the end of the document to the beginning, restoring any content removed by the user, then marking it as a suggested removal, while assuming that earlier changed positions in the document would be unaffected by these restorations
- Now it works in the opposite order, explicitly mapping the changed positions each time the document is modified
- This properly handles complex steps that result in document lifts/merges/joins etc., like deleting the last item in a list, or pressing enter inside of an empty list item (which removes the item and creates a new paragraph outside the list).
- Updating prosemirror-schema-list (take a look …
=> Fix list behavior (mostly)

client/components/Editor/plugins/suggestedEdits/resolve.ts
- This fixes the suggestion buttons always showing as enabled when selecting a range of the document, even if it had no suggestions. 
- It also reduces the likelihood of any bugs causing editor crashes by modifying how the formatting bar checks if the accept/reject suggestions buttons should be enabled. Now those calls will no longer actually try resolving suggestions (and discarding the transaction) and will just check that the selection intersects with a suggestion
- This will be useful for other work we're doing, both on our UI and to make math blocks function properly.
Try a few different selections (cursor, range, node) both with and without suggestions inside. Ensure the buttons are enabled or disabled as appropriate.
=> Check for suggestions inside non-empty selections

server/middleware/deduplicateSlash.ts
N/A
1. Visit the review app.
2. Visit some paths with duplicating slashes (see below) and ensure they redirect you to the "Page not found" screen, and not http://test.com:
- /test.com
- //test.com
- ///////////test.com
- /dash//test.com
- //dash/////////////test.com
=> fix: correctly deduplicate repeating slashes in request url

client/containers/Pub/PubDocument/PubHeaderFormatting.tsx, client/containers/Pub/PubDocument/pubHeaderFormatting.scss
#2681
1. Open a draft and ensure there is a vertical divider between the suggested edits buttons and the Pub word count button in the formatting bar.
=> feat: add vertical line divider for suggested edits controls

client/components/FormattingBar/buttons.ts, client/components/FormattingBar/controlComponents/SuggestedEditsTogglePopover.tsx, client/components/FormattingBar/controlComponents/suggestedEditsTogglePopover.scss, client/components/FormattingBar/utils.ts
#2593
1. Hover the suggestion mode toggle button. You should see a popover with some text that describes its function.
=> feat: add popover to suggested edits toggle button

client/utils/upload.ts
Resolves #2708
1. Upload a file (Pub media, download, etc)
2. Ensure the filename in the assets.pubpub.org URL looks like `https://assets.pubpub.org/{filename}-{timestamp}`
=> feat: add file name in assets.pubpub.org uploads

server/login/api.ts, server/models.ts
Adds the cookie max-age, which should have been present and has somehow been removed. Will avoid caching logged in pages and should help fix remaining cache login issues.
=> Add cache cookie max-age

server/login/api.ts
No idea how this keeps getting left off, but, here we are. Should be up to speed now.
=> Hotfix: add cache cookie back again

server/zoteroIntegration/api.ts
#2728 
perform same steps as in issue above:
1. Open a pub with an account that is not connected to Zotero and open dev console
2. Make a citation
3. Close citation
4. Re-open citation
6. Notice call to /api/zoteroIntegration, which eventually fails
=> fix:return 404 on absent zotero integration

server/routes/robots.ts
Resolves #2738 
1. Visit any community's /robots.txt locally or on duqduq and make sure disallow is set to `/`. 
2. Run locally with prod env variable set, make sure robots.txt only disallows login, and the sitemap link is present.
=> disallow bots in robots.txt if not prod

server/utils/__tests__/ssr.test.tsx, server/utils/ssr.tsx
Per [this](https://support.google.com/webmasters/answer/9689846?hl=en#make_permanent), we shouldn't rely on robots.txt to block indexing. Instead, per [this](https://developers.google.com/search/docs/crawling-indexing/block-indexing), we should put meta tags on all pages that shouldn't be followed.
This does that for all non-prod sites. It's a little brute force, so if there are better places to pass down unlisted, happy to entertain that.
n/a
1. Visit on local or instance and make sure robots noindex meta is set
2. Set pubpub prod environment locally and make sure noindex is _not set_ on most pages, but _is_ set on, e.g., a dashboard page.
=> add noindex meta to all non-prod pages

client/containers/DashboardImpact/dashboardImpact.scss
Metabase updated its embed styling to put the filter on the left instead of the right, which caused the header of the Impact tab to overlap it on some browser sizes. This fixes that.
_Test Plan_
Visit an impact tab at a few browser sizes and make sure it works ok?
=> fix: Impact iframe positioning

server/passwordReset/queries.ts, server/user/model.ts, stubstub/modelize/builders.ts
Types the User model with methods from `passport-local-sequelize`
From 399 -> 397 errors in 109 files.
=> dev: add types for `passport-local-sequelize`

server/activityItem/queries.ts, server/community/hooks.ts, server/pub/model.ts, server/scopeSummary/hooks.ts, server/threadComment/hooks.ts, server/utils/activityHooks.ts, types/sequelize-actorid-override.d.ts
This PR creates an override for a `sequelize` Model's options, such that e.g. these are typescript legal
```ts
Pub.create({...}, {actorId})
Pub.destory({actorId})
``` 
This patch affects every single model we use, even though not every model is able to use this actorId.
However, this was also the case before, and this is a much easier way of fixing this type issue.
This also fixes some other type errors related to activityHooks (where the `actorId` is used)
From 399 -> 343 errors in 99 files.
=> dev: allow actorId as a parameter for sequelize.create etc, and fix activityHook related type errors

server/routes/authenticate.tsx
#2775 
0. [optional, only if in dev] rather than `localhost` url, navigate to `lvh.me`
1. log in
2. navigate to user privacy settings
3. click 'activate'
4. if you are redirected to Zotero, the bug is addressed. Feel free to continue through the rest of the oauth flow for good feeling.
Also implements a redirect if a non-logged-in user attempts to visit `/auth/zotero`, where before it would route them through to Zotero for the usual oauth flow.
=> fix: add next() in zotero middleware

client/components/UserNotifications/UserNotificationPreferences.tsx, client/components/UserNotifications/userNotificationPreferences.scss, client/containers/Legal/Legal.tsx, client/containers/Legal/PrivacySettings.tsx, server/hooks.ts, server/routes/legal.tsx, server/userNotification/create.ts, server/userNotification/hooks.ts, server/userNotificationPreferences/model.ts, server/userNotificationPreferences/queries.ts, tools/migrations/2023_07_24_addDiscussionThreadEmailNotificationPreference.js, types/userNotification.ts
Resolves #2745
This PR adds a new option to receive email notifications for discussions you are subscribed to. Existing notification preferences apply to these new emails, so if you opted out of receiving notifications for discussions threads, you will not get an email when threads receive a reply.
The email contains an Unsubscribe button that, when clicked, redirects to a new Notifications preferences section on the user privacy page.
1. Log in to PubPub. Enable the "Receive discussion thread emails from PubPub" option using the user Privacy Settings page.
2. Create a Pub.
3. Log into another account in separate browser or private browsing window.
4. Visit the same Pub and create a few discussions/replies. The original user should receive an email with notifications for each new …
=> dev: add discussion email notification preference

client/components/Editor/plugins/suggestedEdits/appendTransaction/appendTransaction.ts
Resolves #2689 
On the review instance
1. Create a math node
2. Turn on suggestion mode
3. Edit the math node. The edits should appear directly, not as suggestions
=> Ignore transactions inside of math nodes

server/routes/passwordReset.tsx
Seems to be a semi-common regression in sequelize https://github.com/sequelize/sequelize/issues/15702
https://kfg.sentry.io/issues/4397182310/?project=1505439&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-stream&sort=inbox&stream_index=1
1. Go to /password-reset
2. See it work agian
=> fix: make `/password-reset` not crash

server/routes/dashboardActivity.tsx, server/routes/dashboardCustomScripts.tsx, server/routes/dashboardDiscussions.tsx, server/routes/dashboardEdges.tsx, server/routes/dashboardFacets.tsx, server/routes/dashboardImpact.tsx, server/routes/dashboardMembers.tsx, server/routes/dashboardPage.tsx, server/routes/dashboardPages.tsx, server/routes/dashboardReview.tsx, server/routes/dashboardReviews.tsx, server/routes/dashboardSettings.tsx, server/routes/dashboardSubmissions.tsx, server/utils/queryHelpers/pageGet.ts
Fixes errors like these: https://kfg.sentry.io/issues/4405829345/?project=1505439&query=is%3Aunresolved+cannot+read+properties+of+null&referrer=issue-stream&statsPeriod=14d&stream_index=0
1. Go to random community
2. Go to /dash/collection/some-name/impact
3. See if you get "Not found"  instead of Application Error
4. Go to /dash/pub/some-name/impact
5. See if you get "Not found" instead of Application Error
Ideally also check for
/dash/.../some-name/settings
.../members
.../facets
.../submissions
.../reviews
.../activity
=> fix: throw not found error on /dash/.../impact for invalid collections/pubs instead of crashing

workers/tasks/export/pandoc.ts
Fixes a small logic error where we were only including the DOI and elocation in JATS exports if the Pub was in a primary collection. This could cause Pubs with DOIs but without primary collections (e.g. https://baas.aas.org/pub/httpsbaasaasorgpub2023i025/release/1) to export JATS with no DOIs.
#2792 
1. Visit a Pub with a DOI that is not in a primary collection (e.g. `/pub/httpsbaasaasorgpub2023i019`)
2. Clear its JATS exports in the DB (or create a new release)
3. Download JATS
4. Verify that elocation and DOI appear in the JATS
5. Visit a Pub with a DOI that is in a primary collection (e.g. `/pub/2022i091/release/1`)
6. Clear its JATS exports in the DB (or create a new release)
7. Download JATS
8. Verify that elocation, DOI and issue metadata (e.g. Volume and Issue) appear in the JATS …
=> fix: add DOI and elocation to JATS even if no primary collection

server/signup/api.ts, server/signup/queries.ts
Resolves #2807
No real functionality change here, but we should stop seeing those extraneous log messages for something that's not actually an error
Visit the signup page
Attempt to sign up again with your email address
Observe that the response code is 409 conflict and no log message is printed
=> Return 409 instead of 500 for duplicate emails

server/release/queries.ts, server/utils/firebaseAdmin.ts
~Right now on duqduq, creating a release times out every time with this error: https://kfg.sentry.io/issues/4380557716/events/bc6079257f1e4ee39336b67ff82fbdb0/~ Update: That was fixed by increasing the max connections on dev from 1 to 12. But this still seems like a good idea
According to [this comment](https://github.com/sequelize/sequelize/issues/10858\#issuecomment-549817032) this can happen when queries inside a transaction callback aren't passed the transaction (and are therefore run outside the transaction). 
Sequelize docs: https://sequelize.org/docs/v6/other-topics/transactions/#managed-transactions
Try creating a release on the review instance
=> Run all queries in transaction to avoid connection errors

server/export/queries.ts, tools/exportCollection.js, utils/pub/downloads.js
This fixes what I think was a potentially problematic issue with download behavior. Previously, the `/api/export` query returned a valid download if the historyKey of the latest export was greater or equal than the historyKey sent to the query. Though rare, this could create the condition where, if a Pub's latest release exports failed, or was deleted prior to regeneration, and an export on a draft had subsequently been created, the API would effectively leak draft exports.
This fixes that gap by only returning matched exports if the historyKey sent to the query matches a historyKey in the database. I think this may also solve some of the sentry errors related to download routes, e.g. https://kfg.sentry.io/issues/3913456206/?project=1505439&query=is%3Aunresolved&referrer=issue-stream&strea …
=> fix: Don't export pubs with historyKey > latest

workers/tasks/import/bulk/README.md, workers/tasks/import/bulk/directives/pub.ts
Makes two fixes to bulk imports to account for some db and prosemirror schema drifts over time: downloads, which require a JSON wrapper, and file cards, which require some attribute data.
It's complicated to test, but ping Gabe for an example directive and directory if you'd like to.
=> fix: bulk import inlineFIle and downloads

client/webpack/webpackConfig.prod.js, package.json
Right now our stack traces are showing filenames just prefixed with `/app` rather than `/app/dist` as I thought before. This PR adjusts that path.
Example issue: https://kfg.sentry.io/issues/4443846320/events/053d757956f641f5a4c89a1892c87667/
It also explicitly sets a release for the frontend files because the plugin isn't detecting the heroku env vars.
=> Set release for frontend sourcemap uploads

client/containers/UserCreate/UserCreate.tsx, server/user/api.ts
Previously, newly created users were not receiving the cache cookie but were being logged in. When this coincided with a cache refresh, it meant logged in pages were sometimes cached and displayed to other users. This fixes that problem by adding the cache cookie on user signup and a cachebreaker to the redirect.
1. Create new user locally.
2. Make sure the request to the users endpoint returns a `pp-no-cache` cookie.
3. Make sure the redirect request contains `pp-no-cache`
4. Repeat on duqduq, making sure that after new user creation, accessing duqduq from incognito doesn't load as if you are that new user.
=> hotfix: Add cache cookie and cachebuster to user signup

client/components/Layout/LayoutPagesCollections.tsx, utils/api/contracts/pub.ts, utils/api/schemas/pub.ts, utils/layout/types.ts, utils/layout/validators.ts
- fix: properly coerce custompublishedat in zod schema
- fix: allow full pages to be sent as collections-pages items
- fix: allow doi previews/deposits to be null/empty objects
=> fix: correct validation for customPublishedAs and collection-pages blocks

server/submission/emails.tsx, server/utils/email/reset.ts
Implements expected behavior addressed by #2776.
1. Enable submissions for a collection.
2. Add a personal email address to the list of addresses to be CC'd when a Pub is submitted (target email addresses).
3. Submit a Pub to the collection.
4. Confirm the submitter's email address recieves a message with all target email addresses CC'd.
5. Reply to the email from the submitter's email address. The first target email address should receive this email.
=> fix: move workflow target emails to cc; add Reply-To for first target address

workers/tasks/export/metadata.ts
#2854 
Type changes introduced in #2793 caused styles to be undefined in exports, causing them to always export [1], etc. unless a custom style was set on the citation. This restores citation styles.
- Create a pub and set a citation style.
- Export to word and pdf. Make sure citation style matches export.
=> hotfix: Get inlineCitationStyles from facets

workers/tasks/export/html.tsx
Currently, if you have two of the same references in a document with two different custom inline citation labels, and export to PDF/HTML, it will always export the PDF/HTML so that every inline citation label for that reference is the last custom label, rather than using the custom label for each one. 
The reason is that during the process of creating the HTML document which gets turned into a PDF, we are giving every inline citation with the same "fingerprint" -- e.g. the same reference -- the same ID, which when run through prosemirror-reactive, results in every node with that ID being replaced with the last version of the node. The result is a PDF/HTML export that deviates from the intent in the pub. Minimal example:
**Pub with multiple citations of the same reference with different …
=> Hotfix: allow multiple custom labels for the same reference in PDF exports

client/webpack/webpackConfig.prod.js
Some tables could not be rendered in prod because of `prosemirror-tables` switching to ES6 Classes.
`ts-loader` transpiles our classes to functions, but not those of our dependencies, which causes an issue when we are extending external classes that use native ES6 classes.
Basically
```ts
import { TableView } from 'prosemirror-tables'
export class OurTableView extends TableView {
constructor(){
super()
}
}
```
`OurTableView` gets transpiled to `es5` as per our `tsconfig.client.json`, but `TableView` isn't, which causes errors like
`Uncaught TypeError: Class constructor TableView cannot be invoked without 'new'`
because the transpiled `ES5` code is doing something like `TableView.call(null)`, which ya can't do.
=> fix: make newer version of prosemirror-tables work by also using `esbuild-loader` in prod 

client/containers/Pub/PubDocument/PubInlineSuggestedEdits.tsx, server/user/__tests__/api.test.ts, server/user/api.ts
#2861 
Modified existing test to work properly.
Otherwise:
1. Go to Draft with suggested edits enabled (to be disclosed URL) as a non-super admin user
2. Create some suggested edits
3. Hover over them checkmark
4. Should say "Approve edit suggested by <name>" instead of just "Approve edit"
This was caused by the permissions never returning `{ read: true}` except for superadmins, not even for looking at your own user information, because that data was never passed to the permissions.
The "user you are looking at" is supposed to be extracted by this `getRequestIdsFunction`, the `submittedUserId`
https://github.com/pubpub/pubpub/blob/bbf520c08d7e7ccc2908b7d38bc05dd35bb8b9b7/server/user/api.ts#L10C1-L18C3
However, it extracts that from the `body`, which a `GET` request isn't supposed to have, …
=> fix: remove permission check for get user endpoint

init.js, package-lock.json, package.json, server/server.ts
This PR does two things: remove the newrelic agent and lower the number of performance transactions we send to sentry from the backend. Both of these changes are intended to help keep us below our quotas:
- On Sentry we hit our performance limit and used all our dynamic spend in just 3 days of requests, so this will now capture 5% of our requests. In the future we may want to intentionally exclude some routes so that we can concentrate the tracing on the most useful ones
- On newrelic, the traces use about 3GB/day of our 100GB per month, so we usually exceed the quota by a small amount. Removing those should easily free up enough space for all of our logs
=> Send less data to our monitoring services

server/pubEdge/__tests__/api.test.ts, utils/api/schemas/pubEdge.ts
#2903
1. Create a pub
2. Add a connection
3. Try to update the connection
Also added a test to prevent regression
Cause was the connection schema not allowing for `null` values for the `targetPubId` or `externalPublication`, but the frontend sends that when updating.
=> fix(#2903): fix connections not being able to be updated

types/layout.ts, utils/api/schemas/layout.ts
#2910 
1. Create Page/Collection
2. Add "Create Pub" submission banner in Layout
3. Set a default collection, or multiple
4. Save
5. Reload page
6. Check that default collections are still there
7. Go to page/collection
8. Create Pub
9. Check that it has those collections
=> fix(#2910): allow setting of default collectionIds for create pub banner

server/facets/__tests__/api.test.ts, server/facets/__tests__/update.test.ts, server/facets/create.ts, utils/api/schemas/facets.ts
Facets were not updating if you reverted to the higher facets setting.
1. Go to a Pub
2. Change a facet setting (e.g. setting the labels for tables to "Strange Tables")
3. Save
4. Click "Revert to community/collection value"
5. Save
6. Reload
7. Change should be saved.
=> fix: allow facets to revert to higher scope value

client/utils/hydrateWrapper.tsx, client/utils/initialData.ts, server/Html.tsx
This PR changes the way the `initialData`/`viewData` is read/serialized.
Before, it was `JSON.stringify`'d on an attribute of a script at the bottom. Then that attribute would be read with JSON.parse.
Now, I just set the contents of the HTML directly using `dangerouslySetInnerHTML`.
Why?
Using base `JSON.stringify` in React leads to data that looks like
```html
<script
id="initial-data"
type="text/plain"
data-json='{"communityData":{"id":"99608f92-d70f-46c1-a72c-df272215f13e","subdomain":"hdsr","domain":"localhost:9876","title":"Harvard Data Science Review","citeAs":null,"publishAs":null,"description":"","avatar":"https://assets.pubpub.org/3bvhlseh/51561410323594.png","favicon":"https://assets.pubpub.org/950hnhqt/61559316763143.jpg","accentColorLight":"#fdfdfd","accentColorDark"'
/>
``` …
=> RFC: serialize initial data more efficiently to reduce HTML page size by up to 30% uncompressed/17% compressed

server/routes/pubDocument.tsx, server/utils/queryHelpers/pubEnrich.ts, utils/caching/getCorrectHostname.ts
- fix: include community in pub edge includes in for sibling edges to prevent weird connection 500 edge case
- fix: revert base hostname for pubdoc to be req.hostname as that has been proven to work
=> fix: edge case where pubs with sibling edges of different domains would 500

client/containers/DashboardOverview/CollectionOverview/collectionState.ts, client/containers/DashboardSettings/PubSettings/PubSettings.tsx, package-lock.json, package.json, server/pub/__tests__/api.test.ts, server/pub/api.ts, server/pub/queries.ts, server/server.ts
- fix: show better error message for already used slugs for pubs
- fix: add tests and more readable zod errors
#2954
Someone was trying to update their Pub's slug to an already existing one for quite a while, see the Sentry events linked in the issue.
1. Create new pub
2. Try to name the slug the same as an already existing one (for demo.pubpub.org you can use `oz6wzj9s` as an existing one)
3. see that you get an error message saying the slug is already in use
How the error message looks
I also made Zod errors a bit more readable than before using a package `zod-validation-error`, since I was looking at the error handling anyway.
This will mostly be useful for the SDK, but could theoretically be used to build a more generic error display system on the client, although that's not very high …
=> Show user feedback when slug already exists, and make zod errors prettier

server/routes/pubDownloads.ts
#2964 
1. Go to \<base\>/pub/r2s2rfo7/download/pdf
2. See 404 instead of unhandled
I decided to handle this the same way as releases are handled, i.e. check whether the community is valid and then just forward it
https://github.com/pubpub/pubpub/blob/c2c9d9b880892ac2068b29f0299a7eebfa8f4443/server/routes/pubDocument.tsx#L227-L230
=> fix: handle pub downloads from base pubpub

client/components/Menu/Menu.tsx, client/containers/Pub/PubDocument/PubBottom/ReadNextSection.tsx, client/containers/Pub/PubHeader/collections/CollectionBrowser.tsx, client/utils/collections.ts, server/collectionPub/api.ts, server/collectionPub/queries.ts, server/collectionPub/schemas.ts, server/routes/pubDocument.tsx, utils/api/contracts/collectionPub.ts, utils/collections/getNextCollectionPub.ts
- feat: allow GET /api/collectionPubs to be paginated and make it slightly more efficient
- feat: find next pub to read on serverside
- feat: add infinite scroll to CollectionBrowser
#2979 
Previously, repeated fetching of very large collections over `/api/collectionPubs` through the Collection Dropdown could cause the DB to become overwhelmed.
This was especially problematic when crawlers crawled a ton of Pubs in very large collections at the same time, as the query would never succeed, therefore never cache, and would continue to bring too high of a load on the DB.
This PR changes the way that the Pubs in the Collection Dropdown are fetched. Instead of fetching everything all at once, now only 10 pubs are fetched at a time, the rest being loaded in on scroll.
Pubs will also only start …
=> perf: Add infinite scroll to collection dropdown/minimize calls to /api/collectionPubs

client/containers/Pub/PubHeader/collections/CollectionBrowser.tsx
After clicking the collection browser thingy, a small "0" shows up while the first collection pubs are loading.
1. Go to `pub/2022n6i100p01/release/1?readingCollection=dee6a02a` on BAAS
2. Set throttling to `Slow 3G`
3. Click on Collection Browser
4. Observe no `0`
https://github.com/pubpub/pubpub/assets/21983833/5bf2818b-3b01-4bae-b2fb-6c9f629bc7a8
https://github.com/pubpub/pubpub/assets/21983833/edc08f09-3c08-493c-b643-a13f7712f7ae
This was because I added a check to see if the list of pubs was not empty, but did it in the lazy way, e.g.
```tsx
{pubs && pubs.length && pubs.map(...)}
```
I changed it to
```tsx
{ pubs?.length > 0 ? pubs.map(...) : null }
```
=> fix: Remove annoying "0" when collectionPubs are loading

client/components/Layout/Layout.tsx, client/containers/App/App.tsx, client/containers/DashboardCustomScripts/DashboardCustomScripts.tsx, client/containers/Pub/PubDocument/PubDocument.tsx, client/webpack/lazyLoadedModules.js, client/webpack/webpackConfig.dev.js, client/webpack/webpackConfig.prod.js, server/Html.tsx, utils/analytics/createAnalyticsInstance.ts, utils/analytics/ignoredPaths.ts, utils/analytics/thirdPartyPlugins.ts, utils/analytics/useAnalytics.ts, utils/analytics/useLazyLoadedAnalyticsInstance.ts, utils/analytics/usePageOnce.ts
This PR allows for the following flow
1. At page load, our analytics plugin is loaded, and a pageview event is sent
2. If the user has some third party analytics enabled, that plugin is lazy loaded immediately afterwards OR after accepting the GDPR cookie banner if using a plugin which requires setting cookies (for now only GA)
Additionally, it improves how 3rd party plugins are defined, and cleans up the analytics code a bit.
#2998 
<details>
<summary> 
<h2>Test Plan</h2>
<hr/>
</summary>
The current setup for features per community is
- `demo`: uses new analytics, does not use 3rd party plugins
- `jtrialerror`: uses new analytics, uses google analytics
- `eric`: uses custom analytics, uses simple analytics
For each of these tests, open inspector and clear cookies, and disable adblock …
=> feat: lazy load analytics modules

client/components/Layout/Layout.tsx, client/containers/Pub/PubDocument/PubDocument.tsx, client/containers/Pub/PubHeader/Download.tsx, server/analytics/api.ts, utils/analytics/useAnalytics.ts, utils/api/schemas/analytics.ts
- refactor: require community name/subdomain for track events
- feat: add country code to data
- feat: add isProd flag to analytics event payload
This semi-finalizes the schema for analytics.
Explanation of the extra flags
This makes grouping events easier in metabase.
Before I only required this info for pageviews, but I now also do for track events.
This allows us to use a different map in metabase that is slightly nicer.
Specifically, this map has much easier to see/click countries. To pick a completely random and non-biased example, the Netherlands is quite hard to see on the default one.
I decided that it would be much easier to store Prod and Dev analytics in the same db. 
The way metabase works means we basically have to duplicate every view/model/dashboard if we use two different …
=> feat: add additional fields to the analytics schema

workers/tasks/export/styles/printDocument.scss
This PR:
- Adds small gap between top-left and top right margin titles
- Ensures the titles are top-aligned regardless of line breaks
Resolves #3024
Export a PDF with a long title and a long community name + collection title. The titles in the margins should not bleed into each other, and should stay vertically aligned to the top of the page.
Short top-left title:
Long top-left title:
=> PDF margin title fixes

client/components/AttributionEditor/AttributionDetailControls.tsx, package-lock.json, package.json, server/pubAttribution/__tests__/pubAttribution.test.ts, server/pubAttribution/api.ts, utils/api/schemas/attribution.ts, utils/orcid.ts
Closes #3014 
1. Run tests
1. Open network tab
2. Create new attribution for a pub
3. Try to add the following orcids:
- 0000-0000-0000
- https://orcid.org/0000-0000-0000-0000
- http://orcid.org/0000-0000-0000-0000
- https://www.orcid.org/0000-0000-0000-0000
- orcid.org/0000-0000-0000-0000
- www.orcid.org/0000-0000-0000-0000
4. Observe that the response of all of these is `{"orcid": "0000-0000-0000-0000"}`
5. Also do this for collection attributions
6. Check that when creating an orcid with `https://orcid.org`, this is gone when reloading 
7. Try to create some invalid orcids and observe an error message popping up, AND that the API response 404s.
I decided to allow `https://orcid.org/ID` to be filled in on the frontend and to be accepted by the backend, but have these be transformed into …
=> fix: add client and server side validation for orcids

client/utils/hydrateWrapper.tsx, utils/analytics/plugin.ts
- fix: allow stitch even with new analytics
- chore: add analytics lambda endpoint
Currently Heap and New analytics cannot both be turned on at the same time. Specifically, heap would not get initialized when new analytics is turned on. This PR gets rid of that flag.
It also sends the events to the new AWS endpoint instead of the old /api/analytics/track endpoint.
(on demo, on either qubqub or duqduq)
1. Open network tab
2. Go to home
3. See event to `https://yhzkpvgmsji7wkkmeplrtgoj5y0qbzpp.lambda-url.us-east-1.on.aws` with a payload and `event: 'page'` and an event to `heap.io`
4. Go to a collection
5. See event to AWS endpoint with `event: 'collection'` and an event to `heap.io`
6. Go to a pub
7. See event to AWS endpoint with `event: 'pub'` and an event to `heap.io`
I hardcoded the …
=> feat: allow heap and new analytics to be used simultaneously, and add AWS endpoint instead of local one

utils/analytics/createAnalyticsInstance.ts, utils/analytics/ignoredPaths.ts, utils/analytics/useLazyLoadedAnalyticsInstance.ts, utils/analytics/usePageOnce.ts, utils/api/schemas/analytics.ts
- **fix: catch many cases where no analytics should be sent**
- **fix: allow for base pubpub events to be tracked**
Resolves #3050 
1. Go to the most common pages on `www`, e.g. `/`, `/explore`.
2. See a working page
___
1. Go to `/dash/pub/<existing slug>/settings`
2. See working page
___
(optional check)
1. Go to `/pub/\<fake slug\>`
2. Observe no data being sent to `/api/analytics/track`
This was due to naive relying on the `initialData` types. For some pages, such as dashboard pages, 404s, and base PubPub, these do not reflect the actual initial data.
Dashboard pages and 404s are now more explicitly ignored, and additional access checks have been put in place.
=> fix: fix blank screen on settings pages and www.pubpub.org not loading 

client/components/FormattingBar/controlComponents/ControlsFootnoteCitation/CitationBuilder.tsx, server/collectionPub/__tests__/api.test.ts, server/collectionPub/permissions.ts, server/routes/__tests__/pubDownloads.test.ts, server/routes/pubDownloads.ts, server/user/__tests__/api.test.ts, server/user/api.ts, server/zoteroIntegration/__tests__/api.test.ts, server/zoteroIntegration/api.ts
- fix: wrap it before you get it
- feat: add tests for 404s
- fix: fix assertion errors, just 403 if collection pub is missing
- fix: add tests for collectionpub case
Lots of 500s that clog up my inbox.
Tried to fix the most common ones I see in sentry.
At least two kinds of errors.
Both fixed by wrapping it in this error handler also used in `/pub/slug`
https://kfg.sentry.io/issues/4444264955/?project=1505439&query=&referrer=issue-stream&statsPeriod=7d&stream_index=4
https://kfg.sentry.io/issues/4444036431/?project=1505439&query=&referrer=issue-stream&statsPeriod=7d&stream_index=5
https://github.com/pubpub/pubpub/blob/e4def7d6ade7734b8f30dd1fc050e211ff0680d7/server/routes/pubDownloads.ts#L14-L20
https://github.com/pubpub/pubpub/blob/e4def7d6ade7734b8f30dd1fc050e211ff0680d7/server/routes/p …
=> fix: get rid of some 500s

server/Html.tsx
N/A
N/A
N/A
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since the acquisition, numerous issues have emerged (https://github.com/polyfillpolyfill/polyfill-service/issues/2835, …
=> refactor: replace `polyfill.io`

server/userNotification/__tests__/hooks.test.ts, server/userNotification/create.ts, server/userNotification/hooks.ts
Discussion emails are sent by an `afterCreate` hook on `UserNotification` creation. However, these hooks don't run by default on bulk methods like `UserNotification.bulkCreate`.
https://sequelize.org/docs/v6/other-topics/hooks/#model-hooks:
>Note: methods like bulkCreate do not emit individual hooks by default - only the bulk hooks. However, if you want individual hooks to be emitted as well, you can pass the { individualHooks: true } option to the query call. However, this can drastically impact performance, depending on the number of records involved (since, among other things, all instances will be loaded into memory).
Resolves #3035
Create a pub, comment on it, then reply from another account. You should receive an email.
~I'm not quite sure how this ever worked, since it doesn't seem …
=> Fix discussion email sending

client/components/ContributorsListCondensed/ContributorCondensed.tsx, client/components/ContributorsListCondensed/ContributorsListCondensed.tsx, client/components/ContributorsListCondensed/contributorCondensed.scss, client/components/index.ts, client/containers/Pub/PubDocument/PubDocument.tsx
Adds a condensed contributor to the Pub body behind a feature flag to match Arcadia's current manual version.
- Load arcadia-research locally or on dev, where feature flag is already set.
- Load an extent pub, e.g. http://localhost:9876/pub/idea-defining-actin/release/2?collectionSlug=functional-annotation
- Check that new section matches, with addition of avatar and links to profiles.
- Check that it breaks similarly on mobile (1024 and 728)
Launching will require setting existing contributor section to display none.
After that's done, add `bodyContributors` feature flag and arcadia-research community to flag.
- Could use community primary/secondary colors in the future rather than hard-coding
- Could be extended in the future to automate alphabetic sorting of contributor roles
=> Feat: condensed body contributor

server/community/queries.ts, tools/emailActivityDigest.ts
#3035 
Fixes a new error in the activity digest script: https://my.papertrailapp.com/groups/14651822/events?q=program%3Aapp%2Fscheduler.3606&focus=1714219360833110031&selected=1714219360833110031
Also modifies the script to explicitly send these errors to sentry since they're being caught right now.
Comment out the mailgun sending lines (L52-58) in `emailActivityDigest.ts`, then run `npm run tools -- emailActivityDigest` and it shouldn't error when rendering a digest email. Or just wait until this is merged and check that it succeeds via papertrail.
=> Fix type error preventing activity digest email sending

client/utils/collections.ts
Resolves #3084
1. Go to `pub/perspective-publishing-round-one/release/2?readingCollection=fe6424b5` on Arcadia
2. Click on the CollectionBrowser in the top right.
3. See only one entry
___
Regression prevention
1. Go to a pub in a large colllction e.g. `/pub/2022n8i101p01/release/1?readingCollection=15dae834` on BAAS
2. Click on the CollectionBrowser in the top right
3. Check that all entries are loading one by one, and that it doesn't stop after loading 10 or so.
=> fix: prevent collectionpubs being fetched twice for smaller collections

client/components/AttributionEditor/AttributionDetailControls.tsx, types/use-analytics.d.ts, utils/analytics/plugin.ts, utils/analytics/useAnalytics.ts
Just shifts arounds some types in order to make `@pubpub/sdk` pass `tsc` checks again. Very annoying, would liked to have been able to solve it a different way, but this is the quickest.
No change, is only a type change.
=> fix: small type changes to get the sdk to compile master again

client/containers/CommunityCreate/CommunityCreate.tsx, client/containers/PasswordReset/PasswordReset.tsx, server/community/api.ts, server/community/queries.ts, server/passwordReset/api.ts, utils/api/contracts/community.ts
This PR removes some uncaught errors that were introducing noise in Heroku alerts, making it seems like there was something wrong when either
1. A user was trying to reset a password of an email not belonging to any account
2. A user was trying to create a community with an already existing url
I solved these like so
We now return a `200 'success'` whether the email exists or not. This way, you cannot brute force guess user emails using this path. I guess you can still do this on the account creation screen, but that is a separate issue that could/should be fixed.
We now return a `409 "URL already used"` error in case the url is already in use. 
It also shows this to the user, so it's more clear why they cannot create a certain community.
=> fix: handle some 500s more gracefully

server/utils/citations/structuredCitations.ts
Some pubs with lots of cites are timing out at Heroku because the crossref API is unstable at the moment (https://status.crossref.org/incidents/d7k4ml9vvswv)
This reduces the timeout per cite down to 1 second from 8, and if there's an error, returns the raw doi instead of an error message, so that pages can still be understood by readers.
Longer term, we should probably implement a strategy for now relying on the Crossref API to render cites every time a page is re-rendered out of cache — either storing the results of the API request directly after the first time it's called, or, alternately, creating our own cache of the crossref API.
Additionally, we should try to find a way to send requests through the "polite" API, for better handling, per this blog post: …
=> Hotfiix: handle crossref api errors better

client/containers/DashboardSettings/CommunitySettings/SocialSettings.tsx, client/containers/User/UserEdit.tsx, client/containers/User/UserHeader.tsx, client/utils/navigation/communityNavigation.ts, tools/migrations/2024_06_12_replaceLinkedinHandles.js
Resolves #3082
Note: this requires a small migration (more of a fix) to be run to retroactively add `in/` to the existing linkedin handles.
1. Go to a communities settings
2. Add a bluesky handle
3. Save
4. Observe that no @ is present, as it should (oversight from me that this snuck in, was thinking of mastodon too much)
Do the same for your user account.
1. Go to a communities settings
2. Add a linkedin handle
3. Save
4. Observe that the handle you added becomes a link of the form `https://linkedin.com/<handle>` rather than `https://linkedin.com/in/<handle>` as it is on prod.
Do the same for your user account (in theory we could have limited the users to `in/`, which, as i've learned, stands for "individual", rather than for the "in" in linkedin 🤯. Seems weird to limit this though)
=> fix(#3082): fix linkedin and bluesky handles

server/utils/citations/generateCitationHtml.ts, server/utils/citations/structuredCitations.ts
Appends a mailto to our user agent string to move to Crossref's "polite" pool, per https://api.crossref.org/swagger-ui/index.html and thanks to @larsgw: https://github.com/citation-js/citation-js/issues/228
I need help figuring out how to test this to make sure it's working.
=> Hotfix: Customize Cite.js user agent for Crossref polite pool

client/containers/DashboardOverview/CollectionOverview/PubSelect.tsx
Reduces number of manyPubs queries from collection add button, which relieves server load and makes it less likely communities hit rate limiting. Used same strategy as in [PinnedPubs.tsx](https://github.com/pubpub/pubpub/blob/284359e95afe039d7544c55451a7018e17f74684/client/components/LayoutEditor/LayoutEditorPubs/PinnedPubs.tsx)
- Visit a Collection overview
- With the network console open, click `add pub` button and search for a term
- See that the /api/user/search?q=text query is sent only once every ~200ms at maximum (this is what `PinnedPubs` was set to).
- Delete the text, wait 200ms, and make sure no empty query (api/user/search?q=) is sent.
- Search a common term ("ok" works on demo) and make sure pubs show up and you can add them.
=> dev: Debounce collection search

deposit/datacite/index.tsx, deposit/resource.ts, deposit/transform/pub.ts
#3168 
When it's Arcadia, deposits what would be JournalArticles as preprints.
Need help with this — but I think should be fairly straightforward to attempt to deposit to our test repository?
=> Use preprint for Arcadia datacite deposits

deposit/transform/pub.ts
Previously, depositing to Crossref (or even, I think, loading a DOI settings page that had been previously deposited) was throwing a date error because it assumed a Datacite deposit record JSON structure. I think that was causing a lot of dyno crashes, and in some cases was also preventing depositing.
```
/app/deposit/transform/pub.ts:250
const dateOfLastDeposit = new Date(depositJson.data.attributes.updated);
TypeError: Cannot read properties of undefined (reading 'attributes')
at <anonymous> (/app/deposit/transform/pub.ts:250:56)
at Generator.next (<anonymous>)
at fulfilled (/app/deposit/transform/pub.ts:2:61)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
This fixes that by checking to make sure the timestamp exists, and if not, defaulting to the …
=> fix: Crossref deposit error

client/components/Editor/schemas/code.ts
HTML exports with code blocks now have the language in the lang attribute of the `pre` tag.
1. Create a pub
2. Add three code blocks, with js, python, and none language set
3. HTML export
4. Check that the pre tags have `lang=javascript`, `lang=python`, and nothing set as the attributes
=> feat: add code attrs such as lang to statically rendered html code blocks

workers/tasks/export/export.ts, workers/tasks/export/html.tsx
Because we go from HTML to PDF, where iFrames are not supported, exporting to HTML previously stripped the iFrame url and replaced it with instructions to visit the main document to see interactive content. 
This allows HTML exports to maintain the original URL by passing the target into the `renderStaticHtml` function such that if we target pagedJS outputs, we strip the url, but if we target an html download, we don't strip it.
1. Visit a Pub with an iframe, e.g. `pub/jpfkepm9/draft`
2. Make a small change to regenerate cache
3. Export HTML
4. Open the HTML in a browser and make sure the iframe appears and the src is properly set
5. Export PDF
6. Scroll to where the iframe would be and make sure it has been stripped and replaced with language about how to view the original.
There was …
=> enhancement: Don't strip iframe url if target is html

server/pub/queryMany.ts, server/utils/queryHelpers/pubSanitize.ts
Makes it possible to get public discussions from the getMany query. Essentially, if the pub has a release, this will change the output of the query to:
- If `getDiscussions: true` is set, return public comments instead of private ones
- Not return the draft of the pub (will still return the draftId, which seems to be more used)
- Not return submissions on the pub
- Return only public exports (if `getExports: true` is also set)
The side effects of this PR should be fairly limited, as this only impacts `getPubsById`, which has limited call sites, mostly dashboards that do not make use of drafts or discussions. There is no other place in the app that sets a `releaseNumber` on `sanitizePub`, so that change will have no additional effect.
Part of the problem is it's unclear what the effect of …
=> fix: make querymany return public discussions when pub has release

client/components/Editor/schemas/audio.ts, client/components/Editor/schemas/iframe.ts, client/components/Editor/schemas/image.ts, client/components/Editor/schemas/video.ts
This adds the hideLabel value onto a `data-hide-label` attribute in the toDom function for images, videos, iframes, and audio.
=> update: Add hideLabel value to output HTML

server/scopeSummary/queries.ts
Might resolve #3245  ?
Hypothesis: when hooks are run, there might have been enough delay between syncing the write db that we end up reading unsynced data.  Instead, we force all `scopeSummary` queries to read from the master (write) db instead. that way we should be guaranteed to have the correct data.
All major write operations which have these hooks should probably run in a transaction instead, but that's quite some more work, and this should have a similar result for now.
https://sequelize.org/docs/v7/other-topics/hooks/#hooks-and-transactions
1. 🙈
=> fix: make scopeSummaries hooks always use main write database

server/activityItem/queries.ts, server/pubAttribution/queries.ts, server/signup/queries.ts, server/threadComment/queries.ts, workers/queue.ts
There is a similar issue with signups as was happening for #3245 , see 
- for signups: https://kfg.sentry.io/issues/6331780888/?project=1505439&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0
- for activity items: https://kfg.sentry.io/issues/6331759214/?project=1505439&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=1
- pubAttributions: https://kfg.sentry.io/issues/6334216570/?project=1505439&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=7
- createThreadComment: https://kfg.sentry.io/issues/6331844517/?project=1505439&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referr …
=> fix: fix many read replica issues

client/layouts/CollapsibleHeader/collapsibleHeaderData.ts
We are currently rolling out a new URL link in the elifesciences.org site header.
https://github.com/elifesciences/issues/issues/9146
We have not been able to test the change locally, as no-one of our team of four was able to to run an instance of PubPub or Storybook locally. https://github.com/pubpub/pubpub/issues/3257
=> Attempt to add the browse page link to eLife navigation

client/layouts/TwoColumnFooter/twoColumnFooterData.ts
https://github.com/elifesciences/enhanced-preprints-issues/issues/1252
We are updating carbon footprint information in our site footer.
https://github.com/elifesciences/enhanced-preprints-issues/issues/1252
We have not been able to test the change locally, as no-one of our team of four was able to to run an instance of PubPub or Storybook locally. https://github.com/pubpub/pubpub/issues/3257
=> Update footer with the new carbon certification information

client/containers/DashboardSettings/CommunitySettings/CommunityAdminSettings.tsx, package-lock.json, package.json, workers/tasks/archive.tsx, workers/tasks/archive/readableStreamClone.ts, workers/tasks/archive/siteDownloaderTransform.ts, workers/tasks/archive/sitemapUrlStream.ts
This PR swaps out [node-website-scraper](https://github.com/website-scraper/node-website-scraper) with a custom streaming implementation.
The transformer consumes a stream of URLs and yields streams of page HTML and asset files. The worker task pipes the emitted file streams into a ZIP archive stream, and finally an S3 upload stream. This means a limited number of file chunks are in memory at a given time -- unlike previously, where it was possible for the entire site contents to be in memory by the end of the task.
The worker task splits the sitemap URLs into `N=5` separate streams that are transformed concurrently. These five streams are each piped to the same sink (the archive/upload streams), so stream backpressure (and memory usage) is ultimately limited by the archive/upload …
=> use streaming archive approach

client/components/PubPreview/PubPreviewEdges.tsx
Resolves #3316
1. Archive a community.
2. Connected pubs in PubPreview components should link to the locally archived pub pages.
=> use full community pub url for local edge pub links

server/page/sanitizePageHtml.ts
- Fix an accessibility bug by allowing `<img>` elements to have an `alt` attribute.
- Make it easier to write accessible `html` by allowing the `role` attribute on all elements.
We are unable to build and test locally.
N/A
We noticed when editing an `html` block that `alt` attributes and `role` attributes are stripped. This change attempts to fix these accessibility bugs.
=> Allow alt and role attributes
